'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const SCAFFOLD_WRITE_PLAN_SCHEMA = 'xtend.scaffold.write-plan.v1';
const SCAFFOLD_WRITE_REPORT_SCHEMA = 'xtend.scaffold.write-report.v1';
const SCAFFOLD_GENERATED_OWNERSHIP_SCHEMA = 'xtend.scaffold.generated-ownership.v1';
const DEFAULT_OWNERSHIP_PATH = '.xtend-build/scaffold-ownership.json';
const GENERATED_MARKERS = Object.freeze([
  '@generated by XTend Scaffold',
  'Generated by XTend Scaffold'
]);

const DEFAULT_ALLOWED_ROOTS = Object.freeze([
  'components/',
  'docs/',
  'src/',
  'tests/',
  'xtendrmt/',
  '.xtend-build/',
  '.xtend-test-results/'
]);

function toBoolean(value) {
  return value === true || value === 'true' || value === '1' || value === 'yes';
}

function sha256(value) {
  return crypto.createHash('sha256').update(String(value || '')).digest('hex');
}

function byteLength(value) {
  return Buffer.byteLength(String(value || ''), 'utf8');
}

function stableJson(value) {
  return `${JSON.stringify(value, null, 2)}\n`;
}

function sortObjectByKey(value) {
  return Object.keys(value || {}).sort().reduce((sorted, key) => {
    sorted[key] = value[key];
    return sorted;
  }, {});
}

function normalizeRelativePath(relativePath) {
  if (typeof relativePath !== 'string' || relativePath.trim() === '') {
    return {
      ok: false,
      error: 'WritePlan entries require a non-empty relative path.'
    };
  }

  if (relativePath.includes('\0')) {
    return {
      ok: false,
      error: `WritePlan path "${relativePath}" contains a null byte.`
    };
  }

  const slashPath = relativePath.replace(/\\/g, '/');
  if (path.isAbsolute(slashPath)) {
    return {
      ok: false,
      error: `WritePlan path "${relativePath}" must be relative to the repository root.`
    };
  }

  const normalized = path.posix.normalize(slashPath);
  if (normalized === '.' || normalized === '..' || normalized.startsWith('../')) {
    return {
      ok: false,
      error: `WritePlan path "${relativePath}" must stay inside the repository root.`
    };
  }

  return {
    ok: true,
    path: normalized
  };
}

function normalizeAllowedRoots(allowedRoots) {
  const roots = Array.isArray(allowedRoots) && allowedRoots.length > 0 ? allowedRoots : DEFAULT_ALLOWED_ROOTS;
  return roots.map((entry) => {
    const raw = String(entry || '').replace(/\\/g, '/');
    const trailingSlash = raw.endsWith('/');
    const normalized = normalizeRelativePath(raw);
    if (!normalized.ok) {
      return null;
    }

    return trailingSlash ? `${normalized.path.replace(/\/$/, '')}/` : normalized.path;
  }).filter(Boolean);
}

function pathMatchesAllowedRoot(relativePath, allowedRoot) {
  if (allowedRoot.endsWith('/')) {
    return relativePath.startsWith(allowedRoot);
  }

  return relativePath === allowedRoot || relativePath.startsWith(`${allowedRoot}/`);
}

function isAllowedPath(relativePath, allowedRoots) {
  return allowedRoots.some((allowedRoot) => pathMatchesAllowedRoot(relativePath, allowedRoot));
}

function isInsideRoot(rootDir, absolutePath) {
  const resolvedRoot = path.resolve(rootDir);
  const resolvedPath = path.resolve(absolutePath);
  return resolvedPath === resolvedRoot || resolvedPath.startsWith(`${resolvedRoot}${path.sep}`);
}

function createEmptyOwnershipManifest() {
  return {
    schema: SCAFFOLD_GENERATED_OWNERSHIP_SCHEMA,
    files: {}
  };
}

function readOwnershipManifest(rootDir, ownershipPath = DEFAULT_OWNERSHIP_PATH) {
  const normalized = normalizeRelativePath(ownershipPath);
  if (!normalized.ok) {
    return {
      ok: false,
      path: ownershipPath,
      manifest: createEmptyOwnershipManifest(),
      errors: [normalized.error]
    };
  }

  const absolutePath = path.resolve(rootDir, normalized.path);
  if (!isInsideRoot(rootDir, absolutePath)) {
    return {
      ok: false,
      path: normalized.path,
      manifest: createEmptyOwnershipManifest(),
      errors: [`Ownership manifest path "${normalized.path}" resolves outside the repository root.`]
    };
  }

  if (!fs.existsSync(absolutePath)) {
    return {
      ok: true,
      path: normalized.path,
      manifest: createEmptyOwnershipManifest(),
      errors: []
    };
  }

  try {
    const parsed = JSON.parse(fs.readFileSync(absolutePath, 'utf8'));
    return {
      ok: true,
      path: normalized.path,
      manifest: {
        schema: parsed.schema || SCAFFOLD_GENERATED_OWNERSHIP_SCHEMA,
        files: parsed.files && typeof parsed.files === 'object' ? parsed.files : {}
      },
      errors: []
    };
  } catch (error) {
    return {
      ok: false,
      path: normalized.path,
      manifest: createEmptyOwnershipManifest(),
      errors: [`Failed to read Scaffold ownership manifest "${normalized.path}": ${error.message}`]
    };
  }
}

function hasGeneratedMarker(content) {
  return GENERATED_MARKERS.some((marker) => String(content || '').includes(marker));
}

function detectOwnership(relativePath, currentContent, currentSha256, context) {
  const manifestEntry = context.ownershipManifest.files[relativePath] || null;
  const markerPresent = hasGeneratedMarker(currentContent);
  if (manifestEntry) {
    const safeToUpdate = manifestEntry.sha256 === currentSha256;
    return {
      state: safeToUpdate ? 'owned-current' : 'owned-drift',
      owned: true,
      safeToUpdate,
      source: 'manifest',
      markerPresent,
      manifestEntry
    };
  }

  if (markerPresent && context.trustGeneratedMarkers) {
    return {
      state: 'marker-owned',
      owned: true,
      safeToUpdate: true,
      source: 'generated-marker',
      markerPresent,
      manifestEntry: null
    };
  }

  return {
    state: markerPresent ? 'generated-marker-untracked' : 'unowned',
    owned: false,
    safeToUpdate: false,
    source: markerPresent ? 'generated-marker' : 'none',
    markerPresent,
    manifestEntry: null
  };
}

function createBuildSha256(operation, context) {
  return sha256(JSON.stringify({
    generator: context.generator,
    owner: operation.owner,
    path: operation.path,
    kind: operation.kind,
    templateId: operation.templateId,
    templatePath: operation.templatePath,
    sourceSha256: operation.sourceSha256,
    sha256: operation.sha256
  }));
}

function createOwnershipRecord(operation, context) {
  return {
    schema: SCAFFOLD_GENERATED_OWNERSHIP_SCHEMA,
    owner: operation.owner,
    generator: context.generator || operation.owner,
    kind: operation.kind,
    path: operation.path,
    sha256: operation.sha256,
    bytes: operation.bytes,
    templateId: operation.templateId,
    templatePath: operation.templatePath,
    sourceSha256: operation.sourceSha256,
    buildSha256: operation.buildSha256 || createBuildSha256(operation, context)
  };
}

function createWriteOperation(entry, index, context) {
  const targetPath = entry.path || entry.targetPath;
  const normalized = normalizeRelativePath(targetPath);
  const id = entry.id || `file-${index + 1}`;
  const content = String(entry.content || '');
  const base = {
    id,
    kind: entry.kind || entry.type || 'file',
    path: normalized.ok ? normalized.path : String(targetPath || ''),
    requestedPath: targetPath || null,
    content,
    sha256: sha256(content),
    bytes: byteLength(content),
    generated: entry.generated !== false,
    owner: entry.owner || context.owner,
    templateId: entry.templateId || null,
    templatePath: entry.templatePath || null,
    sourceSha256: entry.sourceSha256 || entry.sourceHash || null,
    buildSha256: entry.buildSha256 || null,
    requestedAction: entry.action || null,
    allowUnownedPatch: entry.allowUnownedPatch === true,
    patch: entry.patch || null,
    metadata: entry.metadata || null,
    exists: false,
    changed: false,
    action: 'conflict',
    status: 'invalid',
    allowed: false,
    ownership: {
      state: 'not-evaluated',
      owned: false,
      safeToUpdate: false,
      source: 'none',
      markerPresent: false
    },
    recordOwnership: false,
    diagnostics: []
  };

  if (!normalized.ok) {
    return {
      ...base,
      diagnostics: [{
        code: 'invalid-path',
        severity: 'error',
        message: normalized.error,
        path: base.path
      }]
    };
  }

  const absolutePath = path.resolve(context.rootDir, normalized.path);
  const diagnostics = [];
  const allowed = isAllowedPath(normalized.path, context.allowedRoots);
  if (!allowed) {
    diagnostics.push({
      code: 'path-not-allowed',
      severity: 'error',
      message: `WritePlan path "${normalized.path}" is outside the allowed Scaffold output roots.`,
      path: normalized.path,
      details: {
        allowedRoots: context.allowedRoots
      }
    });
  }

  if (!isInsideRoot(context.rootDir, absolutePath)) {
    diagnostics.push({
      code: 'path-outside-root',
      severity: 'error',
      message: `WritePlan path "${normalized.path}" resolves outside the repository root.`,
      path: normalized.path
    });
  }

  if (diagnostics.length > 0) {
    return {
      ...base,
      path: normalized.path,
      absolutePath,
      allowed,
      diagnostics
    };
  }

  if (fs.existsSync(absolutePath)) {
    const stat = fs.statSync(absolutePath);
    if (!stat.isFile()) {
      return {
        ...base,
        path: normalized.path,
        absolutePath,
        allowed,
        exists: true,
        diagnostics: [{
          code: 'target-not-file',
          severity: 'error',
          message: `WritePlan target "${normalized.path}" exists but is not a file.`,
          path: normalized.path
        }]
      };
    }

    const currentContent = fs.readFileSync(absolutePath, 'utf8');
    const unchanged = currentContent === content;
    const currentSha256 = sha256(currentContent);
    const ownership = detectOwnership(normalized.path, currentContent, currentSha256, context);
    const allowStructuredPatch = base.allowUnownedPatch === true;
    if (!unchanged && !ownership.safeToUpdate && !context.force && !allowStructuredPatch) {
      const code = ownership.state === 'owned-drift' ? 'owned-file-drift' : 'unowned-existing-target';
      const reason = ownership.state === 'owned-drift'
        ? `Generated file "${normalized.path}" changed since the last Scaffold ownership record.`
        : `Existing file "${normalized.path}" is not owned by Scaffold.`;
      return {
        ...base,
        path: normalized.path,
        absolutePath,
        allowed,
        exists: true,
        changed: true,
        action: 'conflict',
        status: 'conflict',
        currentSha256,
        ownership,
        diagnostics: [{
          code,
          severity: 'error',
          message: `${reason} Use --force only when replacing it is intentional.`,
          path: normalized.path
        }]
      };
    }

    const forceUpdate = !unchanged && context.force && !ownership.safeToUpdate;
    const structuredPatch = !unchanged && allowStructuredPatch && !forceUpdate && !ownership.safeToUpdate;
    return {
      ...base,
      path: normalized.path,
      absolutePath,
      allowed,
      exists: true,
      changed: !unchanged,
      action: unchanged ? 'skip' : (forceUpdate ? 'force-update' : (structuredPatch ? 'patch' : 'update')),
      status: unchanged ? 'unchanged' : (forceUpdate ? 'forced' : (structuredPatch ? 'patched' : 'changed')),
      currentSha256,
      ownership,
      recordOwnership: base.generated && (ownership.safeToUpdate || !unchanged || context.adoptUnowned),
      diagnostics: forceUpdate ? [{
        code: 'force-update',
        severity: 'warn',
        message: `WritePlan will replace "${normalized.path}" because --force is set.`,
        path: normalized.path
      }] : (structuredPatch ? [{
        code: 'structured-patch-existing-target',
        severity: 'warn',
        message: `WritePlan will patch structured target "${normalized.path}" through a deterministic Scaffold patcher.`,
        path: normalized.path
      }] : [])
    };
  }

  return {
    ...base,
    path: normalized.path,
    absolutePath,
    allowed,
    exists: false,
    changed: true,
    action: 'create',
    status: 'missing',
    currentSha256: null,
    ownership: {
      state: 'new',
      owned: true,
      safeToUpdate: true,
      source: 'create',
      markerPresent: false
    },
    recordOwnership: base.generated,
    diagnostics: []
  };
}

function flattenOperationErrors(operations) {
  return operations.flatMap((operation) => operation.diagnostics
    .filter((diagnostic) => diagnostic.severity !== 'warn')
    .map((diagnostic) => diagnostic.message));
}

function summarizeOperation(operation) {
  const {
    content,
    absolutePath,
    ...summary
  } = operation;
  return summary;
}

function summarizeWritePlan(plan) {
  return {
    ...plan,
    operations: plan.operations.map(summarizeOperation)
  };
}

function createWritePlan(entries = [], options = {}) {
  const rootDir = path.resolve(options.rootDir || process.cwd());
  const allowedRoots = normalizeAllowedRoots(options.allowedRoots);
  const mode = toBoolean(options.write) ? 'write' : (toBoolean(options.check) ? 'check' : 'dry-run');
  const ownership = readOwnershipManifest(rootDir, options.ownershipPath || DEFAULT_OWNERSHIP_PATH);
  const context = {
    rootDir,
    allowedRoots,
    owner: options.owner || options.generator || 'xtend-scaffold',
    generator: options.generator || null,
    force: toBoolean(options.force),
    adoptUnowned: toBoolean(options.adoptUnowned),
    trustGeneratedMarkers: toBoolean(options.trustGeneratedMarkers),
    ownershipManifest: ownership.manifest
  };
  const operations = entries.map((entry, index) => createWriteOperation(entry, index, context));
  const errors = ownership.errors.concat(flattenOperationErrors(operations));

  return {
    schema: SCAFFOLD_WRITE_PLAN_SCHEMA,
    ok: errors.length === 0,
    mode,
    generator: options.generator || null,
    owner: context.owner,
    force: context.force,
    rootDir,
    allowedRoots,
    ownershipSchema: SCAFFOLD_GENERATED_OWNERSHIP_SCHEMA,
    ownershipPath: ownership.path,
    operationCount: operations.length,
    changedCount: operations.filter((operation) => operation.changed).length,
    errors,
    operations
  };
}

function writeOperation(operation) {
  fs.mkdirSync(path.dirname(operation.absolutePath), { recursive: true });
  fs.writeFileSync(operation.absolutePath, operation.content, 'utf8');
  return {
    id: operation.id,
    path: operation.path,
    action: operation.action,
    changed: operation.action !== 'skip',
    sha256: operation.sha256
  };
}

function createNextOwnershipManifest(plan) {
  const current = readOwnershipManifest(plan.rootDir, plan.ownershipPath || DEFAULT_OWNERSHIP_PATH).manifest;
  const files = {
    ...(current.files || {})
  };
  const context = {
    generator: plan.generator || plan.owner
  };

  plan.operations
    .filter((operation) => operation.recordOwnership && operation.action !== 'conflict')
    .forEach((operation) => {
      files[operation.path] = createOwnershipRecord(operation, context);
    });

  return {
    schema: SCAFFOLD_GENERATED_OWNERSHIP_SCHEMA,
    files: sortObjectByKey(files)
  };
}

function writeOwnershipManifest(plan) {
  const recordable = plan.operations.some((operation) => operation.recordOwnership && operation.action !== 'conflict');
  if (!recordable) {
    return null;
  }

  const ownershipPath = plan.ownershipPath || DEFAULT_OWNERSHIP_PATH;
  const absolutePath = path.resolve(plan.rootDir, ownershipPath);
  const nextManifest = createNextOwnershipManifest(plan);
  const content = stableJson(nextManifest);
  const changed = !fs.existsSync(absolutePath) || fs.readFileSync(absolutePath, 'utf8') !== content;
  if (changed) {
    fs.mkdirSync(path.dirname(absolutePath), { recursive: true });
    fs.writeFileSync(absolutePath, content, 'utf8');
  }

  return {
    path: ownershipPath,
    changed,
    sha256: sha256(content),
    schema: SCAFFOLD_GENERATED_OWNERSHIP_SCHEMA
  };
}

function applyWritePlan(plan, options = {}) {
  const write = toBoolean(options.write) || plan.mode === 'write';
  const check = toBoolean(options.check) || plan.mode === 'check';
  const mode = write ? 'write' : (check ? 'check' : 'dry-run');

  if (!plan.ok) {
    return {
      schema: SCAFFOLD_WRITE_REPORT_SCHEMA,
      ok: false,
      status: 'blocked',
      mode,
      errors: plan.errors,
      plan: summarizeWritePlan(plan),
      writes: [],
      ownershipManifest: null
    };
  }

  if (check) {
    const changed = plan.operations.filter((operation) => operation.changed);
    return {
      schema: SCAFFOLD_WRITE_REPORT_SCHEMA,
      ok: changed.length === 0,
      status: changed.length === 0 ? 'current' : 'outdated',
      mode,
      errors: changed.length === 0 ? [] : changed.map((operation) => `WritePlan target "${operation.path}" is not current.`),
      plan: summarizeWritePlan(plan),
      writes: [],
      ownershipManifest: null
    };
  }

  if (!write) {
    return {
      schema: SCAFFOLD_WRITE_REPORT_SCHEMA,
      ok: true,
      status: 'planned',
      mode,
      errors: [],
      plan: summarizeWritePlan(plan),
      writes: [],
      ownershipManifest: null
    };
  }

  const writes = [];
  const errors = [];
  plan.operations.forEach((operation) => {
    if (operation.action === 'skip') {
      writes.push({
        id: operation.id,
        path: operation.path,
        action: operation.action,
        changed: false,
        sha256: operation.sha256
      });
      return;
    }

    try {
      writes.push(writeOperation(operation));
    } catch (error) {
      errors.push(`Failed to write "${operation.path}": ${error.message}`);
    }
  });
  let ownershipManifest = null;
  if (errors.length === 0) {
    try {
      ownershipManifest = writeOwnershipManifest(plan);
    } catch (error) {
      errors.push(`Failed to write Scaffold ownership manifest "${plan.ownershipPath}": ${error.message}`);
    }
  }

  return {
    schema: SCAFFOLD_WRITE_REPORT_SCHEMA,
    ok: errors.length === 0,
    status: errors.length === 0 ? 'written' : 'failed',
    mode,
    errors,
    plan: summarizeWritePlan(plan),
    writes,
    ownershipManifest
  };
}

function writeScaffoldFiles(entries = [], options = {}) {
  const plan = createWritePlan(entries, options);
  return applyWritePlan(plan, options);
}

module.exports = {
  DEFAULT_ALLOWED_ROOTS,
  DEFAULT_OWNERSHIP_PATH,
  SCAFFOLD_GENERATED_OWNERSHIP_SCHEMA,
  SCAFFOLD_WRITE_PLAN_SCHEMA,
  SCAFFOLD_WRITE_REPORT_SCHEMA,
  applyWritePlan,
  createWritePlan,
  normalizeRelativePath,
  sha256,
  summarizeWritePlan,
  writeScaffoldFiles
};
