import type { XtendBuilderComponentInput, XtendBuilderOptions, XtendBuilderRecord, XtendBuilderReport } from '../builder-public-types';

export declare const COMPONENT_CONTRACT_V2_SCHEMA: string;
export declare const COMPONENT_NETWORK_ASSERTIONS: string[];
export declare const COMPONENT_NETWORK_CONTEXTS: string[];
export declare const COMPONENT_NETWORK_CONTRACT_DOC: string;
export declare const COMPONENT_NETWORK_CONTRACT_SCHEMA: string;
export declare const COMPONENT_NETWORK_PROFILES: string[];
export declare const COMPONENT_NETWORK_REPORT_SCHEMA: string;
export declare const COMPONENT_NETWORK_REQUIRED_COMMANDS: string[];
export declare const COMPONENT_NETWORK_REQUIRED_DOMAINS: string[];
export declare const COMPONENT_NETWORK_REQUIRED_EVENTS: string[];
export declare const COMPONENT_NETWORK_WORKPACKAGE: string;
export declare const COMPONENT_SHELL_CONTRACT_SCHEMA: string;
export declare const COMPONENT_STYLING_CONTRACT_SCHEMA: string;
export declare const COMPONENT_UX_PERFORMANCE_CONTRACT_SCHEMA: string;
export declare const FABRIC_BOUNDARY_SCHEMA: string;
export declare const KERNEL_BOUNDARY: string;
export declare const RMT_NETWORK_AUTHORING_SCHEMA: string;
export declare const RUNTIME_A11Y_CONTRACT_SCHEMA: string;
export declare function createComponentNetworkContract(input?: XtendBuilderComponentInput, options?: XtendBuilderOptions): XtendBuilderRecord;
export declare function validateComponentNetworkContract(contract: unknown): XtendBuilderReport<XtendBuilderRecord>;
