'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),zlib=require('node:zlib');
const api=require('../../tools/schema-inventory/index.cjs'),{assembleExpectedView}=require('../../tools/schema-inventory/expected-view.cjs');
let provider,inputs,directory;const events=[];
function required(name,body){test(name,()=>{try{body();events.push({name,ok:true});}catch(error){events.push({name,ok:false,error:error.message});throw error;}});}
test.before(()=>{assert.ok(process.env.XTEND_UNION_ARCHIVE&&process.env.XTEND_UNION_EXPECTED,'Actual committed source artifact required; no skip');directory=fs.mkdtempSync(path.join(os.tmpdir(),'expected101-'));provider=api.createSourceProvider({archive:process.env.XTEND_UNION_ARCHIVE,destination:path.join(directory,'source'),expected:JSON.parse(fs.readFileSync(process.env.XTEND_UNION_EXPECTED))});const bindings=provider.provenance().bindings,read=(owner,p)=>provider.readCurrent(bindings.find(r=>r.owner===owner&&r.sourcePath===p).logicalPath),json=(owner,p)=>JSON.parse(read(owner,p));inputs={core:json('core','tests/schemas/xtend-schema-inventory.json'),demo:json('demo','tests/schemas/ownership-101.json'),ledger:JSON.parse(zlib.gunzipSync(read('core','tools/schema-inventory/ownership-ledger.json.gz'))),selection:json('core','tools/schema-inventory/selection.json'),authorityBindings:json('core','tools/schema-inventory/authority-bindings.json'),overlay:json('core','tools/schema-inventory/command-lexical-overlay.json'),resolvePath(owner,p,digest){const r=bindings.find(r=>r.owner===owner&&r.sourcePath===p);assert.ok(r,'Required expected source');if(digest)assert.equal(r.sha256,digest);provider.readCurrent(r.logicalPath);return r.logicalPath;}};});
test.after(()=>{if(process.env.XTEND_EXPECTED_VIEW_TEST_REPORT)fs.writeFileSync(process.env.XTEND_EXPECTED_VIEW_TEST_REPORT,JSON.stringify({events,artifact:provider?.provenance()},null,2)+'\n');if(directory)fs.rmSync(directory,{recursive:true,force:true});});
function mutate(action,expectedError){const value={...structuredClone({...inputs,resolvePath:undefined}),resolvePath:inputs.resolvePath};action(value);assert.throws(()=>assembleExpectedView(value),expectedError);}
required('actual Git-bound productive expected view conserves history and all unselected records',()=>{const expected=api.createExpectedInventory(provider);assert.deepEqual(expected,api.createExpectedInventory(provider));for(const old of inputs.core.entries)if(!inputs.selection.includes(old.schemaId))assert.deepEqual(expected.entries.find(e=>e.schemaId===old.schemaId),old);for(const key of Object.keys(inputs.core).filter(k=>k!=='entries'))assert.deepEqual(expected[key],inputs.core[key]);for(const id of inputs.selection){const entry=expected.entries.find(e=>e.schemaId===id),old=inputs.ledger.entries.find(e=>e.schemaId===id);assert.deepEqual(entry.shapePolicy.authoritativeFingerprints,old.shapePolicy.authoritativeFingerprints);assert.equal(entry.releasedFingerprintSetHash,old.releasedFingerprintSetHash);}assert.deepEqual(inputs.core,JSON.parse(provider.readCurrent('tests/schemas/xtend-schema-inventory.json')));});
required('conflicting canonical owner record rejects',()=>mutate(x=>x.demo.entries[0].canonicalDefinition.role='documentation'));
required('tampered original ledger rejects',()=>mutate(x=>x.ledger.entries[0].description+=' tamper'));
required('missing approved owner record rejects',()=>mutate(x=>x.demo.entries.pop()));
required('new accepted hash rejects',()=>mutate(x=>x.demo.entries[0].shapePolicy.acceptedFingerprints.push('sha256:'+'0'.repeat(64))));
required('new authority rejects',()=>mutate(x=>x.demo.entries[0].shapePolicy.authoritativeFingerprints.push('sha256:'+'1'.repeat(64))));
required('unselected Core mutation rejects',()=>mutate(x=>{x.core.entries.find(e=>!x.selection.includes(e.schemaId)).description+=' mutation';}));
required('missing current owner source rejects',()=>{assert.throws(()=>assembleExpectedView({...inputs,resolvePath(){throw Error('Missing current owner source');}}));});
required('unverified provider clone rejects',()=>assert.throws(()=>api.createExpectedInventory({...provider})));
required('tampered materialized expected owner bytes reject before view construction',()=>{const row=provider.files().find(r=>r.owner==='demo'&&r.path==='tests/schemas/ownership-101.json'),original=fs.readFileSync(row.absolutePath);try{fs.writeFileSync(row.absolutePath,Buffer.from('{}'));assert.throws(()=>api.createExpectedInventory(provider));}finally{fs.writeFileSync(row.absolutePath,original);}});

required('overlay third hash rejects independently of owner record digests',()=>mutate(x=>x.overlay.variants.push({...x.overlay.variants[0],hash:'sha256:'+'2'.repeat(64)}),/Reviewed expected overlay input changed/));
required('substituted overlay ID rejects independently of owner record digests',()=>mutate(x=>x.overlay.schemaId=x.selection[0],/Reviewed expected overlay input changed/));
required('authority binding mutation rejects independently of owner record digests',()=>mutate(x=>x.authorityBindings[0].sourceSha256='3'.repeat(64),/Reviewed expected authority bindings changed/));
