const {
  printComponentContractReport,
  runComponentContractSuite
} = require('./component_contract_helpers');

const priorityComponentConfigs = {
  'x-router': {
    tag: 'x-router',
    fileName: 'xrouter.js',
    docTitle: 'xrouter - XTend Komponente',
    label: 'x-router component contract',
    sourcePath: 'components/xrouter.js',
    fixturePath: 'tests/components/fixtures/xrouter.component.html',
    docPath: 'docs/components/xrouter.md',
    profiles: ['routing'],
    observedAttributes: ['mode', 'routesrc', 'reuse-component'],
    sourceContracts: [
      { pattern: 'normalizeRmtRouteRecord', message: 'x-router normalizes RMT route records' },
      { pattern: 'createRouteElementFromRecord', message: 'x-router creates route elements from RMT records' },
      { pattern: 'registerRoutes(routes = [], options = {})', message: 'x-router exposes registerRoutes API' },
      { pattern: 'router-navigate', message: 'x-router consumes xstate navigation signal' },
      { pattern: 'router-navigated', message: 'x-router publishes navigated state' },
      { pattern: 'route-changed', message: 'x-router emits route-changed' },
      { pattern: 'routechange', message: 'x-router keeps legacy routechange event' },
      { pattern: 'xrouter-routes-registered', message: 'x-router emits route registration event' },
      { pattern: 'xrouter-route-reused', message: 'x-router emits route reuse event' },
      { pattern: 'updateRoute', message: 'x-router supports insular route component updates' },
      { pattern: 'data-rmt-schedule', message: 'x-router preserves RMT schedule references' },
      { pattern: 'xtend.router.scrollBoundary', message: 'x-router publishes scroll boundary diagnostics' },
      { pattern: 'xrouter-scroll-boundary-normalized', message: 'x-router emits scroll boundary normalization event' },
      { pattern: 'xtend.router.closedNavigationOverlays', message: 'x-router publishes closed navigation overlay diagnostics' },
      { pattern: 'xrouter-navigation-overlays-closed', message: 'x-router emits navigation overlay cleanup event' },
      { pattern: 'xtend.router.documentMeta', message: 'x-router publishes document title/meta state' },
      { pattern: 'xrouter-title-updated', message: 'x-router emits document title update events' },
      { pattern: 'classifyXRouterImportUrl', message: 'x-router validates route import URLs before dynamic import' },
      { pattern: 'xtend.security.xrouter.import.refused.external_module', message: 'x-router refuses external route modules' },
      { pattern: 'xrouter-route-import-refused', message: 'x-router emits route import policy refusals' },
      { pattern: 'route.document.title.rewrite', message: 'x-router exposes title rewrite schedule ref' },
      { pattern: 'renderRouteToString', message: 'x-router keeps SSR route rendering helper' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-router"', message: 'x-router fixture uses a stable id' },
      { pattern: 'mode="hash"', message: 'x-router fixture covers hash mode' },
      { pattern: 'path="/"', message: 'x-router fixture declares a route' },
      { pattern: 'data-rmt-schedule="demo.route"', message: 'x-router fixture covers RMT schedule metadata' },
      { pattern: 'window.xstate', message: 'x-router fixture stubs xstate locally' },
      { pattern: '__xtendComponentResult', message: 'x-router fixture exposes a component result object' }
    ],
    docContracts: [
      { pattern: 'router-navigate', message: 'x-router docs describe xstate navigation' },
      { pattern: '`route-changed`', message: 'x-router docs describe route-changed event' },
      { pattern: 'registerRoutes(routes, options)', message: 'x-router docs describe route registration API' },
      { pattern: 'Document Title Rewrite', message: 'x-router docs describe document title rewriting' },
      { pattern: 'data-rmt-schedule', message: 'x-router docs describe RMT schedule forwarding' },
      { pattern: 'reuse-component', message: 'x-router docs describe insular route component reuse' },
      { pattern: 'Scroll Boundary', message: 'x-router docs describe scroll boundary handling' },
      { pattern: 'xtend.router.closedNavigationOverlays', message: 'x-router docs describe overlay cleanup diagnostics' }
    ]
  },
  'x-link': {
    tag: 'x-link',
    fileName: 'xlink.js',
    docTitle: 'xlink - XTend Komponente',
    label: 'x-link component contract',
    sourcePath: 'components/xlink.js',
    fixturePath: 'tests/components/fixtures/xlink.component.html',
    docPath: 'docs/components/xlink.md',
    profiles: ['routing', 'interactive'],
    observedAttributes: ['href'],
    sourceContracts: [
      { pattern: 'before-navigate', message: 'x-link emits cancelable before-navigate' },
      { pattern: 'after-navigate', message: 'x-link emits after-navigate' },
      { pattern: 'x-navigate', message: 'x-link dispatches router navigation signal' },
      { pattern: 'xrouter-after-navigate', message: 'x-link listens for router navigation completion' },
      { pattern: 'aria-current', message: 'x-link mirrors active route to aria-current' },
      { pattern: 'noopener noreferrer', message: 'x-link protects external links' },
      { pattern: 'document.querySelector(\'x-router\')', message: 'x-link derives navigation mode from x-router' },
      { pattern: 'e.key === \'Enter\' || e.key === \' \'', message: 'x-link supports keyboard activation' },
      { pattern: 'overflow-wrap: anywhere', message: 'x-link wraps long labels inside constrained containers' },
      { pattern: '::slotted(*)', message: 'x-link keeps slotted icon/text content overflow-safe' },
      { pattern: 'inline-overflow-wraps-in-constrained-containers', message: 'x-link declares its overflow policy in the UX profile' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-link"', message: 'x-link fixture uses a stable id' },
      { pattern: 'href="/dashboard"', message: 'x-link fixture covers internal href' },
      { pattern: 'href="https://example.com"', message: 'x-link fixture covers external href' },
      { pattern: '<x-router', message: 'x-link fixture contains a router host' },
      { pattern: '__xtendComponentResult', message: 'x-link fixture exposes a component result object' }
    ],
    docContracts: [
      { pattern: '`before-navigate`', message: 'x-link docs describe before-navigate' },
      { pattern: '`after-navigate`', message: 'x-link docs describe after-navigate' },
      { pattern: '`x-navigate`', message: 'x-link docs describe router event sync' },
      { pattern: 'Overflow-Sicherheit', message: 'x-link docs describe overflow-safe navigation labels' }
    ]
  },
  'x-input': {
    tag: 'x-input',
    fileName: 'xinput.js',
    docTitle: 'xinput – XTend Komponente',
    label: 'x-input component contract',
    sourcePath: 'components/xinput.js',
    fixturePath: 'tests/components/fixtures/xinput.component.html',
    docPath: 'docs/components/xinput.md',
    profiles: ['form'],
    observedAttributes: ['type', 'name', 'value', 'placeholder', 'required', 'disabled'],
    sourceContracts: [
      { pattern: 'static formAssociated = true', message: 'x-input is form-associated' },
      { pattern: 'attachInternals', message: 'x-input uses ElementInternals where available' },
      { pattern: 'xinput-value-', message: 'x-input syncs xstate value key' },
      { pattern: 'input-changed', message: 'x-input emits input-changed' },
      { pattern: 'validation-failed', message: 'x-input emits validation-failed' },
      { pattern: 'role="alert"', message: 'x-input exposes validation alert role' },
      { pattern: 'aria-live="assertive"', message: 'x-input exposes assertive validation region' },
      { pattern: 'reportValidity', message: 'x-input exposes validity reporting' },
      { pattern: 'reset()', message: 'x-input exposes reset API' },
      { pattern: '--input-bg-dark', message: 'x-input exposes dark theme background token' },
      { pattern: ':host-context(html[data-theme="dark"]) input', message: 'x-input adapts background in dark theme' },
      { pattern: 'var(--xtend-surface', message: 'x-input falls back to XTend surface token' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-input"', message: 'x-input fixture uses a stable id' },
      { pattern: 'name="email"', message: 'x-input fixture covers name attribute' },
      { pattern: 'type="email"', message: 'x-input fixture covers type attribute' },
      { pattern: 'required', message: 'x-input fixture covers required attribute' },
      { pattern: 'slot="label"', message: 'x-input fixture covers label slot' },
      { pattern: 'slot="error"', message: 'x-input fixture covers error slot' },
      { pattern: 'window.xstate', message: 'x-input fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`input-changed`', message: 'x-input docs describe input-changed event' },
      { pattern: '`validation-failed`', message: 'x-input docs describe validation-failed event' },
      { pattern: '`xinput-value-<id>`', message: 'x-input docs describe state key' },
      { pattern: 'reportValidity()', message: 'x-input docs describe validity API' },
      { pattern: '--input-bg-dark', message: 'x-input docs describe dark background token' }
    ]
  },
  'x-select': {
    tag: 'x-select',
    fileName: 'xselect.js',
    docTitle: 'xselect – XTend Komponente',
    label: 'x-select component contract',
    sourcePath: 'components/xselect.js',
    fixturePath: 'tests/components/fixtures/xselect.component.html',
    docPath: 'docs/components/xselect.md',
    profiles: ['form', 'interactive', 'stateful'],
    observedAttributes: ['name', 'value', 'disabled', 'required', 'multiple', 'placeholder', 'label'],
    sourceContracts: [
      { pattern: 'static formAssociated = true', message: 'x-select is form-associated' },
      { pattern: 'attachInternals', message: 'x-select uses ElementInternals where available' },
      { pattern: 'xtendComponentContract', message: 'x-select exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-select exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-select exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-select exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-select keeps RMT kernel boundary visible' },
      { pattern: 'xselect-value-', message: 'x-select syncs xstate value key' },
      { pattern: 'select-changed', message: 'x-select emits select-changed' },
      { pattern: 'select-invalid', message: 'x-select emits select-invalid' },
      { pattern: 'role="combobox"', message: 'x-select exposes combobox role' },
      { pattern: 'aria-describedby', message: 'x-select wires descriptive regions' },
      { pattern: 'MutationObserver', message: 'x-select tracks slotted option changes' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-select"', message: 'x-select fixture uses a stable id' },
      { pattern: 'name="plan"', message: 'x-select fixture covers name attribute' },
      { pattern: 'value="pro"', message: 'x-select fixture covers value attribute' },
      { pattern: 'required', message: 'x-select fixture covers required attribute' },
      { pattern: 'placeholder="Choose a plan"', message: 'x-select fixture covers placeholder attribute' },
      { pattern: '<option value="starter">', message: 'x-select fixture covers option projection' },
      { pattern: 'slot="label"', message: 'x-select fixture covers label slot' },
      { pattern: 'slot="hint"', message: 'x-select fixture covers hint slot' },
      { pattern: 'slot="error"', message: 'x-select fixture covers error slot' },
      { pattern: 'window.xstate', message: 'x-select fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`select-changed`', message: 'x-select docs describe select-changed event' },
      { pattern: '`select-invalid`', message: 'x-select docs describe select-invalid event' },
      { pattern: '`xselect-value-<id>`', message: 'x-select docs describe state key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-select docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-select docs describe performance profile' },
      { pattern: 'validate()', message: 'x-select docs describe validate API' }
    ]
  },
  'x-checkbox': {
    tag: 'x-checkbox',
    fileName: 'xcheckbox.js',
    docTitle: 'xcheckbox – XTend Komponente',
    label: 'x-checkbox component contract',
    sourcePath: 'components/xcheckbox.js',
    fixturePath: 'tests/components/fixtures/xcheckbox.component.html',
    docPath: 'docs/components/xcheckbox.md',
    profiles: ['form', 'interactive'],
    observedAttributes: ['name', 'value', 'checked', 'disabled', 'required', 'indeterminate', 'label'],
    sourceContracts: [
      { pattern: 'static formAssociated = true', message: 'x-checkbox is form-associated' },
      { pattern: 'attachInternals', message: 'x-checkbox uses ElementInternals where available' },
      { pattern: 'xtendComponentContract', message: 'x-checkbox exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-checkbox exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-checkbox exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-checkbox exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-checkbox keeps RMT kernel boundary visible' },
      { pattern: 'xcheckbox-checked-', message: 'x-checkbox syncs xstate checked key' },
      { pattern: 'checkbox-changed', message: 'x-checkbox emits checkbox-changed' },
      { pattern: 'checkbox-invalid', message: 'x-checkbox emits checkbox-invalid' },
      { pattern: 'aria-checked', message: 'x-checkbox mirrors checked state to ARIA' },
      { pattern: 'indeterminate', message: 'x-checkbox supports indeterminate state' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-checkbox"', message: 'x-checkbox fixture uses a stable id' },
      { pattern: 'name="terms"', message: 'x-checkbox fixture covers name attribute' },
      { pattern: 'value="accepted"', message: 'x-checkbox fixture covers value attribute' },
      { pattern: 'checked', message: 'x-checkbox fixture covers checked state' },
      { pattern: 'required', message: 'x-checkbox fixture covers required attribute' },
      { pattern: 'slot="label"', message: 'x-checkbox fixture covers label slot' },
      { pattern: 'slot="hint"', message: 'x-checkbox fixture covers hint slot' },
      { pattern: 'slot="error"', message: 'x-checkbox fixture covers error slot' },
      { pattern: 'window.xstate', message: 'x-checkbox fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`checkbox-changed`', message: 'x-checkbox docs describe checkbox-changed event' },
      { pattern: '`checkbox-invalid`', message: 'x-checkbox docs describe checkbox-invalid event' },
      { pattern: '`xcheckbox-checked-<id>`', message: 'x-checkbox docs describe state key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-checkbox docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-checkbox docs describe performance profile' },
      { pattern: 'toggle()', message: 'x-checkbox docs describe toggle API' }
    ]
  },
  'x-toggle': {
    tag: 'x-toggle',
    fileName: 'xtoggle.js',
    docTitle: 'xtoggle - XTend component',
    label: 'x-toggle component contract',
    sourcePath: 'components/xtoggle.js',
    fixturePath: 'tests/components/fixtures/xtoggle.component.html',
    docPath: 'docs/components/xtoggle.md',
    profiles: ['form', 'interactive', 'stateful'],
    observedAttributes: ['name', 'value', 'checked', 'disabled', 'required', 'label', 'busy', 'invalid', 'density'],
    sourceContracts: [
      { pattern: 'static formAssociated = true', message: 'x-toggle is form-associated' },
      { pattern: 'attachInternals', message: 'x-toggle uses ElementInternals where available' },
      { pattern: 'xtendComponentContract', message: 'x-toggle exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-toggle exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-toggle exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-toggle exposes Performance profile' },
      { pattern: 'xtendFormControlUxProfile', message: 'x-toggle exposes Form Control UX profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-toggle keeps RMT kernel boundary visible' },
      { pattern: 'xtoggle-checked-', message: 'x-toggle syncs xstate checked key' },
      { pattern: 'toggle-changed', message: 'x-toggle emits toggle-changed' },
      { pattern: 'toggle-invalid', message: 'x-toggle emits toggle-invalid' },
      { pattern: 'role="switch"', message: 'x-toggle uses switch semantics' },
      { pattern: 'aria-checked', message: 'x-toggle mirrors checked state to ARIA' },
      { pattern: 'white-space: nowrap', message: 'x-toggle prevents visible I/O state-symbol wrapping' },
      { pattern: '<slot name="on-label">I</slot>', message: 'x-toggle defaults the checked-visible symbol to I' },
      { pattern: '<slot name="off-label">O</slot>', message: 'x-toggle defaults the unchecked-visible symbol to O' },
      { pattern: 'state-label-on', message: 'x-toggle positions the I symbol on checked-visible side' },
      { pattern: 'state-label-off', message: 'x-toggle positions the O symbol on unchecked-visible side' },
      { pattern: 'Apple Human Interface Guidelines Toggles', message: 'x-toggle records HIG-inspired design reference' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-toggle"', message: 'x-toggle fixture uses a stable id' },
      { pattern: 'name="notifications"', message: 'x-toggle fixture covers name attribute' },
      { pattern: 'value="enabled"', message: 'x-toggle fixture covers value attribute' },
      { pattern: 'checked', message: 'x-toggle fixture covers checked state' },
      { pattern: 'required', message: 'x-toggle fixture covers required attribute' },
      { pattern: 'slot="hint"', message: 'x-toggle fixture covers hint slot' },
      { pattern: 'slot="error"', message: 'x-toggle fixture covers error slot' },
      { pattern: 'slot="on-label"', message: 'x-toggle fixture covers visible on label slot' },
      { pattern: 'slot="off-label"', message: 'x-toggle fixture covers visible off label slot' },
      { pattern: 'slot="on-label">I</span>', message: 'x-toggle fixture uses compact I checked symbol' },
      { pattern: 'slot="off-label">O</span>', message: 'x-toggle fixture uses compact O unchecked symbol' },
      { pattern: 'window.xstate', message: 'x-toggle fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`toggle-changed`', message: 'x-toggle docs describe toggle-changed event' },
      { pattern: '`toggle-invalid`', message: 'x-toggle docs describe toggle-invalid event' },
      { pattern: '`xtoggle-checked-<id>`', message: 'x-toggle docs describe state key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-toggle docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-toggle docs describe performance profile' },
      { pattern: 'xtend.component.form-control-ux-profile.v1', message: 'x-toggle docs describe Form Control UX profile' },
      { pattern: '`role="switch"`', message: 'x-toggle docs describe switch role' },
      { pattern: '`aria-checked`', message: 'x-toggle docs describe aria-checked' },
      { pattern: '`I` fuer ein und `O` fuer aus', message: 'x-toggle docs describe compact visible state symbols' },
      { pattern: 'toggle()', message: 'x-toggle docs describe toggle API' }
    ]
  },
  'x-radio': {
    tag: 'x-radio',
    fileName: 'xradio.js',
    docTitle: 'xradio – XTend Komponente',
    label: 'x-radio component contract',
    sourcePath: 'components/xradio.js',
    fixturePath: 'tests/components/fixtures/xradio.component.html',
    docPath: 'docs/components/xradio.md',
    profiles: ['form', 'interactive'],
    observedAttributes: ['name', 'value', 'checked', 'disabled', 'required', 'label'],
    sourceContracts: [
      { pattern: 'static formAssociated = true', message: 'x-radio is form-associated' },
      { pattern: 'attachInternals', message: 'x-radio uses ElementInternals where available' },
      { pattern: 'xtendComponentContract', message: 'x-radio exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-radio exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-radio exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-radio exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-radio keeps RMT kernel boundary visible' },
      { pattern: 'xradio-checked-', message: 'x-radio syncs xstate checked key' },
      { pattern: 'xradio-value-', message: 'x-radio syncs xstate group value key' },
      { pattern: 'radio-changed', message: 'x-radio emits radio-changed' },
      { pattern: 'radio-invalid', message: 'x-radio emits radio-invalid' },
      { pattern: 'role="radio"', message: 'x-radio exposes radio role' },
      { pattern: 'aria-checked', message: 'x-radio mirrors checked state to ARIA' },
      { pattern: 'ArrowRight', message: 'x-radio supports arrow-key group navigation' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-radio-starter"', message: 'x-radio fixture uses stable starter id' },
      { pattern: 'id="component-radio-pro"', message: 'x-radio fixture uses stable selected id' },
      { pattern: 'name="plan"', message: 'x-radio fixture covers shared name attribute' },
      { pattern: 'value="pro"', message: 'x-radio fixture covers value attribute' },
      { pattern: 'checked', message: 'x-radio fixture covers checked state' },
      { pattern: 'required', message: 'x-radio fixture covers required attribute' },
      { pattern: 'slot="label"', message: 'x-radio fixture covers label slot' },
      { pattern: 'slot="error"', message: 'x-radio fixture covers error slot' },
      { pattern: 'window.xstate', message: 'x-radio fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`radio-changed`', message: 'x-radio docs describe radio-changed event' },
      { pattern: '`radio-invalid`', message: 'x-radio docs describe radio-invalid event' },
      { pattern: '`xradio-checked-<id>`', message: 'x-radio docs describe checked state key' },
      { pattern: '`xradio-value-<name>`', message: 'x-radio docs describe group value key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-radio docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-radio docs describe performance profile' },
      { pattern: 'check()', message: 'x-radio docs describe check API' }
    ]
  },
  'x-textarea': {
    tag: 'x-textarea',
    fileName: 'xtextarea.js',
    docTitle: 'xtextarea - XTend Komponente',
    label: 'x-textarea component contract',
    sourcePath: 'components/xtextarea.js',
    fixturePath: 'tests/components/fixtures/xtextarea.component.html',
    docPath: 'docs/components/xtextarea.md',
    profiles: ['form', 'stateful'],
    observedAttributes: ['name', 'value', 'placeholder', 'required', 'disabled', 'readonly', 'maxlength', 'minlength', 'rows', 'label', 'submit-on-enter'],
    sourceContracts: [
      { pattern: 'static formAssociated = true', message: 'x-textarea is form-associated' },
      { pattern: 'attachInternals', message: 'x-textarea uses ElementInternals where available' },
      { pattern: 'xtendComponentContract', message: 'x-textarea exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-textarea exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-textarea exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-textarea exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-textarea keeps RMT kernel boundary visible' },
      { pattern: 'xtextarea-value-', message: 'x-textarea syncs xstate value key' },
      { pattern: 'textarea-changed', message: 'x-textarea emits textarea-changed' },
      { pattern: 'textarea-invalid', message: 'x-textarea emits textarea-invalid' },
      { pattern: 'textarea-submit', message: 'x-textarea emits textarea-submit' },
      { pattern: 'role="status"', message: 'x-textarea exposes character counter live region' },
      { pattern: 'role="alert"', message: 'x-textarea exposes validation alert region' },
      { pattern: 'aria-describedby', message: 'x-textarea wires descriptive regions' },
      { pattern: 'character-count-announcement', message: 'x-textarea declares character-count screenreader signal' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-textarea"', message: 'x-textarea fixture uses a stable id' },
      { pattern: 'name="notes"', message: 'x-textarea fixture covers name attribute' },
      { pattern: 'maxlength="240"', message: 'x-textarea fixture covers maxlength attribute' },
      { pattern: 'rows="5"', message: 'x-textarea fixture covers rows attribute' },
      { pattern: 'required', message: 'x-textarea fixture covers required attribute' },
      { pattern: 'slot="label"', message: 'x-textarea fixture covers label slot' },
      { pattern: 'slot="hint"', message: 'x-textarea fixture covers hint slot' },
      { pattern: 'slot="error"', message: 'x-textarea fixture covers error slot' },
      { pattern: 'window.xstate', message: 'x-textarea fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`textarea-changed`', message: 'x-textarea docs describe textarea-changed event' },
      { pattern: '`textarea-invalid`', message: 'x-textarea docs describe textarea-invalid event' },
      { pattern: '`textarea-submit`', message: 'x-textarea docs describe textarea-submit event' },
      { pattern: '`xtextarea-value-<id>`', message: 'x-textarea docs describe state key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-textarea docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-textarea docs describe performance profile' },
      { pattern: 'validate()', message: 'x-textarea docs describe validate API' }
    ]
  },
  'x-status': {
    tag: 'x-status',
    fileName: 'xstatus.js',
    docTitle: 'xstatus - XTend Komponente',
    label: 'x-status component contract',
    sourcePath: 'components/xstatus.js',
    fixturePath: 'tests/components/fixtures/xstatus.component.html',
    docPath: 'docs/components/xstatus.md',
    profiles: ['feedback', 'stateful'],
    observedAttributes: ['type', 'state', 'message', 'dismissible', 'busy', 'polite', 'label'],
    sourceContracts: [
      { pattern: 'xtendComponentContract', message: 'x-status exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-status exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-status exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-status exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-status keeps RMT kernel boundary visible' },
      { pattern: 'xstatus-state-', message: 'x-status syncs xstate state key' },
      { pattern: 'status-changed', message: 'x-status emits status-changed' },
      { pattern: 'status-dismissed', message: 'x-status emits status-dismissed' },
      { pattern: 'role="status"', message: 'x-status exposes status role' },
      { pattern: 'role=alert', message: 'x-status declares alert path for critical status' },
      { pattern: 'aria-live', message: 'x-status wires live region' },
      { pattern: 'aria-busy', message: 'x-status mirrors busy state' },
      { pattern: 'scheduler-feedback', message: 'x-status declares scheduler feedback signal' },
      { pattern: 'dismissible', message: 'x-status supports dismissible state' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-status"', message: 'x-status fixture uses a stable id' },
      { pattern: 'type="warning"', message: 'x-status fixture covers warning type' },
      { pattern: 'state="validating"', message: 'x-status fixture covers state attribute' },
      { pattern: 'message="Validation is running"', message: 'x-status fixture covers message attribute' },
      { pattern: 'dismissible', message: 'x-status fixture covers dismissible state' },
      { pattern: 'busy', message: 'x-status fixture covers busy state' },
      { pattern: 'slot="label"', message: 'x-status fixture covers label slot' },
      { pattern: 'window.xstate', message: 'x-status fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`status-changed`', message: 'x-status docs describe status-changed event' },
      { pattern: '`status-dismissed`', message: 'x-status docs describe status-dismissed event' },
      { pattern: '`xstatus-state-<id>`', message: 'x-status docs describe state key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-status docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-status docs describe performance profile' },
      { pattern: 'setStatus(nextState)', message: 'x-status docs describe setStatus API' },
      { pattern: 'dismiss()', message: 'x-status docs describe dismiss API' }
    ]
  },
  'x-progress': {
    tag: 'x-progress',
    fileName: 'xprogress.js',
    docTitle: 'xprogress - XTend Komponente',
    label: 'x-progress component contract',
    sourcePath: 'components/xprogress.js',
    fixturePath: 'tests/components/fixtures/xprogress.component.html',
    docPath: 'docs/components/xprogress.md',
    profiles: ['feedback', 'stateful'],
    observedAttributes: ['value', 'max', 'label', 'status', 'indeterminate', 'busy'],
    sourceContracts: [
      { pattern: 'xtendComponentContract', message: 'x-progress exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-progress exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-progress exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-progress exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-progress keeps RMT kernel boundary visible' },
      { pattern: 'xprogress-value-', message: 'x-progress syncs xstate value key' },
      { pattern: 'progress-changed', message: 'x-progress emits progress-changed' },
      { pattern: 'progress-complete', message: 'x-progress emits progress-complete' },
      { pattern: 'role="progressbar"', message: 'x-progress exposes progressbar role' },
      { pattern: 'aria-valuenow', message: 'x-progress mirrors current value' },
      { pattern: 'aria-valuemax', message: 'x-progress mirrors max value' },
      { pattern: 'indeterminate', message: 'x-progress supports indeterminate state' },
      { pattern: 'scheduler-feedback', message: 'x-progress declares scheduler feedback signal' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-progress"', message: 'x-progress fixture uses a stable id' },
      { pattern: 'value="64"', message: 'x-progress fixture covers value attribute' },
      { pattern: 'max="100"', message: 'x-progress fixture covers max attribute' },
      { pattern: 'status="Hydrating route"', message: 'x-progress fixture covers status attribute' },
      { pattern: 'busy', message: 'x-progress fixture covers busy state' },
      { pattern: 'slot="label"', message: 'x-progress fixture covers label slot' },
      { pattern: 'window.xstate', message: 'x-progress fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`progress-changed`', message: 'x-progress docs describe progress-changed event' },
      { pattern: '`progress-complete`', message: 'x-progress docs describe progress-complete event' },
      { pattern: '`xprogress-value-<id>`', message: 'x-progress docs describe state key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-progress docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-progress docs describe performance profile' },
      { pattern: 'setProgress(value)', message: 'x-progress docs describe setProgress API' },
      { pattern: 'complete()', message: 'x-progress docs describe complete API' }
    ]
  },
  'x-tooltip': {
    tag: 'x-tooltip',
    fileName: 'xtooltip.js',
    docTitle: 'xtooltip - XTend Komponente',
    label: 'x-tooltip component contract',
    sourcePath: 'components/xtooltip.js',
    fixturePath: 'tests/components/fixtures/xtooltip.component.html',
    docPath: 'docs/components/xtooltip.md',
    profiles: ['overlay', 'feedback'],
    observedAttributes: ['for', 'placement', 'open', 'delay', 'label'],
    sourceContracts: [
      { pattern: 'xtendComponentContract', message: 'x-tooltip exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-tooltip exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-tooltip exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-tooltip exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-tooltip keeps RMT kernel boundary visible' },
      { pattern: 'xtooltip-open-', message: 'x-tooltip syncs xstate open key' },
      { pattern: 'tooltip-opened', message: 'x-tooltip emits tooltip-opened' },
      { pattern: 'tooltip-closed', message: 'x-tooltip emits tooltip-closed' },
      { pattern: 'role="tooltip"', message: 'x-tooltip exposes tooltip role' },
      { pattern: 'aria-describedby', message: 'x-tooltip links anchor with describedby' },
      { pattern: 'dismiss-on-escape', message: 'x-tooltip declares Escape dismissal signal' },
      { pattern: "event.key === 'Escape'", message: 'x-tooltip supports Escape close' },
      { pattern: 'prefers-reduced-motion', message: 'x-tooltip respects reduced motion' },
      { pattern: 'forced-colors', message: 'x-tooltip supports forced-colors contrast mode' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-tooltip"', message: 'x-tooltip fixture uses a stable id' },
      { pattern: 'id="tooltip-anchor"', message: 'x-tooltip fixture covers external anchor' },
      { pattern: 'for="tooltip-anchor"', message: 'x-tooltip fixture covers for attribute' },
      { pattern: 'placement="top"', message: 'x-tooltip fixture covers placement attribute' },
      { pattern: 'delay="20"', message: 'x-tooltip fixture covers delay attribute' },
      { pattern: 'label="Tooltip help"', message: 'x-tooltip fixture covers label attribute' },
      { pattern: 'window.xstate', message: 'x-tooltip fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`tooltip-opened`', message: 'x-tooltip docs describe tooltip-opened event' },
      { pattern: '`tooltip-closed`', message: 'x-tooltip docs describe tooltip-closed event' },
      { pattern: '`xtooltip-open-<id>`', message: 'x-tooltip docs describe state key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-tooltip docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-tooltip docs describe performance profile' },
      { pattern: 'show()', message: 'x-tooltip docs describe show API' },
      { pattern: 'hide()', message: 'x-tooltip docs describe hide API' }
    ]
  },
  'x-popover': {
    tag: 'x-popover',
    fileName: 'xpopover.js',
    docTitle: 'xpopover - XTend Komponente',
    label: 'x-popover component contract',
    sourcePath: 'components/xpopover.js',
    fixturePath: 'tests/components/fixtures/xpopover.component.html',
    docPath: 'docs/components/xpopover.md',
    profiles: ['overlay', 'interactive'],
    observedAttributes: ['open', 'placement', 'modal', 'anchor', 'label'],
    sourceContracts: [
      { pattern: 'xtendComponentContract', message: 'x-popover exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-popover exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-popover exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-popover exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-popover keeps RMT kernel boundary visible' },
      { pattern: 'xpopover-open-', message: 'x-popover syncs xstate open key' },
      { pattern: 'popover-opened', message: 'x-popover emits popover-opened' },
      { pattern: 'popover-closed', message: 'x-popover emits popover-closed' },
      { pattern: 'role="dialog"', message: 'x-popover exposes dialog role' },
      { pattern: 'aria-modal', message: 'x-popover mirrors modal state' },
      { pattern: 'aria-expanded', message: 'x-popover mirrors expanded state' },
      { pattern: 'outside-click', message: 'x-popover supports outside click close' },
      { pattern: "event.key === 'Escape'", message: 'x-popover supports Escape close' },
      { pattern: 'focusable', message: 'x-popover implements focus trap candidates' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-popover"', message: 'x-popover fixture uses a stable id' },
      { pattern: 'placement="bottom"', message: 'x-popover fixture covers placement attribute' },
      { pattern: 'modal', message: 'x-popover fixture covers modal state' },
      { pattern: 'label="Filter options"', message: 'x-popover fixture covers label attribute' },
      { pattern: 'slot="trigger"', message: 'x-popover fixture covers trigger slot' },
      { pattern: 'slot="actions"', message: 'x-popover fixture covers actions slot' },
      { pattern: 'window.xstate', message: 'x-popover fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`popover-opened`', message: 'x-popover docs describe popover-opened event' },
      { pattern: '`popover-closed`', message: 'x-popover docs describe popover-closed event' },
      { pattern: '`xpopover-open-<id>`', message: 'x-popover docs describe state key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-popover docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-popover docs describe performance profile' },
      { pattern: 'show()', message: 'x-popover docs describe show API' },
      { pattern: 'hide()', message: 'x-popover docs describe hide API' }
    ]
  },
  'x-drawer': {
    tag: 'x-drawer',
    fileName: 'xdrawer.js',
    docTitle: 'xdrawer - XTend Komponente',
    label: 'x-drawer component contract',
    sourcePath: 'components/xdrawer.js',
    fixturePath: 'tests/components/fixtures/xdrawer.component.html',
    docPath: 'docs/components/xdrawer.md',
    profiles: ['overlay', 'routing'],
    observedAttributes: ['open', 'placement', 'modal', 'label', 'route-aware'],
    sourceContracts: [
      { pattern: 'xtendComponentContract', message: 'x-drawer exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-drawer exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-drawer exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-drawer exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-drawer keeps RMT kernel boundary visible' },
      { pattern: 'xdrawer-open-', message: 'x-drawer syncs xstate open key' },
      { pattern: 'drawer-opened', message: 'x-drawer emits drawer-opened' },
      { pattern: 'drawer-closed', message: 'x-drawer emits drawer-closed' },
      { pattern: 'drawer-route-selected', message: 'x-drawer emits route selection event' },
      { pattern: 'role="dialog"', message: 'x-drawer exposes dialog role' },
      { pattern: 'aria-modal', message: 'x-drawer mirrors modal state' },
      { pattern: 'aria-expanded', message: 'x-drawer mirrors expanded trigger state' },
      { pattern: 'xrouter-after-navigate', message: 'x-drawer listens to XRouter route signal' },
      { pattern: 'route-change-announcement', message: 'x-drawer declares route announcement signal' },
      { pattern: '--xdrawer-bg', message: 'x-drawer maps theme-aware surface tokens' },
      { pattern: 'var(--xtend-surface', message: 'x-drawer consumes XTend surface token fallbacks' },
      { pattern: ':host-context(html[data-theme="dark"])', message: 'x-drawer adapts to dark theme context' },
      { pattern: '_syncThemeAttribute', message: 'x-drawer mirrors document theme state' },
      { pattern: 'MutationObserver', message: 'x-drawer observes dynamic theme changes' },
      { pattern: 'aria-label="Close drawer"', message: 'x-drawer exposes labelled close control' },
      { pattern: 'part="close-icon control icon"', message: 'x-drawer exposes close icon parts instead of text content' },
      { pattern: '_releaseDrawerFocus', message: 'x-drawer releases focus before hiding the drawer surface' },
      { pattern: 'setAttribute(\'inert\'', message: 'x-drawer marks closed surfaces inert' },
      { pattern: "event.key === 'Escape'", message: 'x-drawer supports Escape close' },
      { pattern: 'focusable', message: 'x-drawer implements focus trap candidates' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-drawer"', message: 'x-drawer fixture uses a stable id' },
      { pattern: 'placement="left"', message: 'x-drawer fixture covers placement attribute' },
      { pattern: 'modal', message: 'x-drawer fixture covers modal state' },
      { pattern: 'label="App navigation"', message: 'x-drawer fixture covers label attribute' },
      { pattern: 'route-aware', message: 'x-drawer fixture covers route-aware attribute' },
      { pattern: 'slot="trigger"', message: 'x-drawer fixture covers trigger slot' },
      { pattern: 'slot="header"', message: 'x-drawer fixture covers header slot' },
      { pattern: 'slot="footer"', message: 'x-drawer fixture covers footer slot' },
      { pattern: 'window.xstate', message: 'x-drawer fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`drawer-opened`', message: 'x-drawer docs describe drawer-opened event' },
      { pattern: '`drawer-closed`', message: 'x-drawer docs describe drawer-closed event' },
      { pattern: '`drawer-route-selected`', message: 'x-drawer docs describe route event' },
      { pattern: '`xdrawer-open-<id>`', message: 'x-drawer docs describe state key' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-drawer docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-drawer docs describe performance profile' },
      { pattern: 'Theme und Tokens', message: 'x-drawer docs describe theme tokens' },
      { pattern: '`--drawer-bg-dark`', message: 'x-drawer docs describe dark theme surface token' },
      { pattern: '`--drawer-close-size`', message: 'x-drawer docs describe close button sizing token' },
      { pattern: '`inert`', message: 'x-drawer docs describe inert closed state' },
      { pattern: 'openDrawer()', message: 'x-drawer docs describe open API' },
      { pattern: 'closeDrawer()', message: 'x-drawer docs describe close API' }
    ]
  },
  'x-form': {
    tag: 'x-form',
    fileName: 'xform.js',
    docTitle: 'xform – XTend Komponente',
    label: 'x-form component contract',
    sourcePath: 'components/xform.js',
    fixturePath: 'tests/components/fixtures/xform.component.html',
    docPath: 'docs/components/xform.md',
    profiles: ['form', 'stateful'],
    sourceContracts: [
      { pattern: 'xform-data-', message: 'x-form syncs xstate form data' },
      { pattern: 'getFormData()', message: 'x-form exposes getFormData API' },
      { pattern: 'x-input, x-slider, x-calendar', message: 'x-form discovers supported child controls' },
      { pattern: 'x-select, x-checkbox, x-toggle, x-radio, x-textarea', message: 'x-form discovers WP-E10 form controls including x-toggle' },
      { pattern: 'select-changed', message: 'x-form listens to select changes' },
      { pattern: 'checkbox-changed', message: 'x-form listens to checkbox changes' },
      { pattern: 'radio-changed', message: 'x-form listens to radio changes' },
      { pattern: 'textarea-changed', message: 'x-form listens to textarea changes' },
      { pattern: 'new CustomEvent("submit"', message: 'x-form emits submit event' },
      { pattern: 'new CustomEvent("invalid"', message: 'x-form emits invalid event' },
      { pattern: 'new CustomEvent("reset"', message: 'x-form emits reset event' },
      { pattern: 'role="form"', message: 'x-form exposes form role' },
      { pattern: 'role="status"', message: 'x-form exposes status live region' },
      { pattern: 'role="alert"', message: 'x-form exposes error live region' },
      { pattern: 'MutationObserver', message: 'x-form tracks slotted controls after hydration' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-form"', message: 'x-form fixture uses a stable id' },
      { pattern: '<x-input', message: 'x-form fixture covers x-input child' },
      { pattern: '<x-select', message: 'x-form fixture covers x-select child' },
      { pattern: '<x-textarea', message: 'x-form fixture covers x-textarea child' },
      { pattern: '<x-checkbox', message: 'x-form fixture covers x-checkbox child' },
      { pattern: '<x-radio', message: 'x-form fixture covers x-radio child' },
      { pattern: '<x-calendar', message: 'x-form fixture covers x-calendar child' },
      { pattern: 'type="submit"', message: 'x-form fixture covers submit control' },
      { pattern: 'window.xstate', message: 'x-form fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`submit`', message: 'x-form docs describe submit event' },
      { pattern: '`invalid`', message: 'x-form docs describe invalid event' },
      { pattern: '`reset`', message: 'x-form docs describe reset event' },
      { pattern: '`xform-data-<id>`', message: 'x-form docs describe state key' },
      { pattern: '`select-changed`', message: 'x-form docs describe select event aggregation' },
      { pattern: '`checkbox-changed`', message: 'x-form docs describe checkbox event aggregation' },
      { pattern: '`radio-changed`', message: 'x-form docs describe radio event aggregation' },
      { pattern: '`textarea-changed`', message: 'x-form docs describe textarea event aggregation' },
      { pattern: 'getFormData()', message: 'x-form docs describe getFormData API' }
    ]
  },
  'x-tabs': {
    tag: 'x-tabs',
    fileName: 'xtabs.js',
    docTitle: 'xtabs – XTend Komponente',
    label: 'x-tabs component contract',
    sourcePath: 'components/xtabs.js',
    fixturePath: 'tests/components/fixtures/xtabs.component.html',
    docPath: 'docs/components/xtabs.md',
    profiles: ['interactive', 'routing'],
    observedAttributes: ['selected', 'text-color'],
    sourceContracts: [
      { pattern: 'xtendComponentContract', message: 'x-tabs exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-tabs exposes RMT metadata' },
      { pattern: 'xtendComponentLifecycleTelemetry', message: 'x-tabs exposes lifecycle telemetry metadata' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-tabs exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-tabs keeps RMT kernel boundary visible' },
      { pattern: 'tabSwitch: 16', message: 'x-tabs budgets tab switch work' },
      { pattern: 'keyboardAction: 16', message: 'x-tabs budgets keyboard work' },
      { pattern: 'snapshotPerformance()', message: 'x-tabs exposes performance snapshot API' },
      { pattern: 'customElements.define("x-tab"', message: 'x-tabs ships x-tab child component' },
      { pattern: 'xtabs-selected', message: 'x-tabs syncs selected index to xstate' },
      { pattern: 'tab-selected', message: 'x-tabs emits tab-selected' },
      { pattern: 'bubbles: true', message: 'x-tabs tab-selected bubbles for host/RMT listeners' },
      { pattern: 'composed: true', message: 'x-tabs tab-selected crosses Shadow DOM boundaries' },
      { pattern: 'role="tablist"', message: 'x-tabs exposes tablist role' },
      { pattern: 'btn.setAttribute("role", "tab")', message: 'x-tabs exposes tab roles' },
      { pattern: 'aria-selected', message: 'x-tabs mirrors selected state to aria-selected' },
      { pattern: 'aria-controls', message: 'x-tabs wires tabs to tab panels' },
      { pattern: 'aria-orientation', message: 'x-tabs exposes tablist orientation' },
      { pattern: 'role", "tabpanel"', message: 'x-tabs exposes tabpanel roles' },
      { pattern: 'tabindex', message: 'x-tabs implements roving tabindex' },
      { pattern: 'orientationAttribute', message: 'x-tabs exposes orientation for RMT shell authoring' },
      { pattern: 'ArrowRight', message: 'x-tabs supports next-tab keyboard navigation' },
      { pattern: 'ArrowLeft', message: 'x-tabs supports previous-tab keyboard navigation' },
      { pattern: 'ArrowDown', message: 'x-tabs supports vertical next-tab keyboard navigation' },
      { pattern: 'ArrowUp', message: 'x-tabs supports vertical previous-tab keyboard navigation' },
      { pattern: 'Home', message: 'x-tabs supports first-tab keyboard navigation' },
      { pattern: 'End', message: 'x-tabs supports last-tab keyboard navigation' },
      { pattern: 'selectTab(i)', message: 'x-tabs exposes selectTab API' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-tabs"', message: 'x-tabs fixture uses a stable id' },
      { pattern: 'selected="1"', message: 'x-tabs fixture covers selected attribute' },
      { pattern: 'text-color="#0f172a"', message: 'x-tabs fixture covers text-color attribute' },
      { pattern: 'orientation="vertical"', message: 'x-tabs fixture covers vertical orientation' },
      { pattern: 'data-rmt-schedule="ui.user-blocking.tabs"', message: 'x-tabs fixture covers RMT tab schedule metadata' },
      { pattern: 'data-xtend-lane="user-blocking"', message: 'x-tabs fixture covers Fabric lane metadata' },
      { pattern: '<x-tab name="Overview"', message: 'x-tabs fixture covers named child tabs' },
      { pattern: 'window.xstate', message: 'x-tabs fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`selected`', message: 'x-tabs docs describe selected attribute' },
      { pattern: '`orientation`', message: 'x-tabs docs describe orientation attribute' },
      { pattern: '`tab-selected`', message: 'x-tabs docs describe tab-selected event' },
      { pattern: '`bubbles: true`', message: 'x-tabs docs describe bubbling event behavior' },
      { pattern: '`composed: true`', message: 'x-tabs docs describe composed event behavior' },
      { pattern: '`xtabs-selected`', message: 'x-tabs docs describe state key' },
      { pattern: 'Keyboard-Navigation', message: 'x-tabs docs describe keyboard navigation' },
      { pattern: '`aria-controls`', message: 'x-tabs docs describe ARIA panel wiring' },
      { pattern: '`Home`', message: 'x-tabs docs describe Home keyboard navigation' },
      { pattern: '`End`', message: 'x-tabs docs describe End keyboard navigation' },
      { pattern: '`ArrowUp`', message: 'x-tabs docs describe vertical keyboard navigation' },
      { pattern: 'Performance-Profil', message: 'x-tabs docs describe performance profile' },
      { pattern: '`snapshotPerformance()`', message: 'x-tabs docs describe performance snapshot API' }
    ]
  },
  'x-dialog': {
    tag: 'x-dialog',
    fileName: 'xdialog.js',
    docTitle: 'xdialog - XTend Komponente',
    label: 'x-dialog component contract',
    sourcePath: 'components/xdialog.js',
    fixturePath: 'tests/components/fixtures/xdialog.component.html',
    docPath: 'docs/components/xdialog.md',
    profiles: ['overlay'],
    observedAttributes: ['open', 'overlay', 'title', 'width', 'height'],
    sourceContracts: [
      { pattern: 'xtendScreenreaderSignals', message: 'x-dialog declares screenreader signals' },
      { pattern: 'xtendMotionContrastPolicy', message: 'x-dialog declares motion and contrast policy' },
      { pattern: 'xtend.component.x-dialog.', message: 'x-dialog syncs canonical open-state key' },
      { pattern: 'dialog-open-', message: 'x-dialog keeps dialog-open compatibility key' },
      { pattern: 'xdialog-open-', message: 'x-dialog keeps xdialog-open compatibility key' },
      { pattern: 'dialog-opened', message: 'x-dialog emits dialog-opened' },
      { pattern: 'dialog-closed', message: 'x-dialog emits dialog-closed' },
      { pattern: 'role="dialog"', message: 'x-dialog exposes dialog role' },
      { pattern: 'aria-modal="true"', message: 'x-dialog marks modal semantics' },
      { pattern: 'aria-labelledby', message: 'x-dialog labels the dialog' },
      { pattern: 'event.key === \'Escape\'', message: 'x-dialog supports Escape close' },
      { pattern: 'focusable', message: 'x-dialog implements focus trap candidates' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-dialog"', message: 'x-dialog fixture uses a stable id' },
      { pattern: 'open', message: 'x-dialog fixture covers open attribute' },
      { pattern: 'overlay', message: 'x-dialog fixture covers overlay attribute' },
      { pattern: 'title="Component dialog"', message: 'x-dialog fixture covers title attribute' },
      { pattern: 'width="420px"', message: 'x-dialog fixture covers width attribute' },
      { pattern: 'window.xstate', message: 'x-dialog fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`dialog-opened`', message: 'x-dialog docs describe dialog-opened' },
      { pattern: '`dialog-closed`', message: 'x-dialog docs describe dialog-closed' },
      { pattern: '`xtend.component.x-dialog.<id>.open`', message: 'x-dialog docs describe canonical open key' },
      { pattern: '`xdialog-open-<id>`', message: 'x-dialog docs describe compatibility key' }
    ]
  },
  'x-lightbox': {
    tag: 'x-lightbox',
    fileName: 'xlightbox.js',
    docTitle: 'xlightbox – XTend Komponente',
    label: 'x-lightbox component contract',
    sourcePath: 'components/xlightbox.js',
    fixturePath: 'tests/components/fixtures/xlightbox.component.html',
    docPath: 'docs/components/xlightbox.md',
    profiles: ['overlay', 'media'],
    observedAttributes: ['src', 'open', 'alt'],
    sourceContracts: [
      { pattern: 'xlightbox-open-', message: 'x-lightbox syncs xstate open key' },
      { pattern: 'lightbox-opened', message: 'x-lightbox emits lightbox-opened' },
      { pattern: 'lightbox-closed', message: 'x-lightbox emits lightbox-closed' },
      { pattern: 'role="dialog"', message: 'x-lightbox exposes dialog role' },
      { pattern: 'aria-hidden', message: 'x-lightbox syncs aria-hidden' },
      { pattern: 'aria-modal="true"', message: 'x-lightbox marks modal dialog semantics' },
      { pattern: 'aria-label="Schliessen"', message: 'x-lightbox labels close button' },
      { pattern: 'event.key === \'Escape\'', message: 'x-lightbox supports Escape close' },
      { pattern: 'slot name="trigger"', message: 'x-lightbox exposes a trigger slot' },
      { pattern: '_ensureDocumentPortal', message: 'x-lightbox portals overlays to the document body' },
      { pattern: 'data-xtend-portal', message: 'x-lightbox marks document-body portal state' },
      { pattern: 'max-height: calc(100dvh', message: 'x-lightbox constrains media to dynamic viewport height' },
      { pattern: 'object-fit: contain', message: 'x-lightbox preserves image aspect ratio inside viewport' },
      { pattern: 'inert', message: 'x-lightbox makes the closed overlay inert' },
      { pattern: 'window.showLightbox', message: 'x-lightbox exposes global showLightbox helper' },
      { pattern: 'XLightbox.show', message: 'x-lightbox exposes static show helper' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-lightbox"', message: 'x-lightbox fixture uses a stable id' },
      { pattern: 'src="/tests/components/fixtures/demo-image.svg"', message: 'x-lightbox fixture covers src attribute' },
      { pattern: 'slot="trigger"', message: 'x-lightbox fixture covers trigger slot' },
      { pattern: 'data-xlightbox', message: 'x-lightbox fixture covers data-xlightbox enhancement' },
      { pattern: 'window.xstate', message: 'x-lightbox fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`src`', message: 'x-lightbox docs describe src attribute' },
      { pattern: '`open`', message: 'x-lightbox docs describe open attribute' },
      { pattern: '`trigger`', message: 'x-lightbox docs describe trigger slot' },
      { pattern: 'document.body', message: 'x-lightbox docs describe document body portal' },
      { pattern: '`lightbox-opened`', message: 'x-lightbox docs describe lightbox-opened' },
      { pattern: '`lightbox-closed`', message: 'x-lightbox docs describe lightbox-closed' },
      { pattern: '`xlightbox-open-<id>`', message: 'x-lightbox docs describe state key' }
    ]
  },
  'x-calendar': {
    tag: 'x-calendar',
    fileName: 'xcalendar.js',
    docTitle: 'xcalendar – XTend Komponente',
    label: 'x-calendar component contract',
    sourcePath: 'components/xcalendar.js',
    fixturePath: 'tests/components/fixtures/xcalendar.component.html',
    docPath: 'docs/components/xcalendar.md',
    profiles: ['form', 'interactive'],
    sourceContracts: [
      { pattern: 'static formAssociated = true', message: 'x-calendar is form-associated' },
      { pattern: 'xcalendar-state-', message: 'x-calendar syncs xstate calendar state' },
      { pattern: 'date-select', message: 'x-calendar emits date-select' },
      { pattern: 'role="grid"', message: 'x-calendar exposes grid role' },
      { pattern: 'role", "gridcell"', message: 'x-calendar exposes day gridcell role' },
      { pattern: 'aria-selected', message: 'x-calendar mirrors selected date to aria-selected' },
      { pattern: 'aria-label="Previous Month"', message: 'x-calendar labels previous month control' },
      { pattern: 'set value(dateStr)', message: 'x-calendar exposes value setter' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-calendar"', message: 'x-calendar fixture uses a stable id' },
      { pattern: 'data-contract-date="2026-05-06"', message: 'x-calendar fixture covers deterministic contract date' },
      { pattern: 'window.xstate', message: 'x-calendar fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`date-select`', message: 'x-calendar docs describe date-select event' },
      { pattern: '`xcalendar-state-<id>`', message: 'x-calendar docs describe state key' },
      { pattern: '`value`', message: 'x-calendar docs describe value API' },
      { pattern: 'ARIA-Rollen', message: 'x-calendar docs describe accessibility' }
    ]
  },
  'x-writer': {
    tag: 'x-writer',
    fileName: 'xwriter.js',
    docTitle: 'xwriter – XTend Komponente',
    label: 'x-writer component contract',
    sourcePath: 'components/xwriter.js',
    fixturePath: 'tests/components/fixtures/xwriter.component.html',
    docPath: 'docs/components/xwriter.md',
    profiles: ['form', 'stateful'],
    observedAttributes: ['storage-key'],
    sourceContracts: [
      { pattern: 'xwriter-content', message: 'x-writer syncs editor content to xstate' },
      { pattern: 'writer:change', message: 'x-writer emits writer:change' },
      { pattern: 'writer:save', message: 'x-writer emits writer:save' },
      { pattern: 'writer:error', message: 'x-writer emits writer:error' },
      { pattern: 'writer:autosave', message: 'x-writer emits writer:autosave' },
      { pattern: 'writer:export', message: 'x-writer emits writer:export' },
      { pattern: 'localStorage.setItem', message: 'x-writer supports local persistence' },
      { pattern: 'loadMarkdownLib', message: 'x-writer loads markdown helper' },
      { pattern: 'contenteditable="true"', message: 'x-writer renders editable surface' },
      { pattern: 'enableExportButtons', message: 'x-writer guards export affordances' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-writer"', message: 'x-writer fixture uses a stable id' },
      { pattern: 'storage-key="component-writer-content"', message: 'x-writer fixture covers storage-key attribute' },
      { pattern: 'api="local"', message: 'x-writer fixture covers local API mode' },
      { pattern: 'autosave="60000"', message: 'x-writer fixture covers autosave attribute' },
      { pattern: 'window.xstate', message: 'x-writer fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`storage-key`', message: 'x-writer docs describe storage-key attribute' },
      { pattern: '`writer:change`', message: 'x-writer docs describe writer:change' },
      { pattern: '`writer:save`', message: 'x-writer docs describe writer:save' },
      { pattern: '`writer:autosave`', message: 'x-writer docs describe writer:autosave' }
    ]
  },
  'x-button': {
    tag: 'x-button',
    fileName: 'xbutton.js',
    docTitle: 'xbutton – XTend Komponente',
    label: 'x-button component contract',
    sourcePath: 'components/xbutton.js',
    fixturePath: 'tests/components/fixtures/xbutton.component.html',
    docPath: 'docs/components/xbutton.md',
    profiles: ['interactive'],
    observedAttributes: ['disabled', 'label', 'variant', 'size', 'icon', 'loading', 'overlay', 'aria-label', 'aria-busy'],
    sourceContracts: [
      { pattern: 'xbutton-state-', message: 'x-button syncs state key' },
      { pattern: 'loading-start', message: 'x-button emits loading-start' },
      { pattern: 'loading-end', message: 'x-button emits loading-end' },
      { pattern: 'role="button"', message: 'x-button exposes button role' },
      { pattern: 'aria-disabled', message: 'x-button mirrors disabled state to aria-disabled' },
      { pattern: 'aria-busy', message: 'x-button mirrors loading state to aria-busy' },
      { pattern: 'prefers-reduced-motion', message: 'x-button respects reduced motion' },
      { pattern: 'forced-colors', message: 'x-button supports forced-colors contrast mode' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-button exposes Performance profile' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-button exposes RMT metadata' },
      { pattern: 'button-interaction', message: 'x-button emits interaction telemetry' },
      { pattern: 'button-performance-measured', message: 'x-button emits Fabric performance measurement' },
      { pattern: 'snapshotPerformance()', message: 'x-button exposes performance snapshot API' },
      { pattern: 'getInteractionBudget()', message: 'x-button exposes interaction budget API' },
      { pattern: '_syncLabelFallback()', message: 'x-button preserves its default slot for late slotted icon hydration' },
      { pattern: 'fallback-label', message: 'x-button keeps fallback text inside the slot instead of replacing the slot' },
      { pattern: '--xtend-button-min-touch-target', message: 'x-button declares touch target token' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-button"', message: 'x-button fixture uses a stable id' },
      { pattern: 'variant="danger"', message: 'x-button fixture covers variant attribute' },
      { pattern: 'size="large"', message: 'x-button fixture covers size attribute' },
      { pattern: 'loading', message: 'x-button fixture covers loading attribute' },
      { pattern: 'aria-label="Save settings"', message: 'x-button fixture covers aria-label' },
      { pattern: 'window.xstate', message: 'x-button fixture stubs xstate locally' },
      { pattern: 'button-interaction', message: 'x-button fixture observes interaction telemetry' },
      { pattern: 'snapshotPerformance()', message: 'x-button fixture validates performance snapshot' },
      { pattern: '__xtendComponentResult', message: 'x-button fixture exposes a component result object' }
    ],
    docContracts: [
      { pattern: '`loading-start`', message: 'x-button docs describe loading-start' },
      { pattern: '`loading-end`', message: 'x-button docs describe loading-end' },
      { pattern: '`aria-busy`', message: 'x-button docs describe aria-busy' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-button docs describe performance profile' },
      { pattern: '`button-interaction`', message: 'x-button docs describe interaction telemetry' },
      { pattern: '`snapshotPerformance()`', message: 'x-button docs describe performance snapshot API' }
    ]
  },
  'x-icon': {
    tag: 'x-icon',
    fileName: 'xicon.js',
    docTitle: 'xicon – XTend Komponente',
    label: 'x-icon component contract',
    sourcePath: 'components/xicon.js',
    fixturePath: 'tests/components/fixtures/xicon.component.html',
    docPath: 'docs/components/xicon.md',
    profiles: ['display', 'iconography'],
    observedAttributes: ['name', 'pack', 'src', 'label', 'size', 'stroke-width', 'color', 'decorative'],
    sourceContracts: [
      { pattern: 'XTendIconRegistry', message: 'x-icon exposes registry runtime' },
      { pattern: 'registerIconPack(pack', message: 'x-icon exposes icon pack registration API' },
      { pattern: 'resolveIcon(name', message: 'x-icon exposes icon resolution API' },
      { pattern: 'createXTendCoreIconPack', message: 'x-icon ships internal core icon pack adapter' },
      { pattern: 'createXTendLucideIconPack', message: 'x-icon ships local Lucide icon pack adapter' },
      { pattern: 'cdnAllowed: false', message: 'x-icon defaults icon packs to local CDN-free distribution' },
      { pattern: 'isSafeIconUrl', message: 'x-icon validates external icon URLs before rendering' },
      { pattern: 'appendSafeSvgMarkup', message: 'x-icon sanitizes raw SVG pack markup before rendering' },
      { pattern: 'xicon-state-', message: 'x-icon syncs state key' },
      { pattern: 'icon-ready', message: 'x-icon emits icon-ready' },
      { pattern: 'icon-missing', message: 'x-icon emits icon-missing' },
      { pattern: "setAttribute('role', 'img')", message: 'x-icon exposes semantic image role when labeled' },
      { pattern: 'aria-hidden', message: 'x-icon hides decorative icons from assistive tech' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-icon exposes RMT metadata' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-icon exposes Performance profile' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-icon keeps RMT kernel boundary visible' },
      { pattern: '--xtend-icon-size', message: 'x-icon declares icon size token' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-icon"', message: 'x-icon fixture uses a stable id' },
      { pattern: 'name="search"', message: 'x-icon fixture covers name attribute' },
      { pattern: 'pack="lucide"', message: 'x-icon fixture covers local Lucide adapter' },
      { pattern: 'label="Search"', message: 'x-icon fixture covers accessible label' },
      { pattern: 'stroke-width="2.25"', message: 'x-icon fixture covers stroke-width attribute' },
      { pattern: 'window.xstate', message: 'x-icon fixture stubs xstate locally' },
      { pattern: 'window.XTend.icons.register', message: 'x-icon fixture registers a custom pack' },
      { pattern: 'icon-ready', message: 'x-icon fixture observes icon-ready' },
      { pattern: '__xtendComponentResult', message: 'x-icon fixture exposes a component result object' }
    ],
    docContracts: [
      { pattern: '`core` Pack', message: 'x-icon docs describe internal core pack' },
      { pattern: '`lucide` Adapter', message: 'x-icon docs describe local Lucide adapter' },
      { pattern: '`window.XTend.icons.register(pack, options?)`', message: 'x-icon docs describe global registry API' },
      { pattern: '`icon-ready`', message: 'x-icon docs describe icon-ready event' },
      { pattern: '`icon-missing`', message: 'x-icon docs describe icon-missing event' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-icon docs describe RMT contract' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-icon docs describe performance profile' },
      { pattern: '`aria-hidden`', message: 'x-icon docs describe decorative accessibility behavior' }
    ]
  },
  'x-spinner': {
    tag: 'x-spinner',
    fileName: 'xspinner.js',
    docTitle: 'xspinner – XTend Komponente',
    label: 'x-spinner component contract',
    sourcePath: 'components/xspinner.js',
    fixturePath: 'tests/components/fixtures/xspinner.component.html',
    docPath: 'docs/components/xspinner.md',
    profiles: ['feedback', 'display'],
    observedAttributes: ['paused', 'size', 'color', 'speed', 'type', 'overlay', 'aria-label', 'aria-busy', 'aria-valuetext'],
    sourceContracts: [
      { pattern: 'xspinner-paused-', message: 'x-spinner syncs paused state key' },
      { pattern: 'spinner-started', message: 'x-spinner emits spinner-started' },
      { pattern: 'spinner-stopped', message: 'x-spinner emits spinner-stopped' },
      { pattern: 'newValue !== null ? "paused" : "resumed"', message: 'x-spinner emits pause/resume events' },
      { pattern: 'if (value === paused) return;', message: 'x-spinner avoids recursive paused state mirroring' },
      { pattern: 'if (oldValue === newValue) return;', message: 'x-spinner ignores idempotent attribute changes' },
      { pattern: 'role", "status"', message: 'x-spinner exposes status role' },
      { pattern: 'aria-live', message: 'x-spinner exposes live region semantics' },
      { pattern: 'aria-busy', message: 'x-spinner exposes busy semantics' },
      { pattern: 'prefers-reduced-motion', message: 'x-spinner respects reduced motion' },
      { pattern: 'forced-colors', message: 'x-spinner supports forced-colors contrast mode' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-spinner"', message: 'x-spinner fixture uses a stable id' },
      { pattern: 'type="dots"', message: 'x-spinner fixture covers type attribute' },
      { pattern: 'paused', message: 'x-spinner fixture covers paused attribute' },
      { pattern: 'aria-label="Loading dashboard"', message: 'x-spinner fixture covers aria-label' },
      { pattern: 'aria-valuetext="Loading 50 percent"', message: 'x-spinner fixture covers aria-valuetext' },
      { pattern: 'window.xstate', message: 'x-spinner fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`spinner-started`', message: 'x-spinner docs describe spinner-started' },
      { pattern: 'xspinner-paused-', message: 'x-spinner docs describe paused state key' },
      { pattern: '`aria-valuetext`', message: 'x-spinner docs describe aria-valuetext' }
    ]
  },
  'x-menu': {
    tag: 'x-menu',
    fileName: 'xmenu.js',
    docTitle: 'xmenu – XTend Komponente',
    label: 'x-menu component contract',
    sourcePath: 'components/xmenu.js',
    fixturePath: 'tests/components/fixtures/xmenu.component.html',
    docPath: 'docs/components/xmenu.md',
    profiles: ['interactive'],
    sourceContracts: [
      { pattern: 'xtendComponentContract', message: 'x-menu exposes Component Contract metadata' },
      { pattern: 'xtendRmtMetadata', message: 'x-menu exposes RMT metadata' },
      { pattern: 'xtendScaffoldA11yProfile', message: 'x-menu exposes A11y profile' },
      { pattern: 'xtendScaffoldPerformanceProfile', message: 'x-menu exposes Performance profile' },
      { pattern: 'xtend.rmt.component-contract.v1', message: 'x-menu declares RMT component contract schema' },
      { pattern: 'no-rmt-kernel-import-of-xtend-types', message: 'x-menu keeps RMT kernel boundary visible' },
      { pattern: 'role="menubar"', message: 'x-menu exposes menubar role' },
      { pattern: 'setAttribute("role", "menuitem")', message: 'x-menu exposes menuitem role' },
      { pattern: 'xmenu-active', message: 'x-menu syncs active item to xstate' },
      { pattern: '_stateTargetsThisMenu', message: 'x-menu scopes shared active state by menu id' },
      { pattern: '_resolveFocusIndex', message: 'x-menu separates roving focus from current-page state' },
      { pattern: 'menu-item-clicked', message: 'x-menu emits menu-item-clicked' },
      { pattern: 'menu-navigate', message: 'x-menu emits menu-navigate' },
      { pattern: 'menu-keyboard-navigation', message: 'x-menu emits keyboard navigation telemetry' },
      { pattern: 'menu-performance-measured', message: 'x-menu emits performance measurements' },
      { pattern: 'aria-current', message: 'x-menu mirrors active item to aria-current' },
      { pattern: 'ArrowRight', message: 'x-menu supports next keyboard navigation' },
      { pattern: 'ArrowLeft', message: 'x-menu supports previous keyboard navigation' },
      { pattern: 'Home', message: 'x-menu supports Home key' },
      { pattern: 'End', message: 'x-menu supports End key' },
      { pattern: 'x-link', message: 'x-menu supports slotted x-link hosts' },
      { pattern: 'x-router', message: 'x-menu derives router compatibility' },
      { pattern: 'snapshotPerformance()', message: 'x-menu exposes performance snapshot API' },
      { pattern: 'getInteractionBudget()', message: 'x-menu exposes interaction budget API' },
      { pattern: '--xtend-menu-min-touch-target', message: 'x-menu exposes touch target token' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-menu"', message: 'x-menu fixture uses a stable id' },
      { pattern: 'href="/overview"', message: 'x-menu fixture covers link item' },
      { pattern: '<x-router', message: 'x-menu fixture covers router host compatibility' },
      { pattern: '<x-link href="/settings"', message: 'x-menu fixture covers x-link host compatibility' },
      { pattern: 'data-rmt-schedule="ui.user-blocking.navigation"', message: 'x-menu fixture covers RMT navigation schedule metadata' },
      { pattern: 'data-xtend-lane="user-blocking"', message: 'x-menu fixture covers Fabric lane metadata' },
      { pattern: 'role="menuitem"', message: 'x-menu fixture covers explicit menuitem' },
      { pattern: 'window.xstate', message: 'x-menu fixture stubs xstate locally' },
      { pattern: 'menu-performance-measured', message: 'x-menu fixture observes performance telemetry' },
      { pattern: 'parallel menu does not synthesize current page', message: 'x-menu fixture does not mark a focus fallback as the current page' },
      { pattern: 'parallel menu retains roving focus', message: 'x-menu fixture keeps one focusable item without a current page' },
      { pattern: 'parallel menu state avoids feedback writes', message: 'x-menu fixture blocks cross-menu state feedback cascades' },
      { pattern: 'snapshotPerformance()', message: 'x-menu fixture validates performance snapshot' },
      { pattern: '__xtendComponentResult', message: 'x-menu fixture exposes a component result object' }
    ],
    docContracts: [
      { pattern: 'Keyboard-Navigation', message: 'x-menu docs describe keyboard navigation' },
      { pattern: 'ARIA-Rollen', message: 'x-menu docs describe ARIA roles' },
      { pattern: '`menu-item-clicked`', message: 'x-menu docs describe menu-item-clicked' },
      { pattern: '`menu-navigate`', message: 'x-menu docs describe menu-navigate' },
      { pattern: '`xmenu-active`', message: 'x-menu docs describe active state key' },
      { pattern: 'xtend.performance.component-profile.v1', message: 'x-menu docs describe performance profile' },
      { pattern: 'snapshotPerformance()', message: 'x-menu docs describe performance snapshot API' }
    ]
  },
  'x-summary': {
    tag: 'x-summary',
    fileName: 'xsummary.js',
    docTitle: 'xsummary - XTend Komponente',
    label: 'x-summary component contract',
    sourcePath: 'components/xsummary.js',
    fixturePath: 'tests/components/fixtures/xsummary.component.html',
    docPath: 'docs/components/xsummary.md',
    profiles: ['display', 'stateful'],
    observedAttributes: ['open', 'type'],
    sourceContracts: [
      { pattern: 'xsummary-open-', message: 'x-summary syncs open state key' },
      { pattern: 'new CustomEvent(isOpen ? "open" : "close"', message: 'x-summary emits open/close events' },
      { pattern: 'role="button"', message: 'x-summary exposes button role' },
      { pattern: 'aria-expanded', message: 'x-summary mirrors expanded state' },
      { pattern: 'details[open] .icon {\n          transform: rotate(180deg);', message: 'x-summary points its disclosure indicator upward while expanded' },
      { pattern: 'e.key === "Enter" || e.key === " "', message: 'x-summary supports keyboard toggle' },
      { pattern: '_applyOpenState', message: 'x-summary centralizes open-state synchronization' },
      { pattern: '_syncingAttribute', message: 'x-summary guards attribute reflection against recursive updates' },
      { pattern: 'value === this._isOpen()', message: 'x-summary ignores xstate updates that already match the DOM state' },
      { pattern: 'xstate.get(this._stateKey) === isOpen', message: 'x-summary avoids publishing unchanged xstate values' },
      { pattern: '}, this._stateKey)', message: 'x-summary subscribes only to its own xstate key' },
      { pattern: 'open()', message: 'x-summary exposes open API' },
      { pattern: 'close()', message: 'x-summary exposes close API' },
      { pattern: 'toggle()', message: 'x-summary exposes toggle API' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-summary"', message: 'x-summary fixture uses a stable id' },
      { pattern: 'type="info"', message: 'x-summary fixture covers type attribute' },
      { pattern: 'open', message: 'x-summary fixture covers open attribute' },
      { pattern: 'slot="title"', message: 'x-summary fixture covers title slot' },
      { pattern: 'window.xstate', message: 'x-summary fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`open`', message: 'x-summary docs describe open attribute' },
      { pattern: '`close`', message: 'x-summary docs describe close event' },
      { pattern: 'xsummary-open-<id>', message: 'x-summary docs describe state key' },
      { pattern: 'reentrant-sicher', message: 'x-summary docs describe loop-safe xstate synchronization' },
      { pattern: 'aria-expanded', message: 'x-summary docs describe aria-expanded' }
    ]
  },
  'x-player': {
    tag: 'x-player',
    fileName: 'xplayer.js',
    docTitle: 'xplayer – XTend Komponente',
    label: 'x-player component contract',
    sourcePath: 'components/xplayer.js',
    fixturePath: 'tests/components/fixtures/xplayer.component.html',
    docPath: 'docs/components/xplayer.md',
    profiles: ['media', 'interactive'],
    observedAttributes: ['src', 'poster', 'type', 'media-chooser', 'downloadable', 'autoplay', 'title', 'height', 'width'],
    sourceContracts: [
      { pattern: 'xplayer-state-', message: 'x-player syncs media state key' },
      { pattern: 'xplayer-spinner-', message: 'x-player syncs spinner state key' },
      { pattern: 'xplayer-play', message: 'x-player emits play event' },
      { pattern: 'xplayer-pause', message: 'x-player emits pause event' },
      { pattern: 'xplayer-fullscreen', message: 'x-player emits fullscreen event' },
      { pattern: 'xplayer-pip', message: 'x-player emits picture-in-picture event' },
      { pattern: 'xplayer-caption', message: 'x-player emits caption event' },
      { pattern: 'role="region"', message: 'x-player exposes media region role' },
      { pattern: 'role="slider"', message: 'x-player exposes seekbar slider role' },
      { pattern: 'aria-label="Media Player"', message: 'x-player labels player region' },
      { pattern: 'playsinline', message: 'x-player supports mobile inline playback' }
    ],
    fixtureContracts: [
      { pattern: 'id="component-player"', message: 'x-player fixture uses a stable id' },
      { pattern: 'src="/tests/components/fixtures/demo-video.mp4"', message: 'x-player fixture covers src attribute' },
      { pattern: 'poster="/tests/components/fixtures/demo-poster.svg"', message: 'x-player fixture covers poster attribute' },
      { pattern: 'title="Component player"', message: 'x-player fixture covers title attribute' },
      { pattern: 'media-chooser', message: 'x-player fixture covers media chooser attribute' },
      { pattern: 'window.xstate', message: 'x-player fixture stubs xstate locally' }
    ],
    docContracts: [
      { pattern: '`xplayer-play`', message: 'x-player docs describe play event' },
      { pattern: '`xplayer-pause`', message: 'x-player docs describe pause event' },
      { pattern: '`src`', message: 'x-player docs describe src attribute' }
    ]
  }
};

function runPriorityComponentSuite(tag, options = {}) {
  const config = priorityComponentConfigs[tag];
  if (!config) {
    throw new Error(`Unknown priority component suite: ${tag}`);
  }
  return runComponentContractSuite(config, options);
}

function printPriorityComponentReport(result) {
  printComponentContractReport(result);
}

module.exports = {
  printPriorityComponentReport,
  priorityComponentConfigs,
  runPriorityComponentSuite
};
