// @generated by XTend Scaffold - maraca-app-services
import { defineAppServices, service } from '@ccslabs/xtend-maraca/app-services';

export default defineAppServices({
  '{{serviceId}}': service({
    kind: 'query',
    target: 'server',
    concurrency: 'latest'
  })
});
