// @generated by XTend Scaffold - maraca-server-services
import { defineServerServices, service } from '@ccslabs/xtend-maraca/server-services';

export default defineServerServices({
  '{{serviceId}}': service({
    kind: 'query',
    target: 'server',
    async invoke(input: unknown, { signal, correlationId }) {
      signal.throwIfAborted();
      return {
        schema: 'xtend.maraca.health.v1',
        ok: true,
        input,
        correlationId
      };
    }
  })
});
