<?php
declare(strict_types=1);

// @generated by XTend Scaffold - maraca-php-services
return [
    '{{serviceId}}' => static function ($input, array $context = []): array {
        return [
            'schema' => 'xtend.maraca.health.v1',
            'ok' => true,
            'input' => $input,
            'correlationId' => $context['correlationId'] ?? null,
        ];
    },
];
