// @generated by XTend Scaffold RMT app build.
// Source: xtendrmt/rmt-lifecycle-demo.rmt
// Command: node xtend-builder/scaffold.js rmt-build --source xtendrmt/rmt-lifecycle-demo.rmt --write --json
import '../components/x-rmt-lifecycle-demo-build.js';

const SOURCE_URL = new URL('./rmt-lifecycle-demo.rmt', import.meta.url);
const CORE_URL = new URL('./rmt-lifecycle-demo.rmt-build.core.json', import.meta.url);
const REPORT_URL = new URL('./rmt-lifecycle-demo.rmt-build.scaffold.json', import.meta.url);
const BUILD_FINGERPRINT = Object.freeze({
  "schema": "xtend.scaffold.rmt-app-build.v1",
  "source": "xtendrmt/rmt-lifecycle-demo.rmt",
  "sourceSha256": "77ca654f845c8dd26e5c6ab58471548f24299b393baa27485653706771b06f0d",
  "core": "xtendrmt/rmt-lifecycle-demo.rmt-build.core.json",
  "coreSha256": "8cbd4da913280ec61869d3ef8cd24c18370dc0d268355affbeee56fce02522a8",
  "scaffoldReport": "xtendrmt/rmt-lifecycle-demo.rmt-build.scaffold.json",
  "generatedComponent": "components/x-rmt-lifecycle-demo-build.js",
  "componentTag": "x-rmt-lifecycle-demo-build",
  "sourceSyntax": "rmt-vnext",
  "counts": {
    "templates": 1,
    "surfaces": 4,
    "remoteSurfaces": 0,
    "lanes": 5,
    "operations": 6,
    "slots": 1,
    "events": 1,
    "dataSources": 6
  },
  "stages": [
    {
      "id": "template",
      "label": "RMT vNext Template",
      "artifact": "xtendrmt/rmt-lifecycle-demo.rmt",
      "status": "source"
    },
    {
      "id": "core",
      "label": "Compiler Core",
      "artifact": "xtendrmt/rmt-lifecycle-demo.rmt-build.core.json",
      "status": "compiled"
    },
    {
      "id": "scaffold",
      "label": "Scaffold Build",
      "artifact": "components/x-rmt-lifecycle-demo-build.js",
      "status": "generated"
    },
    {
      "id": "http",
      "label": "HTTP/Test",
      "artifact": "xtendrmt-rmt-lifecycle-demo-rmt-build.html",
      "status": "servable"
    }
  ]
});

function text(value) {
  return document.createTextNode(String(value));
}

function element(tagName, attributes = {}, children = []) {
  const node = document.createElement(tagName);
  Object.entries(attributes).forEach(([name, value]) => {
    if (value === false || value === null || value === undefined) return;
    if (value === true) {
      node.setAttribute(name, '');
      return;
    }
    node.setAttribute(name, String(value));
  });
  children.forEach((child) => node.appendChild(typeof child === 'string' ? text(child) : child));
  return node;
}

async function fetchText(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Unable to load ${url.pathname}: ${response.status}`);
  return response.text();
}

async function fetchJson(url) {
  return JSON.parse(await fetchText(url));
}

function renderRmtBuild(root, payload) {
  const component = element('x-rmt-lifecycle-demo-build', {
    'aria-label': 'RMT app build',
    'data-rmt-build-component': BUILD_FINGERPRINT.componentTag
  });
  const summary = element('section', { class: 'xtend-rmt-build-summary' }, [
    element('h1', {}, ['RMT App Build']),
    element('p', {}, [BUILD_FINGERPRINT.source]),
    element('dl', {}, [
      element('dt', {}, ['Templates']),
      element('dd', {}, [String(BUILD_FINGERPRINT.counts.templates)]),
      element('dt', {}, ['Surfaces']),
      element('dd', {}, [String(BUILD_FINGERPRINT.counts.surfaces)]),
      element('dt', {}, ['Operations']),
      element('dd', {}, [String(BUILD_FINGERPRINT.counts.operations)])
    ])
  ]);
  component.appendChild(summary);
  root.replaceChildren(component);
  root.setAttribute('data-rmt-build-rendered', 'true');
  return {
    root,
    core: payload.core,
    report: payload.report,
    source: payload.source,
    fingerprint: BUILD_FINGERPRINT
  };
}

async function bootRmtBuildApp(options = {}) {
  const root = options.root || document.querySelector('[data-rmt-build-root]');
  if (!root) throw new Error('RMT build root not found');
  root.setAttribute('aria-busy', 'true');
  try {
    const payload = {
      source: await fetchText(SOURCE_URL),
      core: await fetchJson(CORE_URL),
      report: await fetchJson(REPORT_URL)
    };
    const result = renderRmtBuild(root, payload);
    root.setAttribute('aria-busy', 'false');
    window.__XTendRmtBuildResult = {
      status: 'passed',
      schema: 'xtend.scaffold.rmt-app-build.v1',
      sourceSyntax: result.core.manifest.sourceSyntax,
      generatedBy: result.report.buildCommand,
      counts: BUILD_FINGERPRINT.counts
    };
    return result;
  } catch (error) {
    root.setAttribute('aria-busy', 'false');
    root.setAttribute('data-rmt-build-rendered', 'failed');
    window.__XTendRmtBuildResult = {
      status: 'failed',
      schema: 'xtend.scaffold.rmt-app-build.v1',
      error: error.message
    };
    throw error;
  }
}

window.XTendRmtBuildApp = {
  schema: 'xtend.scaffold.rmt-app-build.v1',
  build: BUILD_FINGERPRINT,
  bootRmtBuildApp
};

export { BUILD_FINGERPRINT, bootRmtBuildApp };
export default window.XTendRmtBuildApp;
