// @generated by XTend Scaffold RMT lifecycle build.
// Source: xtendrmt/rmt-lifecycle-demo.rmt
// Command: node xtend-builder/scaffold.js rmt-lifecycle-demo --write --json
import '../components/x-rmt-lifecycle-demo.js';
import '../components/xsection.js';
import '../components/xcards.js';
import '../components/xcode.js';
import '../components/xstatus.js';
import '../components/xprogress.js';

const SOURCE_URL = new URL('./rmt-lifecycle-demo.rmt', import.meta.url);
const CORE_URL = new URL('./rmt-lifecycle-demo.core.json', import.meta.url);
const REPORT_URL = new URL('./rmt-lifecycle-demo.scaffold.json', import.meta.url);
const BUILD_FINGERPRINT = Object.freeze({
  "schema": "xtend.rmt.lifecycle-demo.v1",
  "buildSchema": "xtend.rmt.lifecycle-demo.scaffold-build.v1",
  "source": "xtendrmt/rmt-lifecycle-demo.rmt",
  "sourceSha256": "77ca654f845c8dd26e5c6ab58471548f24299b393baa27485653706771b06f0d",
  "core": "xtendrmt/rmt-lifecycle-demo.core.json",
  "coreSha256": "24e6ef71f8baeaa4a483c0f51895c5599ba17ace4e657d913da36644c4fc452a",
  "scaffoldReport": "xtendrmt/rmt-lifecycle-demo.scaffold.json",
  "generatedComponent": "components/x-rmt-lifecycle-demo.js",
  "generatedBy": "node xtend-builder/scaffold.js rmt-lifecycle-demo --write --json",
  "sourceSyntax": "rmt-vnext",
  "counts": {
    "templates": 1,
    "surfaces": 4,
    "lanes": 5,
    "operations": 6,
    "slots": 1,
    "events": 1,
    "dataSources": 6
  },
  "stages": [
    {
      "id": "template",
      "label": "RMT vNext Template",
      "artifact": "xtendrmt/rmt-lifecycle-demo.rmt",
      "status": "source",
      "detail": "Authoring source; kein JSON-Fallback und keine manuelle App-Shell."
    },
    {
      "id": "core",
      "label": "Compiler Core",
      "artifact": "xtendrmt/rmt-lifecycle-demo.core.json",
      "status": "compiled",
      "detail": "4 Surfaces, 5 Lanes und 6 Lifecycle-Operationen."
    },
    {
      "id": "scaffold",
      "label": "Scaffold Build",
      "artifact": "components/x-rmt-lifecycle-demo.js",
      "status": "generated",
      "detail": "XTend Custom Element und Demo-App werden vom Scaffold-Generator geschrieben."
    },
    {
      "id": "http",
      "label": "HTTP/Test",
      "artifact": "tests/browser/fixtures/rmt-lifecycle-demo-smoke.html",
      "status": "servable",
      "detail": "Host und Browser-Smoke laufen ueber den lokalen XTend Dev Server."
    }
  ]
});

function ensureStyles() {
  if (document.querySelector('style[data-rmt-lifecycle-demo-style]')) return;
  const style = document.createElement('style');
  style.setAttribute('data-rmt-lifecycle-demo-style', 'true');
  style.textContent = `
    :root {
      --rmt-life-ink: #172033;
      --rmt-life-muted: #5d697a;
      --rmt-life-line: #d8dee8;
      --rmt-life-surface: #ffffff;
      --rmt-life-soft: #f5f7fa;
      --rmt-life-accent: #0f766e;
      --rmt-life-warm: #b45309;
      --rmt-life-build: #334155;
    }

    body {
      background: #f2f5f7;
      color: var(--rmt-life-ink);
    }

    x-rmt-lifecycle-demo::part(root) {
      border: 0;
      border-radius: 0;
      padding: 0;
      background: transparent;
    }

    .rmt-lifecycle-app {
      display: grid;
      gap: 24px;
      width: min(1180px, calc(100vw - 32px));
      margin: 0 auto;
      padding: 24px 0 48px;
      box-sizing: border-box;
    }

    .rmt-lifecycle-toolbar {
      display: grid;
      grid-template-columns: auto minmax(0, 1fr) auto;
      gap: 16px;
      align-items: center;
      padding: 18px 0 8px;
      border-bottom: 1px solid var(--rmt-life-line);
    }

    .rmt-lifecycle-logo {
      width: 48px;
      height: 48px;
      object-fit: contain;
    }

    .rmt-lifecycle-title {
      display: grid;
      gap: 4px;
      min-width: 0;
    }

    .rmt-lifecycle-title h1 {
      margin: 0;
      font-size: 1.55rem;
      line-height: 1.2;
      letter-spacing: 0;
    }

    .rmt-lifecycle-title p {
      margin: 0;
      color: var(--rmt-life-muted);
      line-height: 1.45;
    }

    .rmt-lifecycle-meta {
      display: flex;
      flex-wrap: wrap;
      gap: 8px;
      justify-content: flex-end;
      min-width: 0;
    }

    .rmt-lifecycle-chip {
      display: inline-flex;
      align-items: center;
      min-height: 30px;
      padding: 0 10px;
      border: 1px solid var(--rmt-life-line);
      border-radius: 999px;
      background: var(--rmt-life-surface);
      color: var(--rmt-life-build);
      font-size: 0.88rem;
      white-space: nowrap;
    }

    .rmt-lifecycle-grid {
      display: grid;
      grid-template-columns: minmax(0, 1fr) minmax(320px, 0.72fr);
      gap: 18px;
      align-items: start;
    }

    .rmt-lifecycle-panel {
      display: grid;
      gap: 16px;
      min-width: 0;
    }

    .rmt-lifecycle-pipeline {
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 12px;
      margin: 0;
      padding: 0;
      list-style: none;
    }

    .rmt-lifecycle-step {
      display: grid;
      grid-template-rows: auto auto minmax(64px, 1fr) auto;
      gap: 8px;
      min-width: 0;
      min-height: 178px;
      padding: 14px;
      border: 1px solid var(--rmt-life-line);
      border-radius: 8px;
      background: var(--rmt-life-surface);
      box-sizing: border-box;
    }

    .rmt-lifecycle-step strong,
    .rmt-lifecycle-step span,
    .rmt-lifecycle-step code {
      overflow-wrap: anywhere;
    }

    .rmt-lifecycle-stage-number {
      width: 28px;
      height: 28px;
      display: inline-grid;
      place-items: center;
      border-radius: 999px;
      background: #e0f2f1;
      color: #0f766e;
      font-weight: 700;
    }

    .rmt-lifecycle-detail {
      color: var(--rmt-life-muted);
      line-height: 1.45;
    }

    .rmt-lifecycle-path {
      color: var(--rmt-life-build);
      font-size: 0.82rem;
    }

    .rmt-lifecycle-kpis {
      display: grid;
      grid-template-columns: repeat(4, minmax(0, 1fr));
      gap: 10px;
    }

    .rmt-lifecycle-kpi {
      display: grid;
      gap: 4px;
      padding: 12px;
      border: 1px solid var(--rmt-life-line);
      border-radius: 8px;
      background: var(--rmt-life-soft);
      min-width: 0;
    }

    .rmt-lifecycle-kpi span {
      color: var(--rmt-life-muted);
      font-size: 0.82rem;
    }

    .rmt-lifecycle-kpi strong {
      font-size: 1.35rem;
      color: var(--rmt-life-accent);
    }

    .rmt-lifecycle-side {
      display: grid;
      gap: 14px;
      min-width: 0;
    }

    .rmt-lifecycle-artifact {
      display: grid;
      gap: 10px;
      padding: 14px;
      border: 1px solid var(--rmt-life-line);
      border-radius: 8px;
      background: var(--rmt-life-surface);
      min-width: 0;
    }

    .rmt-lifecycle-artifact h2 {
      margin: 0;
      font-size: 1rem;
      line-height: 1.3;
    }

    .rmt-lifecycle-artifact p {
      margin: 0;
      color: var(--rmt-life-muted);
      line-height: 1.45;
    }

    .rmt-lifecycle-artifact x-code {
      max-height: 320px;
      overflow: auto;
    }

    @media (max-width: 920px) {
      .rmt-lifecycle-toolbar,
      .rmt-lifecycle-grid {
        grid-template-columns: 1fr;
      }

      .rmt-lifecycle-meta {
        justify-content: flex-start;
      }

      .rmt-lifecycle-pipeline,
      .rmt-lifecycle-kpis {
        grid-template-columns: repeat(2, minmax(0, 1fr));
      }
    }

    @media (max-width: 560px) {
      .rmt-lifecycle-app {
        width: min(100%, calc(100vw - 20px));
        padding-top: 12px;
      }

      .rmt-lifecycle-pipeline,
      .rmt-lifecycle-kpis {
        grid-template-columns: 1fr;
      }
    }
  `;
  document.head.appendChild(style);
}

function append(parent, child) {
  if (child === null || child === undefined) return parent;
  if (Array.isArray(child)) {
    child.forEach((entry) => append(parent, entry));
    return parent;
  }
  parent.appendChild(typeof child === 'string' ? document.createTextNode(child) : child);
  return parent;
}

function element(tagName, attributes = {}, children = []) {
  const node = document.createElement(tagName);
  Object.entries(attributes).forEach(([name, value]) => {
    if (value === false || value === null || value === undefined) return;
    if (value === true) {
      node.setAttribute(name, '');
      return;
    }
    node.setAttribute(name, String(value));
  });
  append(node, children);
  return node;
}

function codeBlock(lang, text) {
  const block = element('x-code', { lang });
  const template = document.createElement('template');
  template.setAttribute('data-x-code-mode', 'text');
  template.content.appendChild(document.createTextNode(String(text || '').trim()));
  block.appendChild(template);
  return block;
}

async function fetchText(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Unable to load ${url.pathname}: ${response.status}`);
  return response.text();
}

async function fetchJson(url) {
  return JSON.parse(await fetchText(url));
}

function renderStage(stage, index) {
  return element('li', {
    class: 'rmt-lifecycle-step',
    'data-rmt-lifecycle-stage': stage.id
  }, [
    element('span', { class: 'rmt-lifecycle-stage-number' }, String(index + 1)),
    element('strong', {}, stage.label),
    element('span', { class: 'rmt-lifecycle-detail' }, stage.detail),
    element('code', { class: 'rmt-lifecycle-path' }, stage.artifact)
  ]);
}

function renderKpi(label, value) {
  return element('div', { class: 'rmt-lifecycle-kpi' }, [
    element('span', {}, label),
    element('strong', {}, String(value))
  ]);
}

function renderDemo(root, payload) {
  ensureStyles();
  const core = payload.core;
  const report = payload.report;
  const counts = BUILD_FINGERPRINT.counts;
  const shell = element('x-rmt-lifecycle-demo', {
    'aria-label': 'RMT Lifecycle Demo',
    'data-generated-by': 'xtend-scaffold'
  });
  const app = element('main', { class: 'rmt-lifecycle-app' }, [
    element('header', { class: 'rmt-lifecycle-toolbar' }, [
      element('img', {
        class: 'rmt-lifecycle-logo',
        alt: 'XTend Scaffold',
        src: new URL('../icons/xtend-scaffold.webp', import.meta.url).pathname
      }),
      element('div', { class: 'rmt-lifecycle-title' }, [
        element('h1', {}, 'RMT Lifecycle Demo'),
        element('p', {}, 'vNext Template rein, Scaffold Build raus: Core JSON, XTend Custom Element, App-Modul, Host und Smoke Fixture.')
      ]),
      element('div', { class: 'rmt-lifecycle-meta' }, [
        element('span', { class: 'rmt-lifecycle-chip' }, BUILD_FINGERPRINT.sourceSyntax),
        element('span', { class: 'rmt-lifecycle-chip' }, report.status),
        element('span', { class: 'rmt-lifecycle-chip' }, 'HTTP-ready')
      ])
    ]),
    element('section', { class: 'rmt-lifecycle-grid' }, [
      element('div', { class: 'rmt-lifecycle-panel' }, [
        element('x-status', {
          type: 'success',
          state: 'ready',
          label: 'Lifecycle Build',
          message: 'Scaffold hat die Demo-Artefakte aus dem RMT vNext Template erzeugt.'
        }),
        element('ol', { class: 'rmt-lifecycle-pipeline' }, BUILD_FINGERPRINT.stages.map(renderStage)),
        element('div', { class: 'rmt-lifecycle-kpis' }, [
          renderKpi('Templates', counts.templates),
          renderKpi('Surfaces', counts.surfaces),
          renderKpi('Lanes', counts.lanes),
          renderKpi('Operations', counts.operations)
        ]),
        element('x-progress', {
          value: '100',
          max: '100',
          label: 'Lifecycle completeness'
        })
      ]),
      element('aside', { class: 'rmt-lifecycle-side' }, [
        element('section', { class: 'rmt-lifecycle-artifact' }, [
          element('h2', {}, 'Source Template'),
          element('p', {}, SOURCE_URL.pathname),
          codeBlock('rmt', payload.source)
        ]),
        element('section', { class: 'rmt-lifecycle-artifact' }, [
          element('h2', {}, 'Compiled Core'),
          element('p', {}, `${core.schema} - ${core.manifest.documentId}`),
          codeBlock('json', JSON.stringify({
            schema: core.schema,
            documentId: core.manifest.documentId,
            sourceSyntax: core.manifest.sourceSyntax,
            counts
          }, null, 2))
        ]),
        element('section', { class: 'rmt-lifecycle-artifact' }, [
          element('h2', {}, 'Scaffold Output'),
          element('p', {}, report.buildCommand),
          codeBlock('json', JSON.stringify({
            generatedComponent: report.generated.component,
            generatedApp: report.generated.app,
            host: report.generated.host,
            browserSmoke: report.generated.browserSmoke
          }, null, 2))
        ])
      ])
    ])
  ]);
  shell.appendChild(app);
  root.replaceChildren(shell);
  root.setAttribute('data-rmt-lifecycle-rendered', 'true');
  return { root, core, report, fingerprint: BUILD_FINGERPRINT };
}

async function bootRmtLifecycleDemo(options = {}) {
  const root = options.root || document.querySelector('[data-rmt-lifecycle-demo-root]');
  if (!root) throw new Error('RMT lifecycle demo root not found');
  root.setAttribute('aria-busy', 'true');
  try {
    const payload = {
      source: await fetchText(SOURCE_URL),
      core: await fetchJson(CORE_URL),
      report: await fetchJson(REPORT_URL)
    };
    const result = renderDemo(root, payload);
    root.setAttribute('aria-busy', 'false');
    window.__XTendRmtLifecycleDemoResult = {
      status: 'passed',
      schema: 'xtend.rmt.lifecycle-demo.v1',
      sourceSyntax: result.core.manifest.sourceSyntax,
      generatedBy: result.report.buildCommand,
      counts: BUILD_FINGERPRINT.counts
    };
    return result;
  } catch (error) {
    root.setAttribute('aria-busy', 'false');
    root.setAttribute('data-rmt-lifecycle-rendered', 'failed');
    window.__XTendRmtLifecycleDemoResult = {
      status: 'failed',
      schema: 'xtend.rmt.lifecycle-demo.v1',
      error: error.message
    };
    throw error;
  }
}

window.XTendRmtLifecycleDemo = {
  schema: 'xtend.rmt.lifecycle-demo.v1',
  build: BUILD_FINGERPRINT,
  bootRmtLifecycleDemo
};

export { BUILD_FINGERPRINT, bootRmtLifecycleDemo };
export default window.XTendRmtLifecycleDemo;
