'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {createRequire}=require('node:module');
const {digest,verifyCandidates,verifyInstalledClosure,verifyResolution}=require('../../candidate-integrity.cjs');
const {verifyEvidence,verifyReportFiles,verifyInstallationFiles,required}=require('../../scripts/product-candidate-evidence.cjs');
const coreSha='1'.repeat(40),demoSha='2'.repeat(40);
function fixture(t) {
 const directory=fs.mkdtempSync(path.join(os.tmpdir(),'candidate-contract-'));t.after(()=>fs.rmSync(directory,{recursive:true,force:true}));
 fs.writeFileSync(path.join(directory,'core.tgz'),'candidate');fs.writeFileSync(path.join(directory,'php.tar'),'php');
 const packages=[{name:'@fixture/core',version:'0.9.0',file:'core.tgz',sha256:digest(Buffer.from('candidate')),integrity:'sha512-'+require('node:crypto').createHash('sha512').update('candidate').digest('base64')}];
 const manifest={schema:'xtend.product-candidates.v1',coreSha,demoSha,packages,php:{file:'php.tar',sha256:digest(Buffer.from('php')),sources:{'runtime.php':digest(Buffer.from('source'))}}};
 return {directory,manifest};
}
test('exact identities and digests accept only matching immutable candidate files',t=>{const {directory,manifest}=fixture(t);assert.equal(verifyCandidates(manifest,{directory,coreSha,demoSha}),manifest);});
test('wrong Core SHA and wrong Demo SHA reject even when tarballs exist',t=>{const {directory,manifest}=fixture(t);for(const args of [{coreSha:'3'.repeat(40),demoSha},{coreSha,demoSha:'4'.repeat(40)}])assert.throws(()=>verifyCandidates(manifest,{directory,...args}),/SHA/);});
test('wrong npm and PHP digests reject',t=>{const {directory,manifest}=fixture(t);fs.writeFileSync(path.join(directory,'core.tgz'),'tampered');assert.throws(()=>verifyCandidates(manifest,{directory,coreSha,demoSha}),/digest|integrity/);fs.writeFileSync(path.join(directory,'core.tgz'),'candidate');manifest.php.sha256='0'.repeat(64);assert.throws(()=>verifyCandidates(manifest,{directory,coreSha,demoSha}),/fingerprint/);});
test('missing tarball never resolves from an available sibling Core checkout',t=>{const {directory,manifest}=fixture(t);const sibling=path.join(directory,'xtend');fs.mkdirSync(sibling);fs.writeFileSync(path.join(sibling,'core.tgz'),'candidate');fs.rmSync(path.join(directory,'core.tgz'));assert.throws(()=>verifyCandidates(manifest,{directory,coreSha,demoSha}),/Missing/);});
test('candidate resolver rejects symlinked tarballs and escaping names',t=>{const {directory,manifest}=fixture(t);fs.renameSync(path.join(directory,'core.tgz'),path.join(directory,'actual.tgz'));fs.symlinkSync('actual.tgz',path.join(directory,'core.tgz'));assert.throws(()=>verifyCandidates(manifest,{directory,coreSha,demoSha}),/regular/);manifest.packages[0].file='../core.tgz';assert.throws(()=>verifyCandidates(manifest,{directory,coreSha,demoSha}),/path/);});
test('transitive Registry fallback and links reject despite a valid direct candidate',t=>{const {manifest}=fixture(t);const entry={version:'0.9.0',resolved:'file:.candidate/core.tgz',integrity:manifest.packages[0].integrity};const lock={packages:{'node_modules/@fixture/core':entry}};assert.equal(verifyInstalledClosure(lock,manifest),true);lock.packages['node_modules/dependent/node_modules/@fixture/core']={...entry,resolved:'https://registry.npmjs.org/core.tgz'};assert.throws(()=>verifyInstalledClosure(lock,manifest),/Registry fallback/);delete lock.packages['node_modules/dependent/node_modules/@fixture/core'];entry.link=true;assert.throws(()=>verifyInstalledClosure(lock,manifest),/linked/);});
test('actual Node ancestor resolution is rejected outside the isolated Demo node_modules',t=>{const {directory,manifest}=fixture(t);const ancestor=path.join(directory,'node_modules/@fixture/core');fs.mkdirSync(ancestor,{recursive:true});fs.writeFileSync(path.join(ancestor,'package.json'),JSON.stringify({name:'@fixture/core',version:'0.9.0'}));const demo=path.join(directory,'demo');fs.mkdirSync(demo);fs.mkdirSync(path.join(demo,'node_modules'));const req=createRequire(path.join(demo,'package.json'));assert.throws(()=>verifyResolution(req,manifest,path.join(demo,'node_modules')),/outside/);});
function evidence(packages,php){return {schema:'xtend.product-candidate-evidence.v1',ok:true,status:'passed',coreSha,demoSha,packages,php,generatedAt:new Date().toISOString(),commands:required.map(id=>({id,status:'passed',exitCode:0,skips:[]}))};}
test('publish acceptance fails closed for missing, failed, stale, mismatched or incomplete evidence',t=>{const {manifest}=fixture(t);const good=evidence(manifest.packages,manifest.php);good.installation=Array.from({length:8},(_,i)=>({product:String(i),status:'passed',lockSha256:'a'.repeat(64)}));good.reports=required.map(id=>({id,file:'reports/'+id+'.json',sha256:'b'.repeat(64),status:'passed'}));const expected={coreSha,demoSha,packages:manifest.packages,php:manifest.php,installation:good.installation,reports:good.reports};assert.equal(verifyEvidence(good,expected),true);for(const bad of [null,{...good,ok:false},{...good,generatedAt:'2020-01-01T00:00:00Z'},{...good,coreSha:'3'.repeat(40)},{...good,demoSha:'4'.repeat(40)},{...good,packages:[]},{...good,php:{}},{...good,php:{...good.php,sha256:'0'.repeat(64)}},{...good,php:{...good.php,sources:{'runtime.php':'wrong'}}},{...good,installation:[]},{...good,reports:good.reports.slice(1)},{...good,commands:good.commands.slice(1)},{...good,commands:[...good.commands,{id:'skipped',status:'passed',exitCode:0,skips:['missing browser']}]}])assert.throws(()=>verifyEvidence(bad,expected));});

test('copied report bytes, exact SHAs and status are checked independently',t=>{const {directory}=fixture(t);fs.mkdirSync(path.join(directory,'reports'));const filename=path.join(directory,'reports/http-security.json');let result={schema:'xtend.product-suite-result.v1',id:'http-security',coreSha,demoSha,status:'passed',exitCode:0,skips:[]};const write=()=>{const bytes=Buffer.from(JSON.stringify(result));fs.writeFileSync(filename,bytes);return [{id:'http-security',file:'reports/http-security.json',sha256:digest(bytes),status:'passed'}];};let reports=write();assert.equal(verifyReportFiles(reports,{directory,coreSha,demoSha}),true);fs.appendFileSync(filename,' ');assert.throws(()=>verifyReportFiles(reports,{directory,coreSha,demoSha}),/digest/);for(const change of [{coreSha:'3'.repeat(40)},{demoSha:'4'.repeat(40)},{status:'failed'},{exitCode:1},{skips:['missing Chrome']}]){result={...result,...change};reports=write();assert.throws(()=>verifyReportFiles(reports,{directory,coreSha,demoSha}),/identity/);}});

test('candidate lock version, integrity and dependency metadata cannot drift',t=>{const {manifest}=fixture(t);const base={version:'0.9.0',resolved:'file:.candidate/core.tgz',integrity:manifest.packages[0].integrity};for(const patch of [{version:'0.8.0'},{integrity:'wrong'},{dependencies:{'@fixture/other':'latest'}}])assert.throws(()=>verifyInstalledClosure({packages:{'node_modules/@fixture/core':{...base,...patch}}},manifest));});

test('all eight installation lock files must match identities, bytes and candidate closure',t=>{
 const {directory,manifest}=fixture(t);fs.mkdirSync(path.join(directory,'locks'));
 const products=['.','products/maraca-app-services-test-bench','products/resumability-maraca-erp-demo','products/rmt-animation-testbench','products/rmt-maraca-kernel-orchestration','products/xtend-llm','products/xtend-material-workbench','products/xtend-shop'];
 const lock={packages:{'node_modules/@fixture/core':{version:'0.9.0',resolved:'file:.candidate/core.tgz',integrity:manifest.packages[0].integrity}}};
 const bytes=Buffer.from(JSON.stringify(lock));const installation=products.map(product=>{const file='locks/'+(product==='.'?'root':product.split('/').at(-1))+'.json';fs.writeFileSync(path.join(directory,file),bytes);return {product,file,status:'passed',lockSha256:digest(bytes)};});
 assert.equal(verifyInstallationFiles(installation,{directory,manifest}),true);
 assert.throws(()=>verifyInstallationFiles(installation.slice(1),{directory,manifest}),/product set/);
 assert.throws(()=>verifyInstallationFiles([...installation.slice(1),installation[1]],{directory,manifest}),/product set/);
 fs.appendFileSync(path.join(directory,installation[0].file),' ');assert.throws(()=>verifyInstallationFiles(installation,{directory,manifest}),/digest/);
 lock.packages['node_modules/@fixture/core'].resolved='https://registry.npmjs.org/core.tgz';const altered=Buffer.from(JSON.stringify(lock));fs.writeFileSync(path.join(directory,installation[0].file),altered);installation[0].lockSha256=digest(altered);assert.throws(()=>verifyInstallationFiles(installation,{directory,manifest}),/Registry fallback/);
});
