'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const {execFileSync,spawnSync}=require('node:child_process');
test('SHA archive packing excludes untracked published files and fingerprints generated PHP', {timeout:60000},t=>{
 const temp=fs.mkdtempSync(path.join(os.tmpdir(),'xtend-pack-source-'));t.after(()=>fs.rmSync(temp,{recursive:true,force:true}));
 const source=path.join(temp,'core'),output=path.join(temp,'candidates');fs.mkdirSync(path.join(source,'scripts'),{recursive:true});
 const root=path.resolve(__dirname,'../..');
 for(const file of ['candidate-integrity.cjs','scripts/product-candidate-canary.cjs','scripts/product-candidate-evidence.cjs','scripts/build_laravel_package.js'])fs.copyFileSync(path.join(root,file),path.join(source,file));
 fs.writeFileSync(path.join(source,'package.json'),JSON.stringify({name:'@fixture/exact-core',version:'0.9.0',workspaces:[],files:['candidate-integrity.cjs','docs','security','tools']}));
 fs.writeFileSync(path.join(source,'LICENSE'),'fixture license');
 for(const directory of ['laravel/src','laravel/config','laravel/resources','xtendrmt','xscaler','docs','security','tools'])fs.mkdirSync(path.join(source,directory),{recursive:true});
 for(const directory of ['laravel/src','laravel/config','laravel/resources'])fs.writeFileSync(path.join(source,directory,'.keep'),'tracked fixture directory');
 fs.writeFileSync(path.join(source,'laravel/composer.json'),JSON.stringify({name:'fixture/php',autoload:{files:['runtime/runtime.php']}}));
 fs.writeFileSync(path.join(source,'laravel/README.md'),'tracked PHP');fs.writeFileSync(path.join(source,'xtendrmt/runtime.php'),'<?php // tracked runtime');
 fs.writeFileSync(path.join(source,'docs/tracked.md'),'tracked documentation');
 const git=args=>execFileSync('git',args,{cwd:source,encoding:'utf8'}).trim();
 git(['init','-q']);git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.test','commit','-qm','exact source']);
 const sha=git(['rev-parse','HEAD']);
 for(const directory of ['docs','security','tools'])fs.writeFileSync(path.join(source,directory,'untracked-must-not-publish.js'),'untracked contamination');
 const run=spawnSync(process.execPath,['scripts/product-candidate-canary.cjs','--pack-only','--demo-sha','2'.repeat(40),'--out',output],{cwd:source,encoding:'utf8',timeout:55000});
 assert.equal(run.status,0,run.stdout+'\n'+run.stderr);
 const manifest=JSON.parse(fs.readFileSync(path.join(output,'manifest.json')));assert.equal(manifest.coreSha,sha);assert.equal(manifest.development,false);
 const packed=execFileSync('tar',['-tf',path.join(output,manifest.packages[0].file)],{encoding:'utf8'});
 assert.ok(packed.includes('package/docs/tracked.md'));
 assert.ok(!packed.includes('untracked-must-not-publish'),packed);
 const {digest}=require('../../candidate-integrity.cjs');
 assert.equal(manifest.php.sources['runtime.php'],digest(Buffer.from('<?php // tracked runtime')));
 const phpSource=execFileSync('tar',['-xOf',path.join(output,manifest.php.file),'./runtime/runtime.php']);
 assert.equal(digest(phpSource),manifest.php.sources['runtime.php']);
});
