'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),zlib=require('node:zlib'),ts=require('typescript');
const expectedSchema=require('../../tools/schema-inventory/command-lexical-overlay.json').schemaId;
const root=path.resolve(__dirname,'../..'),sha=b=>crypto.createHash('sha256').update(b).digest('hex');
const canonical=fs.readFileSync(path.join(root,'xtend-maraca/plan-runtime.mjs'),'utf8'),output=zlib.gunzipSync(fs.readFileSync(path.join(__dirname,'fixtures/command-runtime-d1.mjs.gz'))).toString();
// Exact current D1 output fixture, not a historical or full product pass.
function extract(source,name){const file=ts.createSourceFile('actual.mjs',source,ts.ScriptTarget.Latest,true,ts.ScriptKind.JS),found=[];function visit(n){if(ts.isFunctionDeclaration(n)&&n.name?.text===name)found.push(n.getText(file));ts.forEachChild(n,visit);}visit(file);assert.equal(found.length,1);return found[0];}
function adapters(source){return new Function(extract(source,'asRecord')+';const SYSTEM_REFRESH_COMMAND="xtend.system.refresh";function recordLegacyAdapter(){};function dispatchCommand(envelope){return envelope};'+extract(source,'render')+';'+extract(source,'refresh')+';return {render,refresh};')();}
function check(source){const api=adapters(source);for(const name of ['render','refresh']){for(const input of [undefined,null,'bad',[],0])assert.deepEqual(api[name](input),{schema:expectedSchema,command:'xtend.system.refresh',metadata:{operation:'maraca.'+name}});const input={operation:'custom.operation',correlationId:'fixed',extra:7};assert.deepEqual(api[name](input),{schema:expectedSchema,command:'xtend.system.refresh',metadata:input});assert.deepEqual(input,{operation:'custom.operation',correlationId:'fixed',extra:7});}}
test('digest-bound current D1 fixture and retained canonical adapters preserve command construction',()=>{assert.equal(sha(output),'16e583631727612eac9922c20a24d078a30af0b10b43306fb3d8ee2f7b12673c');assert.equal(sha(canonical),'79f8163164a204469691c7a067ac5a90333dbc7b4c740e9465f0eda764bfdda1');check(canonical);check(output);});
test('schema default-operation metadata-spread and caller-override mutations fail',()=>{const body=extract(canonical,'render');for(const mutate of [s=>s.replace("schema: 'xtend.rmt.command.v1'","schema: 'wrong'"),s=>s.replace("|| 'maraca.render'","|| 'wrong.render'"),s=>s.replace('...asRecord(metadata),',''),s=>s.replace("asRecord(metadata).operation || 'maraca.render'","'maraca.render'")]){const bad=mutate(body);assert.notEqual(bad,body);assert.throws(()=>check(canonical.replace(body,bad)));}});
test('actual production minifier with repository-resolved Terser reproduces exact current D1 bytes',async t=>{const temp=fs.mkdtempSync(path.join(os.tmpdir(),'command-reproduction-'));t.after(()=>fs.rmSync(temp,{recursive:true,force:true}));const terser=require('terser'),builder=fs.readFileSync(path.join(root,'xtend-maraca/index.js'),'utf8'),minify=new Function('fs','requireOptional',extract(builder,'minifyCopiedMaracaRuntimeAssets')+';return minifyCopiedMaracaRuntimeAssets;')(fs,()=>({available:true,module:terser})),filename=path.join(temp,'runtime.mjs');fs.writeFileSync(filename,canonical);const asset={fileName:'runtime/xtend-maraca-plan-runtime.mjs',path:filename};await minify({profile:'production',rootDir:root},[asset]);assert.equal(sha(fs.readFileSync(filename)),sha(output));assert.equal(asset.bytes,Buffer.byteLength(output));});
test('actual production minifier rejects missing code',async()=>{const builder=fs.readFileSync(path.join(root,'xtend-maraca/index.js'),'utf8'),minify=new Function('fs','requireOptional',extract(builder,'minifyCopiedMaracaRuntimeAssets')+';return minifyCopiedMaracaRuntimeAssets;')(fs,()=>({available:true,module:{minify:async()=>({})}}));await assert.rejects(minify({profile:'production'},[{fileName:'runtime/input.mjs',path:path.join(root,'xtend-maraca/plan-runtime.mjs')}]),/Terser did not return code/);});
