'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const api=require('../../tools/schema-inventory/index.cjs'),overlay=require('../../tools/schema-inventory/command-lexical-overlay.json'),ids=require('../../tools/schema-inventory/selection.json');
const ledgerBytes=require('node:zlib').gunzipSync(fs.readFileSync(path.join(__dirname,'../../tools/schema-inventory/ownership-ledger.json.gz'))),ledger=JSON.parse(ledgerBytes);
// Controlled scanner envelopes from immutable ledger and exact measured overlay.
// They prove narrow validator behavior, not current 101-ID source conservation.
function fixture(){const entries=ids.map(id=>structuredClone(ledger.entries.find(e=>e.schemaId===id))),core={entries:structuredClone(entries)},demo={entries:structuredClone(entries)};demo.entries.find(e=>e.schemaId===overlay.schemaId).shapeFingerprints.push(...structuredClone(overlay.variants));const inventory={selection:ids,entries:structuredClone(demo.entries)};const e=inventory.entries.find(e=>e.schemaId===overlay.schemaId);e.shapePolicy.acceptedFingerprints=e.shapeFingerprints.map(f=>f.hash).sort();return {core,demo,inventory};}
test('historical raw ledger is unchanged and only exact 101 selection is valid',()=>{assert.equal(crypto.createHash('sha256').update(ledgerBytes).digest('hex'),'40a4e1d38dbf9e64a724d69178803768e6bff22c90c8260f5644916c24e127c8');api.assertSelection(ids);assert.equal(ids.length,101);for(const bad of [ids.filter(id=>id!==overlay.schemaId),[...ids,'other.id'],ids.slice().reverse()])assert.throws(()=>api.assertSelection(bad));});
test('controlled paired union keeps all historical 15 plus exactly two lexical variants',()=>{const {core,demo,inventory}=fixture();const rows=api.verifyUnion(core,demo),row=rows.find(r=>r.schemaId===overlay.schemaId);assert.equal(rows.length,101);assert.equal(row.hashes.length,17);const old=ledger.entries.find(e=>e.schemaId===overlay.schemaId);for(const hash of old.shapePolicy.acceptedFingerprints)assert.ok(row.hashes.includes(hash));assert.equal(api.validateOwner(demo,inventory,'demo').length,101);});
test('missing old hash, third new hash, and altered shape with claimed exact hash reject',()=>{for(const kind of ['missing-old','third','changed']){const {core,demo}=fixture(),a=core.entries.find(e=>e.schemaId===overlay.schemaId),b=demo.entries.find(e=>e.schemaId===overlay.schemaId);if(kind==='missing-old'){const h=a.shapeFingerprints[0].hash;a.shapeFingerprints=a.shapeFingerprints.filter(f=>f.hash!==h);b.shapeFingerprints=b.shapeFingerprints.filter(f=>f.hash!==h);}if(kind==='third')b.shapeFingerprints.push({hash:'sha256:'+'0'.repeat(64),shape:{}});if(kind==='changed')b.shapeFingerprints.find(f=>f.hash===overlay.variants[0].hash).shape={changed:true};assert.throws(()=>api.verifyUnion(core,demo));}});
test('exact overlay hashes cannot authorize another ID or Core owner',()=>{const {core,demo,inventory}=fixture();core.entries.find(e=>e.schemaId===overlay.schemaId).shapeFingerprints.push(...structuredClone(overlay.variants));assert.throws(()=>api.validateOwner(core,inventory,'core'),/Demo generated command overlay/);const {core:a,demo:b}=fixture();b.entries[0].shapeFingerprints.push(structuredClone(overlay.variants[0]));assert.throws(()=>api.verifyUnion(a,b));});
test('actual sourcePaths, symbol, generated evidence and authoritative mutations reject',()=>{for(const kind of ['source','symbol','evidence','authority']){const {demo,inventory}=fixture(),f=demo.entries.find(e=>e.schemaId===overlay.schemaId).shapeFingerprints.find(f=>f.hash===overlay.variants[0].hash);if(kind==='source')f.sourcePaths=['another/runtime.mjs'];if(kind==='symbol')f.symbols=['other'];if(kind==='evidence')f.evidence[0].completeness='complete';if(kind==='authority')f.authoritative=true;assert.throws(()=>api.validateOwner(demo,inventory,'demo'));}});
test('historical decision rationale, aliases lifecycle authority and releases remain immutable',()=>{for(const key of ['rationale','decision','release','authority','alias','lifecycle']){const {demo,inventory}=fixture(),e=inventory.entries.find(e=>e.schemaId===overlay.schemaId);if(key==='rationale')e.shapePolicy.rationale='reset';if(key==='decision')e.shapePolicy.decision='accept-all';if(key==='release')e.releasedFingerprintSetHash='sha256:'+'0'.repeat(64);if(key==='authority')e.shapePolicy.authoritativeFingerprints=['invented'];if(key==='alias')e.aliasOf='other';if(key==='lifecycle')e.lifecycle={status:'retired'};assert.throws(()=>api.validateOwner(demo,inventory,'demo'));}});
