'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),crypto=require('node:crypto'),{execFileSync,spawnSync}=require('node:child_process');
const root=path.resolve(__dirname,'../..'),sha=bytes=>crypto.createHash('sha256').update(bytes).digest('hex');
test('Core AppServices metadata names existing Core suites and retains required product evidence',()=>{
 const pkg=JSON.parse(fs.readFileSync(path.join(root,'package.json'))),m=pkg.xtend.maracaAppServices;
 assert.equal(m.catfoodSuite,undefined);assert.equal(m.suites.length,4);assert.equal(m.suiteIds.length,4);
 for(const file of m.suites){assert.equal(file.startsWith('tests/products/'),false);assert.equal(fs.existsSync(path.join(root,file)),true,file);}
 assert.ok(pkg.scripts[m.aggregatePackageScript.replace('npm run ','')]);
 const required=require('../../scripts/product-candidate-evidence.cjs').required;
 for(const id of ['xtend-llm-app-services-catfood','maraca-app-services-test-bench','shop-browser-fpm'])assert.ok(required.includes(id),id);
});
test('whole verification CLI binds its actual validated inputs and rejects changed evidence',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'xtend-verification-contract-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.mkdirSync(path.join(dir,'scripts'));
 for(const file of ['candidate-integrity.cjs','scripts/product-candidate-evidence.cjs'])fs.copyFileSync(path.join(root,file),path.join(dir,file));
 fs.mkdirSync(path.join(dir,'tools'),{recursive:true});fs.cpSync(path.join(root,'tools/schema-inventory'),path.join(dir,'tools/schema-inventory'),{recursive:true});
 const demoSha='2'.repeat(40);fs.writeFileSync(path.join(dir,'product-demos.lock.json'),JSON.stringify({demoSha}));
 const git=args=>execFileSync('git',args,{cwd:dir,encoding:'utf8'}).trim();git(['init','-q']);git(['add','.']);git(['-c','user.name=Fixture','-c','user.email=fixture@example.test','commit','-qm','verification fixture']);const coreSha=git(['rev-parse','HEAD']);
 const output=path.join(dir,'.xtend-test-results/product-candidates');fs.mkdirSync(path.join(output,'locks'),{recursive:true});fs.mkdirSync(path.join(output,'reports'));
 const packages=[{name:'@ccslabs/xtend',version:'0.9.0',file:'fixture.tgz',sha256:sha('candidate'),integrity:'sha512-'+crypto.createHash('sha512').update('candidate').digest('base64')}],php={file:'php.tar',sha256:sha('php'),sources:{'runtime.php':sha('source')}};
 fs.writeFileSync(path.join(output,'fixture.tgz'),'candidate');fs.writeFileSync(path.join(output,'php.tar'),'php');const manifest={schema:'xtend.product-candidates.v1',coreSha,demoSha,packages,php};fs.writeFileSync(path.join(output,'manifest.json'),JSON.stringify(manifest));
 const products=['.','products/maraca-app-services-test-bench','products/resumability-maraca-erp-demo','products/rmt-animation-testbench','products/rmt-maraca-kernel-orchestration','products/xtend-llm','products/xtend-material-workbench','products/xtend-shop'];
 const installation=products.map(product=>{const file='locks/'+(product==='.'?'root':product.split('/').at(-1))+'.json',bytes=JSON.stringify({packages:{'':{dependencies:{'@ccslabs/xtend':'0.9.0'}},'node_modules/@ccslabs/xtend':{version:'0.9.0',resolved:'file:.candidate/fixture.tgz',integrity:packages[0].integrity}}});fs.writeFileSync(path.join(output,file),bytes);return {product,file,status:'passed',lockSha256:sha(bytes)};});fs.writeFileSync(path.join(output,'installation.json'),JSON.stringify({results:installation}));
 const required=require('../../scripts/product-candidate-evidence.cjs').required,commands=required.map(id=>({id,status:'passed',exitCode:0,skips:[]})),reports=commands.map(c=>{const file='reports/'+c.id+'.json',bytes=JSON.stringify({schema:'xtend.product-suite-result.v1',coreSha,demoSha,...c});fs.writeFileSync(path.join(output,file),bytes);return {id:c.id,file,status:'passed',sha256:sha(bytes)};});const ledger=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(path.join(root,'tools/schema-inventory/ownership-ledger.json.gz')))),ids=require('../../tools/schema-inventory/selection.json'),bindings=require('../../tools/schema-inventory/authority-bindings.json');const rows=ids.map(schemaId=>({schemaId,hashes:ledger.entries.find(e=>e.schemaId===schemaId).shapePolicy.acceptedFingerprints.slice().sort()}));const ownerReport={selection:ids,coreSha,demoSha,packageSha256:packages[0].sha256,packageVersion:packages[0].version,ledgerSha256:'40a4e1d38dbf9e64a724d69178803768e6bff22c90c8260f5644916c24e127c8',selectionOk:true,migrationComplete:false,remainingOwnershipIds:24,generatedAt:new Date().toISOString(),core:rows,demo:rows,union:rows,authorities:bindings.map(b=>({...b,coreSha,packageSha256:packages[0].sha256,packageVersion:packages[0].version,importedSource:'imports/core/'+coreSha+'/'+b.oldSource}))};const ownerBytes=JSON.stringify(ownerReport),owner=reports.find(r=>r.id==='schema-ownership-100');fs.writeFileSync(path.join(output,owner.file),ownerBytes);owner.sha256=sha(ownerBytes);fs.writeFileSync(path.join(output,'reports.json'),JSON.stringify(reports));
 const filename=path.join(dir,'.xtend-test-results/product-candidate.json'),evidence={schema:'xtend.product-candidate-evidence.v1',ok:true,status:'passed',coreSha,demoSha,packages,php,installation,reports,commands,generatedAt:new Date().toISOString()};fs.writeFileSync(filename,JSON.stringify(evidence));
 const run=()=>spawnSync(process.execPath,['scripts/product-candidate-evidence.cjs'],{cwd:dir,encoding:'utf8',timeout:10000});let result=run();assert.equal(result.status,0,result.stderr);assert.deepEqual(JSON.parse(result.stdout),{schema:'xtend.product-candidate-verification.v1',ok:true,coreSha,demoSha,manifestSha256:sha(fs.readFileSync(path.join(output,'manifest.json'))),evidenceSha256:sha(fs.readFileSync(filename))});
 for(const patch of [{coreSha:'3'.repeat(40)},{generatedAt:'2000-01-01T00:00:00Z'},{php:{...php,sha256:'0'.repeat(64)}},{commands:commands.slice(1)}]){fs.writeFileSync(filename,JSON.stringify({...evidence,...patch}));result=run();assert.notEqual(result.status,0);assert.equal(result.stdout.trim(),'');}
});
