'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),helper=require('../utils/test-catalog');
const workflow = shell => 'jobs:\n  required:\n    steps:\n      - name: Execute required gate\n        run: |\n' + shell.split('\n').map(line=>'          '+line).join('\n');
const has = (shell, command) => helper.workflowHasCommand(workflow(shell), command);
test('actual nightly workflow executes every declared npm and direct command obligation',()=>{const p=require('../../package.json');function walk(x){if(x&&typeof x==='object'){if(x.schema==='xtend.ci.nightly-build.v1'){let text=fs.readFileSync(path.join(root,x.workflow),'utf8');text=text.slice(0,text.indexOf('\n  optional-source-to-sea:'));for(const c of x.commandSet)assert.equal(helper.workflowHasCommand(text,c),true,c);}Object.values(x).forEach(walk);}}walk(p);});
test('missing and substituted direct commands cannot satisfy an obligation',()=>{for(const c of ['npm pack --workspace xtendrmt --dry-run --json --silent','node scripts/product-candidate-canary.cjs']){assert.equal(has(c+' > report.json',c),true);assert.equal(has('',c),false);assert.equal(has(c.replace('xtendrmt','foreign').replace('product-candidate-canary','wrong'),c),false);}assert.equal(has('echo node scripts/product-candidate-canary.cjs','node scripts/product-candidate-canary.cjs'),false);});

test('nonexecuting or execution-changing modifiers never satisfy required commands',()=>{for(const c of ['node scripts/product-candidate-canary.cjs','npm run test:ci-nightly'])for(const suffix of [' --help',' --pack-only',' --version',' || true',' | cat'])assert.equal(has(c+suffix,c),false,c+suffix);});
test('commented commands and heredoc bodies are not executions',()=>{const c='node scripts/product-candidate-canary.cjs';for(const text of ['# '+c,'  # '+c,"cat <<'EOF'\n"+c+'\nEOF','cat <<-END\n'+c+'\nEND'])assert.equal(has(text,c),false,text);assert.equal(has("cat <<'EOF'\nignored\nEOF\n"+c,c),true);});

test('env and multiline name text cannot provide execution evidence',()=>{const c='node scripts/product-candidate-canary.cjs';for(const metadata of ['env:\n  NOTE: |\n    '+c,'jobs:\n  required:\n    steps:\n      - name: |\n          '+c+'\n        run: echo other','jobs:\n  required:\n    steps:\n      - env:\n          NOTE: |\n            '+c+'\n        run: echo other'])assert.equal(helper.workflowHasCommand(metadata,c),false);assert.equal(helper.workflowHasCommand('jobs:\n  required:\n    steps:\n      - run: '+c,c),true);});
