'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const api=require('../../tools/schema-inventory/index.cjs'),ledger=JSON.parse(require('node:zlib').gunzipSync(require('node:fs').readFileSync(require('node:path').join(__dirname,'../../tools/schema-inventory/ownership-ledger.json.gz')))),ids=require('../../tools/schema-inventory/selection.json');
// Controlled validator fixtures, NOT a current product/source conservation proof.
function scans(){const entries=ids.map(id=>structuredClone(ledger.entries.find(e=>e.schemaId===id)));return [{entries:structuredClone(entries)},{entries:structuredClone(entries)}];}
test('exact 100 selection and immutable-ledger union controlled fixture',()=>{api.assertSelection(ids);assert.equal(api.verifyUnion(...scans()).length,100);});
test('selection omission, addition and reordering reject',()=>{for(const selected of [ids.slice(1),[...ids,'unknown'],ids.slice().reverse()])assert.throws(()=>api.assertSelection(selected),/Exact reviewed/);});
test('union missing, extra and same-hash changed normalized shape reject',()=>{for(const mutation of ['missing','extra','changed']){const [a,b]=scans();if(mutation==='missing'){a.entries[0].shapeFingerprints=[];b.entries[0].shapeFingerprints=[];}if(mutation==='extra')a.entries[0].shapeFingerprints.push({hash:'sha256:'+'0'.repeat(64),shape:{}});if(mutation==='changed')a.entries[0].shapeFingerprints[0].shape={changed:true};assert.throws(()=>api.verifyUnion(a,b),/union mismatch|normalized shape/);}});
test('local accepted, release, alias, lifecycle and policy mutations reject',()=>{const [scan]=scans(),base={selection:ids,entries:structuredClone(scan.entries)};for(const mutation of ['accepted','release','alias','lifecycle','rationale','authority','usage','canonical','role','interface']){const doc=structuredClone(base),e=doc.entries[0];if(mutation==='usage')e.usages[0].sourcePaths[0]='mutated-real-source.ts';if(mutation==='role')e.usages[0].role='mutated-role';if(mutation==='interface')e.usages[0].interfaceReferences[0].path='mutated-interface.ts';if(mutation==='canonical')e.canonicalDefinition={path:'other',symbol:'other'};if(mutation==='accepted')e.shapePolicy.acceptedFingerprints=[];if(mutation==='release')e.releasedFingerprintSetHash=null;if(mutation==='alias')e.aliasOf='other';if(mutation==='lifecycle')e.lifecycle={status:'retired'};if(mutation==='rationale')e.shapePolicy.rationale='replacement';if(mutation==='authority')e.shapePolicy.authoritativeFingerprints=[];assert.throws(()=>api.validateOwner(scan,doc,'controlled'),/accepted set|Historical|authority|usage\/source binding|canonical binding/);}});
test('public parser rejects wrong TypeScript version and exposes no baseline writer',()=>{assert.throws(()=>api.createScanner({typescript:{version:'5.9.2'}}),/5.9.3/);const scanner=api.createScanner({typescript:require('typescript')});assert.equal(scanner.acceptBaseline,undefined);assert.equal(scanner.writeInventory,undefined);});

test('selected historical duplicate and consolidation removal, rationale mutation and addition reject',()=>{assert.ok(api.verifySelectedGovernance(ledger));for(const key of ['duplicateReviews','consolidations'])for(const mutation of ['remove','rationale','add']){const doc=structuredClone(ledger),row=doc[key].find(r=>(r.schemaIds||[]).some(id=>ids.includes(id)));assert.ok(row);if(mutation==='remove')doc[key]=doc[key].filter(r=>r!==row);if(mutation==='rationale')row.rationale='changed history';if(mutation==='add')doc[key].push({...row,[key==='duplicateReviews'?'reviewId':'consolidationId']:'new-record'});assert.throws(()=>api.verifySelectedGovernance(doc),new RegExp(key));}});
