'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os');
const root=path.resolve(__dirname,'../..'),api=require('../../catalog/type-exports');
const helpers=['./product-support','./test-support/browser-hypervisor','./test-support/php-fpm','./test-support/dev-server','./laravel-package','./candidate-integrity','./schema-inventory'];
const manifest=()=>JSON.parse(fs.readFileSync(path.join(root,'package.json'),'utf8'));
function result(mutate=()=>{}){const pkg=manifest();mutate(pkg);return api.validateTypeExportsPlan(api.createTypeExportsPlan({rootDir:root,packageManifest:pkg}));}
test('exact207 keys and fingerprint classify only the seven existing public helpers',()=>{const pkg=manifest(),plan=api.createTypeExportsPlan({rootDir:root,packageManifest:pkg});assert.deepEqual(result().errors,[]);assert.equal(Object.keys(pkg.exports).length,207);assert.equal(api.TYPE_EXPORTS_LOCKED_EXPORT_COUNT,207);assert.equal(api.TYPE_EXPORTS_LOCKED_EXPORT_FINGERPRINT,'c2224955e47635f60bb9f69dd673b5753d18d2229d6091334f412887ae95db11');assert.equal(api.createExportFingerprint(Object.keys(pkg.exports)),api.TYPE_EXPORTS_LOCKED_EXPORT_FINGERPRINT);assert.deepEqual(plan.classificationGroups.find(g=>g.id==='public-migration-helpers').exports,helpers);for(const key of helpers){const c=plan.classifications.find(c=>c.exportKey===key);assert.equal(c.typeDecision,'declaration-ready');assert.equal(c.group,'public-migration-helpers');}});
test('unreviewed export is rejected without a catch-all classification',()=>{const r=result(p=>p.exports['./unreviewed-helper']='./api.js');assert.equal(r.ok,false);assert.ok(r.errors.some(e=>e.includes('unexpected package exports')));});
test('same-count substitution still rejects missing and unreviewed keys',()=>{const r=result(p=>{delete p.exports['./schema-inventory'];p.exports['./unreviewed-helper']='./api.js';});assert.equal(r.ok,false);assert.ok(r.errors.some(e=>e.includes('missing package exports')));assert.ok(r.errors.some(e=>e.includes('unexpected package exports')));});
test('each helper rejects a same-key wrong runtime target even if another target exists',()=>{for(const key of helpers){const r=result(p=>{const v=p.exports[key];if(typeof v==='string')p.exports[key]='./api.js';else v.default='./api.js';});assert.equal(r.ok,false,key);assert.ok(r.errors.some(e=>e.includes(key)&&e.includes('exact reviewed public helper target/type contract')),key);}});
test('each helper rejects a foreign existing types target',()=>{for(const key of helpers){const r=result(p=>{const v=p.exports[key];p.exports[key]=typeof v==='string'?{types:'./api.d.ts',default:v}:{...v,types:'./api.d.ts'};});assert.equal(r.ok,false,key);assert.ok(r.errors.some(e=>e.includes(key)&&e.includes('exact reviewed public helper')),key);}});
test('stale metadata fingerprint and count cannot self-confirm the current contract',()=>{for(const mutate of [p=>p.xtend.typeExports.lockedExportFingerprint='9d06399910cc18b7be2473db3108e0d09a1561a4672b3bbf69bd2b10d96367f1',p=>p.xtend.typeExports.expectedExportCount=206])assert.equal(result(mutate).ok,false);});
test('ordered key fingerprint rejects reorder with the same keys and count',()=>{const r=result(p=>p.exports=Object.fromEntries(Object.entries(p.exports).reverse()));assert.equal(r.ok,false);assert.ok(r.errors.some(e=>e.includes('package export lock fingerprint changed')));});
test('public helper declarations compile and wrong known argument types fail',t=>{const ts=require('typescript'),dir=fs.mkdtempSync(path.join(os.tmpdir(),'helper-types-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const moduleRoot=path.join(dir,'node_modules','@ccslabs');fs.mkdirSync(moduleRoot,{recursive:true});fs.symlinkSync(root,path.join(moduleRoot,'xtend'),'dir');const imports=[['php-fpm','startFpmProxy','tools/browser-hypervisor/php-fpm'],['laravel-package','buildLaravelPackage','scripts/build_laravel_package'],['dev-server','listenXtendDevServer','scripts/serve_xtend_dev'],['browser-hypervisor','createCapabilities, createEvidence','tools/browser-hypervisor/index']].map(([name,symbol,file])=>`import {${symbol}} from ${JSON.stringify('@ccslabs/xtend/'+(name==='dev-server'?'test-support/dev-server':name==='php-fpm'?'test-support/php-fpm':name==='browser-hypervisor'?'test-support/browser-hypervisor':name))};`).join('\n')+'\n'+['product-support','candidate-integrity','schema-inventory'].map((key,index)=>`import * as publicHelper${index} from ${JSON.stringify('@ccslabs/xtend/'+key)};`).join('\n');const options={strict:true,noEmit:true,skipLibCheck:false,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.NodeNext,moduleResolution:ts.ModuleResolutionKind.NodeNext,types:['node'],typeRoots:[path.resolve(path.dirname(require.resolve('@types/node/package.json')),'..')]};function compile(body){const file=path.join(dir,'consumer.ts');fs.writeFileSync(file,imports+'\n'+body);return ts.getPreEmitDiagnostics(ts.createProgram([file],options));}const valid="void startFpmProxy({binary:'php-fpm',fixture:'fixture'});void buildLaravelPackage({output:'out',archiveTool:'tar'});void listenXtendDevServer({port:0});void createCapabilities({engine:'chromium',width:1280});";assert.deepEqual(compile(valid).map(d=>ts.flattenDiagnosticMessageText(d.messageText,'\n')),[]);for(const bad of ["void startFpmProxy({binary:3,fixture:'fixture'});","void buildLaravelPackage({output:3});","void listenXtendDevServer({port:'bad'});","void createCapabilities({width:'bad'});","void createEvidence({runId:3});","void createEvidence({harnessSha256:3});","void createEvidence({status:3});","void createCapabilities({preloadScript:3});","void createCapabilities({scripts:[{script:3}]});","void createCapabilities({scripts:[{script:'return 1',waitFor:3}]});","void createCapabilities({scripts:[{script:'return 1',args:3}]});"])assert.ok(compile(bad).some(d=>d.code===2322),bad);});
