'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const {execFileSync}=require('node:child_process');
const {createHash,createPublicKey,verify}=require('node:crypto');
const root=path.resolve(__dirname,'..');
async function runContracts({php=false}={}){
 const checks=[],failures=[];const check=async(name,run)=>{try{await run();checks.push(name);}catch(error){failures.push({name,message:error.message});}};
 const {createRmtCompilationSession}=require('@ccslabs/xtend/rmt-language/compilation-session');
 const {createPortableRenderArtifact,projectPortableRender}=await import('@ccslabs/xtend/rmt/portable-render');
 const {canonicalizeRmtResumePayload,unsignedEnvelope}=await import(require('node:url').pathToFileURL(path.join(path.dirname(require.resolve('@ccslabs/xtend/package.json')),'xtendrmt/rmt-resume-protocol.js')));
 if(!php){
  await check('public page, remote surface and capture types compile in the installed package',()=>{const ts=require('typescript');const program=ts.createProgram([path.join(__dirname,'types.ts')],{noEmit:true,strict:true,target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.ESNext,moduleResolution:ts.ModuleResolutionKind.Bundler});const errors=ts.getPreEmitDiagnostics(program);assert.equal(errors.length,0,errors.map(error=>ts.flattenDiagnosticMessageText(error.messageText,'\n')).join('\n'));});
  await check('superseded Maraca boot releases its controller and cannot overwrite a newer page',async()=>{
   const {createMaracaPageClient}=await import('@ccslabs/xtend/maraca/page-client');
   const {PAGE_RESPONSE_SCHEMA}=await import('@ccslabs/xtend/rmt/page-contract');
   const artifact=createPortableRenderArtifact({descriptor:{type:'text',text:'$model.value'}},{inputs:['value'],defaults:{value:0}});
   const page=(name,value)=>({schema:PAGE_RESPONSE_SCHEMA,kind:'page',version:'1',contextKey:'guest',page:name,url:'/'+name,props:{value},shared:{},head:[],errors:{},flash:{},deferred:{},merge:{},once:{},partial:false,layout:null,renderArtifact:artifact,maraca:{entry:'/'+name+'.mjs'}});
   const disposed=[],created=[];let release,entered;const blocked=new Promise(resolve=>{release=resolve;}),booting=new Promise(resolve=>{entered=resolve;});
   const win={location:{origin:'http://store.test'},addEventListener(){},removeEventListener(){},scrollTo(){}};
   const client=createMaracaPageClient({initialPage:page('initial',0),root:{focus(){}},window:win,fetch:async url=>Response.json(page(new URL(url).pathname.slice(1),2)),loadBundle:async url=>({createXtendMaraca(){const name=new URL(url).pathname;created.push(name);return {facade:{name},async boot(){if(name==='/old.mjs'){entered();await blocked;}return {ok:true};},dispose(){disposed.push(name);}};}})});
   await client.start();const old=client.visit('/old');await booting;const current=client.visit('/current');release();await Promise.all([old,current]);
   assert.equal(client.page.page,'current');assert.equal(client.getRuntime().name,'/current.mjs');assert.deepEqual(disposed,['/initial.mjs','/old.mjs']);client.dispose();assert.deepEqual(disposed,created);
  });
  await check('catalog has 36 unique products, 72 SKUs and local dimensioned images',()=>{const data=JSON.parse(fs.readFileSync(path.join(root,'database/catalog.json')));assert.equal(data.length,36);assert.equal(new Set(data.map(p=>p.slug)).size,36);const variants=data.flatMap(p=>p.variants);assert.equal(new Set(variants.map(v=>v.sku)).size,72);assert(variants.some(v=>v.stock===0));for(const v of variants){assert(Number.isSafeInteger(v.price)&&v.price>0);assert.match(fs.readFileSync(path.join(root,'public',v.image),'utf8'),/width="720" height="640"/);}});
  await check('Maraca and portable views reuse current compiler facts and native controls',()=>{const session=createRmtCompilationSession({root});const input={text:fs.readFileSync(path.join(root,'src/app.rmt'),'utf8'),filePath:path.join(root,'src/app.rmt')};const first=session.compileSource(input),second=session.compileSource(input,{documentId:'src/app.rmt'});assert.equal(first.ok,true,JSON.stringify(first.diagnostics));assert.equal(first,second);assert.deepEqual(session.snapshot(),{compilations:1,hits:1,documents:1});const artifact=createPortableRenderArtifact(first);const projection=projectPortableRender(artifact);assert.match(JSON.stringify(projection.descriptor),/data-xtend-component/);assert(first.orchestrationArtifacts.events.some(e=>e.target==='.cart-line-form'&&e.closest==='.cart-line-form'));session.compileSource({...input,text:input.text+'\n// changed'});assert.equal(session.snapshot().compilations,2);});
 }else{
  const probe=data=>JSON.parse(execFileSync(process.env.XTEND_PHP_BINARY||'php',[path.join(__dirname,'framework.php')],{input:JSON.stringify(data),encoding:'utf8',timeout:10000}));
  await check('PHP signatures preserve dynamic objects, lists, UTF-16 key order and JS numbers',()=>{const state={catalog:{z:'last',a:'first',empty:{},items:[],nested:[{z:2,a:1}]},numbers:[0,-0,1e-7,1e-6,1.2345e-6,1e20,1e21,3.141592653589793,1000000000000000100],unicode:{'\uE000':'bmp','😀':'astral','separator':'\u2028\u2029'}};const result=probe({operation:'resume',stateJson:JSON.stringify(state)});assert.equal(result.result.ok,true);const envelope=result.result.response.resume;const canonical=canonicalizeRmtResumePayload(unsignedEnvelope(envelope));assert.equal(envelope.integrity.digest,createHash('sha256').update(canonical).digest('base64url'));assert(verify('sha256',Buffer.from(canonical),{key:createPublicKey({key:result.publicKey,format:'jwk'}),dsaEncoding:'ieee-p1363'},Buffer.from(envelope.integrity.signature,'base64url')));assert.deepEqual(envelope.snapshot.state,JSON.parse(JSON.stringify(state)));});
  await check('RMT input policies have matching PHP and JavaScript verdicts before handlers',async()=>{const {applyAppServiceInputPolicy}=await import('@ccslabs/xtend/maraca/app-services');const policy={schema:'xtend.maraca.app-service-input-policy.v1',fields:[{name:'text',type:'string',boundary:'xtend.security.sanitizing-boundary.v1',sanitize:'text'}]};for(const input of [{text:'Mara\r\nMuster'},{text:'<safe text>'},{text:'\u0000bad'},{text:42},{}]){let js;try{js=applyAppServiceInputPolicy(input,{serviceId:'test.policy',phase:'server',policy});}catch(error){js={verdict:error.details.verdict};}const base={schema:'xtend.maraca.app-services-manifest.v1',targets:['php'],services:[{id:'test.policy',kind:'command',target:'server',mode:'invoke',concurrency:'serial',implementations:{browser:true,node:false,php:true},inputPolicy:policy}]};const manifest={...base,fingerprint:createHash('sha256').update(canonicalizeRmtResumePayload(base)).digest('hex')};const result=probe({operation:'policy',input,policy,manifest});assert.deepEqual(result.verdict,js.verdict);assert.equal(result.called,js.verdict.ok);if(result.ok)assert.deepEqual(result.value,js.input);}});
  await check('PHP remote fragments reject foreign targets, preserve failures and terminate once',()=>{for(const scenario of ['success','outside','throw','timeout','cleanup','slow-cleanup','observer']){const result=probe({operation:'fragments',scenario});assert.equal(result.closed,1);assert.equal(result.frames.filter(f=>['complete','error','cancelled'].includes(f.type)).length,1);assert.equal(result.frames.at(-1).type,scenario==='success'?'complete':'error');assert(!JSON.stringify(result.frames).includes('private'));}});
 }
 return {ok:!failures.length,checks,failures};
}
module.exports={runContracts};
