<?php
declare(strict_types=1);
$root=dirname(__DIR__);require $root.'/vendor/autoload.php';$app=require $root.'/bootstrap/app.php';
$app->make(Illuminate\Contracts\Console\Kernel::class)->bootstrap();
config(['database.connections.sqlite.database'=>':memory:','shop.payment_secret'=>str_repeat('test-secret-',8)]);
Illuminate\Support\Facades\DB::purge('sqlite');app(App\Domain\StoreDatabase::class)->install();
$checks=[];$failures=[];
function ensure(bool $value,string $message='Assertion failed'):void{if(!$value)throw new RuntimeException($message);}
function check(string $name,callable $run):void{global $checks,$failures;try{$run();$checks[]=$name;}catch(Throwable $error){$failures[]=['name'=>$name,'error'=>get_class($error),'message'=>$error->getMessage()];}}
function rejects(callable $run,int $status):void{try{$run();}catch(Symfony\Component\HttpKernel\Exception\HttpExceptionInterface $error){ensure($error->getStatusCode()===$status);return;}throw new RuntimeException('Expected HTTP '.$status);}
function guest():Illuminate\Http\Request{$r=Illuminate\Http\Request::create('/');$session=new Illuminate\Session\Store('test',new Illuminate\Session\ArraySessionHandler(120));$session->start();$r->setLaravelSession($session);return $r;}
function cartAdd($r,string $sku='TEC-01-1',int $quantity=1):array{$cart=app(App\Cart::class);return $cart->change($r,['sku'=>$sku,'quantity'=>$quantity,'version'=>$cart->read($r)['version']],'add');}
function address():array{return ['email'=>'mara@example.test','name'=>'Mara Muster','street'=>'Demostraße 12','postal'=>'10115','city'=>'Berlin','country'=>'DE','shipping'=>'standard'];}
function attempt($r,string $scenario='success'):array{$checkout=app(App\Domain\Checkout::class);$checkout->save($r,address());return $checkout->attempt($r,['version'=>app(App\Cart::class)->read($r)['version'],'scenario'=>$scenario]);}
function proof(array $attempt):string{$signer=new XtendStore\Payment\PaymentProof(config('shop.payment_secret'));$claims=$signer->verify($attempt['capability'],'authorize');$claims['purpose']='authorized';return $signer->sign($claims);}
check('36 products and 72 independently priced and stocked variants',function(){ensure(Illuminate\Support\Facades\DB::table('products')->count()===36);ensure(Illuminate\Support\Facades\DB::table('variants')->count()===72);});
check('additive installation does not reset existing stock',function(){Illuminate\Support\Facades\DB::table('variants')->where('sku','TEC-02-1')->update(['stock'=>2]);app(App\Domain\StoreDatabase::class)->install();ensure(app(App\Domain\Catalog::class)->variant('TEC-02-1')['stock']===2);});
check('guest carts are isolated and optimistic revisions reject stale tabs',function(){$a=guest();$b=guest();$one=cartAdd($a);ensure($one['count']===1&&app(App\Cart::class)->read($b)['empty']);rejects(fn()=>app(App\Cart::class)->change($a,['version'=>0],'clear'),409);ensure(app(App\Cart::class)->read($a)['count']===1);});
check('shipping and authoritative prices use integer cents',function(){$r=guest();$cart=cartAdd($r,'WOH-01-1');ensure($cart['subtotal']===3990&&$cart['shipping']===490&&$cart['total']===4480);ensure(app(App\Cart::class)->read($r,'express')['shipping']===990);$cart=cartAdd($r,'TEC-01-1');ensure($cart['shipping']===0);});
check('quantity limits and stock prevent invalid mutations',function(){$r=guest();rejects(fn()=>cartAdd($r,'TEC-02-1',3),422);ensure(app(App\Cart::class)->read($r)['empty']);});
check('server validation returns nested field errors without saving an invalid draft',function(){$r=guest();try{app(App\Domain\Checkout::class)->save($r,array_replace(address(),['email'=>'bad','postal'=>'abcde']));throw new RuntimeException('Validation accepted');}catch(Illuminate\Validation\ValidationException $error){ensure(isset($error->errors()['email'],$error->errors()['postal']));}ensure(app(App\Domain\Checkout::class)->draft($r)['email']==='');});
check('successful authorization stores stock and order atomically and retry is idempotent',function(){$r=guest();cartAdd($r);$before=app(App\Domain\Catalog::class)->variant('TEC-01-1')['stock'];$attempt=attempt($r);$proof=proof($attempt);$checkout=app(App\Domain\Checkout::class);$order=$checkout->complete($r,$proof);ensure($checkout->complete($r,$proof)===$order);ensure(app(App\Domain\Catalog::class)->variant('TEC-01-1')['stock']===$before-1);ensure(app(App\Cart::class)->read($r)['empty']);ensure($checkout->order($r,$order['id'])['totalText']===App\Domain\Catalog::money(8900));rejects(fn()=>$checkout->order(guest(),$order['id']),404);});
check('wrong session, tampered proof and changed cart cannot complete payment',function(){$r=guest();cartAdd($r);$attempt=attempt($r);$checkout=app(App\Domain\Checkout::class);rejects(fn()=>$checkout->complete(guest(),proof($attempt)),404);rejects(fn()=>$checkout->complete($r,proof($attempt).'broken'),422);cartAdd($r);rejects(fn()=>$checkout->complete($r,proof($attempt)),409);});
check('amount, currency and version are bound to the attempt',function(){$r=guest();cartAdd($r);$attempt=attempt($r);$signer=new XtendStore\Payment\PaymentProof(config('shop.payment_secret'));$claims=$signer->verify($attempt['capability'],'authorize');foreach(['amount'=>1,'currency'=>'USD','version'=>99] as $key=>$value){$bad=array_replace($claims,['purpose'=>'authorized',$key=>$value]);rejects(fn()=>app(App\Domain\Checkout::class)->complete($r,$signer->sign($bad)),422);}});
check('cancelled, declined and expired attempts never create an order',function(){foreach(['cancel','declined','expired'] as $scenario){$r=guest();cartAdd($r);$attempt=attempt($r,$scenario==='declined'?'declined':'success');if($scenario==='cancel')app(App\Domain\Checkout::class)->cancel($r,$attempt['id']);if($scenario==='expired')Illuminate\Support\Facades\DB::table('payment_attempts')->where('id',$attempt['id'])->update(['expires_at'=>time()-1]);rejects(fn()=>app(App\Domain\Checkout::class)->complete($r,proof($attempt)),409);ensure(!app(App\Cart::class)->read($r)['empty']);}});
check('failed stock transaction leaves no partial order or cart reset',function(){$r=guest();cartAdd($r);$attempt=attempt($r);$orders=Illuminate\Support\Facades\DB::table('orders')->count();$stock=app(App\Domain\Catalog::class)->variant('TEC-01-1')['stock'];Illuminate\Support\Facades\DB::table('variants')->where('sku','TEC-01-1')->update(['stock'=>0]);rejects(fn()=>app(App\Domain\Checkout::class)->complete($r,proof($attempt)),409);ensure(Illuminate\Support\Facades\DB::table('orders')->count()===$orders);ensure(!app(App\Cart::class)->read($r)['empty']);Illuminate\Support\Facades\DB::table('variants')->where('sku','TEC-01-1')->update(['stock'=>$stock]);});
echo json_encode(['ok'=>!$failures,'checks'=>$checks,'failures'=>$failures,'runtime'=>['php'=>PHP_VERSION,'laravel'=>Illuminate\Foundation\Application::VERSION,'peakMemoryBytes'=>memory_get_peak_usage(true)]],JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT|JSON_THROW_ON_ERROR)."\n";exit($failures?1:0);
