const fs=require('node:fs'),path=require('node:path'),os=require('node:os'),test=require('node:test'),assert=require('node:assert/strict');const root=require('./harness.cjs').root,p=__dirname,proposed=require('./harness.cjs').load(),current=require('./harness.cjs').load(false,true),scan=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(p+'/observed-source.json.gz'))),base=JSON.parse(fs.readFileSync(root+'/tests/schemas/xtend-schema-inventory.json')),id=['xtend','product-candidates','v1'].join('.'),binding=JSON.parse(require('node:zlib').gunzipSync(fs.readFileSync(p+'/binding.json.gz')));const canonical={path:binding.canonicalPath,symbol:binding.canonicalSymbol,definitionType:'typescript-declaration',role:'definition',visibility:'internal'};
const observed=scan.entries.find(e=>e.schemaId===id);const diagnosticScan=structuredClone(scan);diagnosticScan.entries.find(e=>e.schemaId===id).canonicalDefinition=canonical;const entry=structuredClone(observed);entry.canonicalDefinition=canonical;entry.status='active';entry.lifecycle={status:'active',rollout:'planned'};entry.releasedFingerprintSetHash=null;entry.shapePolicy={...entry.shapePolicy,mode:'polymorphic',acceptedFingerprints:entry.shapeFingerprints.map(f=>f.hash),releasedFingerprintSetHash:null,decision:'CONTROLLED-model-test-only-not-governance-approval',rationale:'Controlled reviewed-binding fixture, NOT an approved registration.'};entry.initialAuthorityReview={status:'reviewed-unreleased',schemaId:id,sourcePath:binding.canonicalPath,symbol:binding.canonicalSymbol,sourceSha256:binding.sourceSha256,authoritativeFingerprint:binding.authority,released:false};const doc=structuredClone(base);doc.entries=doc.entries.filter(e=>e.schemaId!==id);doc.entries.push(entry);doc.entries.sort((a,b)=>a.schemaId.localeCompare(b.schemaId));doc.schemaFamilies=doc.schemaFamilies.filter(f=>f.activeSchemaId!==id);doc.schemaFamilies.push({familyId:entry.familyId,currentVersion:1,activeSchemaId:id,tombstones:[],versions:[{schemaId:id,version:1,lifecycle:entry.lifecycle,releasedFingerprintSetHash:null}]});doc.schemaFamilies.sort((a,b)=>a.familyId.localeCompare(b.familyId));const get=d=>d.entries.find(e=>e.schemaId===id);const errors=(module,d=doc,s=diagnosticScan,rootDir=root)=>module.validateInventoryDocument(d,s,{rootDir}).errors;const drift=e=>e.some(e=>e.schemaId===id&&e.code==='released-fingerprint-drift');
test('one controlled initial binding can retain null releasehash; unchanged validator rejects it',()=>{assert.equal(drift(errors(proposed)),false);assert.equal(drift(errors(current)),true);assert.equal(get(doc).releasedFingerprintSetHash,null);assert.equal(get(doc).shapePolicy.releasedFingerprintSetHash,null);assert.equal(doc.schemaFamilies.find(f=>f.activeSchemaId===id).versions[0].releasedFingerprintSetHash,null);});
test('sixteen invalid initial-manifest bindings reject through existing released-drift gate',()=>{const rows=[];for(const mutation of ['missing-review','wrong-path','wrong-symbol','wrong-digest','wrong-authority','wrong-canonical','rollout-complete','not-active','alias','replacement','history','release-record','tombstone','other-family-version','missing-family','invented-entry-release']){const d=structuredClone(doc),e=get(d),family=d.schemaFamilies.find(f=>f.activeSchemaId===id);if(mutation==='missing-review')delete e.initialAuthorityReview;if(mutation==='wrong-path')e.initialAuthorityReview.sourcePath='other.d.ts';if(mutation==='wrong-symbol')e.initialAuthorityReview.symbol='Other';if(mutation==='wrong-digest')e.initialAuthorityReview.sourceSha256='0'.repeat(64);if(mutation==='wrong-authority')e.initialAuthorityReview.authoritativeFingerprint='sha256:'+'0'.repeat(64);if(mutation==='wrong-canonical')e.canonicalDefinition.path='candidate-integrity.cjs';if(mutation==='rollout-complete')e.lifecycle.rollout='complete';if(mutation==='not-active')e.lifecycle.status='retired';if(mutation==='alias')e.aliasOf=['xtend','a11y','profile','v1'].join('.');if(mutation==='replacement')e.replacedBy='other.v2';if(mutation==='history')e.history=[{release:'previous'}];if(mutation==='release-record')d.releaseRecords=[{schemaId:id,version:1}];if(mutation==='tombstone')family.tombstones=[{schemaId:id,version:1,rationale:'Prior retired version'}];if(mutation==='other-family-version')family.versions.push({...family.versions[0],schemaId:['xtend','product-candidates','v2'].join('.'),version:2});if(mutation==='missing-family')d.schemaFamilies=d.schemaFamilies.filter(f=>f!==family);if(mutation==='invented-entry-release')e.releasedFingerprintSetHash=e.shapePolicy.releasedFingerprintSetHash='sha256:'+'0'.repeat(64);assert.equal(drift(errors(proposed,d)),true,mutation);rows.push(mutation);}});
test('other new IDs cannot use this exception',()=>{const d=structuredClone(doc),e=get(d),s=structuredClone(diagnosticScan);const other=['xtend','other-candidates','v1'].join('.');e.schemaId=other;e.familyId=['xtend','other-candidates'].join('.');const family=d.schemaFamilies.find(f=>f.activeSchemaId===id);family.familyId=e.familyId;family.activeSchemaId=other;family.versions[0].schemaId=other;s.entries.find(e=>e.schemaId===id).schemaId=other;assert.ok(errors(proposed,d,s).some(e=>e.schemaId===other&&e.code==='released-fingerprint-drift'));});
test('old released contracts reject null reset and authority-set drift under both validators',()=>{const old=base.entries.find(e=>e.releasedFingerprintSetHash&&e.shapeFingerprints.some(f=>f.authoritative)&&e.lifecycle.status==='active'&&!e.aliasOf);assert.ok(old);const rows=[];for(const mutation of ['null-reset','changed-authority-set']){const d=structuredClone(base),e=d.entries.find(e=>e.schemaId===old.schemaId);if(mutation==='null-reset')e.releasedFingerprintSetHash=e.shapePolicy.releasedFingerprintSetHash=null;else{const f=e.shapeFingerprints.find(f=>f.authoritative);f.hash='sha256:'+'0'.repeat(64);e.shapePolicy.authoritativeFingerprints=e.shapeFingerprints.filter(f=>f.authoritative).map(f=>f.hash);}for(const m of [current,proposed])assert.ok(errors(m,d,scan).some(error=>error.schemaId===old.schemaId&&error.code==='released-fingerprint-drift'));rows.push({schemaId:old.schemaId,mutation,bothValidatorsReject:true});}});
test('actual declaration byte change cannot retain the initial exception',t=>{const dir=fs.mkdtempSync(path.join(os.tmpdir(),'authority-source-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));fs.writeFileSync(path.join(dir,'candidate-integrity.d.ts'),fs.readFileSync(root+'/candidate-integrity.d.ts')+'\n// changed\n');assert.equal(drift(errors(proposed,doc,diagnosticScan,dir)),true);});

test('normal released Manifest never uses initial bypass; first release requires source retirement',()=>{const d=structuredClone(doc),e=get(d),family=d.schemaFamilies.find(f=>f.activeSchemaId===id),released=proposed.authoritativeFingerprintSetHash(e.shapeFingerprints);e.releasedFingerprintSetHash=e.shapePolicy.releasedFingerprintSetHash=released;family.versions[0].releasedFingerprintSetHash=released;assert.equal(proposed.__testInitialAuthority(e,d,diagnosticScan,root),false);assert.throws(()=>proposed.assertCandidateInitialAuthorityRetiredForRelease(),/source-level/);const retired=require('./harness.cjs').load(true);assert.equal(retired.assertCandidateInitialAuthorityRetiredForRelease(),true);assert.equal(retired.__testInitialAuthority(e,d,diagnosticScan,root),false);});
test('after source retirement deleting ALL manifest release/history metadata cannot revive initial bypass',()=>{const retired=require('./harness.cjs').load(true);const reset=structuredClone(doc);assert.equal(retired.__testInitialAuthority(get(reset),reset,diagnosticScan,root),false);assert.equal(drift(errors(retired,reset)),true);assert.equal(get(reset).releasedFingerprintSetHash,null);assert.equal(get(reset).shapePolicy.releasedFingerprintSetHash,null);assert.equal(reset.schemaFamilies.find(f=>f.activeSchemaId===id).versions[0].releasedFingerprintSetHash,null);});


test('legitimate current CandidateManifest declaration remains authoritative and observed',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'productive-candidate-declaration-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const source=fs.readFileSync(root+'/candidate-integrity.d.ts');fs.writeFileSync(path.join(dir,'candidate-integrity.d.ts'),source);
 const result=current.scanSchemaInventory({rootDir:dir}),observed=result.entries.find(e=>e.schemaId===id);
 assert.ok(observed);assert.equal(observed.canonicalDefinition.path,'candidate-integrity.d.ts');assert.equal(observed.canonicalDefinition.symbol,'CandidateManifest');
 assert.ok(observed.shapeFingerprints.some(f=>f.authoritative&&f.sourcePaths.includes('candidate-integrity.d.ts')));
 assert.deepEqual(fs.readFileSync(path.join(dir,'candidate-integrity.d.ts')),source);
});
