'use strict';
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const policy = require('../security/html-sanitizer-policy').createHtmlSanitizer.toString();
const upstream = fs.readFileSync(require.resolve('dompurify'), 'utf8').replace(/\/\/# sourceMappingURL=.*$/m, '');
// Scope the upstream CommonJS export; never read or modify host globals.
const factory = `(() => { const module = {exports: {}}; const exports = module.exports;\n${upstream}\nreturn module.exports; })()`;
const header = '// Generated by scripts/build_html_sanitizer.js; DOMPurify 3.4.16 (MPL-2.0 OR Apache-2.0).\n';
const body = `const createDOMPurify = ${factory};\n${policy}\nconst sanitizerCache = new WeakMap();\nfunction createCachedSanitizer(windowTarget) {\n  if (!windowTarget || (typeof windowTarget !== 'object' && typeof windowTarget !== 'function')) return createHtmlSanitizer(windowTarget, createDOMPurify);\n  if (!sanitizerCache.has(windowTarget)) sanitizerCache.set(windowTarget, createHtmlSanitizer(windowTarget, createDOMPurify));\n  return sanitizerCache.get(windowTarget);\n}\n`;
const outputs = {
  'xtendrmt/html-sanitizer.cjs': header + body + 'module.exports = {createHtmlSanitizer: createCachedSanitizer};\n',
  'xtendrmt/html-sanitizer.mjs': header + body + 'const createSanitizer = createCachedSanitizer;\nexport {createSanitizer as createHtmlSanitizer};\n',
  'xtendrmt/kernel/modules/rmt-html-sanitizer.js': '/* modules/rmt-html-sanitizer.js */\n' + header + `(function registerRmtHtmlSanitizerModule(global) {\n${body}const appModules = global.AppModules || (global.AppModules = {});\nappModules.createHtmlSanitizer = function createRmtHtmlSanitizerAdapter(windowTarget) { return createCachedSanitizer(windowTarget || (typeof window !== 'undefined' ? window : undefined)); };\n})(__XTENDRMT_GLOBAL__);\n`
};
for (const [target, value] of Object.entries(outputs)) {
  if (process.argv.includes('--check')) {
    if (fs.readFileSync(path.join(root, target), 'utf8') !== value) throw new Error(`Sanitizer artifact drift: ${target}`);
  } else fs.writeFileSync(path.join(root, target), value);
}
