const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const vm = require('vm');
const { verifyRmtDemoInventory } = require('./verify_rmt_demo_inventory');

const ARTIFACT_PARITY_SCHEMA = 'xtend.rmt.artifact-parity.v1';
const KERNEL_ARTIFACT_PARITY_SCHEMA = 'xtend.rmt.kernel-artifact-parity.v1';
const KERNEL_MODULE_MANIFEST_SCHEMA = 'xtend.rmt.kernel-module-manifest.v2';
const KERNEL_HARDENING_SOURCE_OF_TRUTH = 'development/WP-RKSH-10-Buildprozess-und-Artefakt-Paritaet-fuer-neue-Layer-absichern.md';
const REQUIRED_ARTIFACTS = [
  'xtendrmt/rmt-core.esm.js',
  'xtendrmt/rmt-runtime.esm.js',
  'xtendrmt/rmt-runtime.browser.js',
  'xtendrmt/rmt-core.d.ts',
  'xtendrmt/rmt.schema.json',
  'xtendrmt/rmt-manifest.json'
];
const REQUIRED_KERNEL_HARDENING_DOCS = [
  'development/XTendRMT-Kernel-Artifact-Parity-Contract.md',
  KERNEL_HARDENING_SOURCE_OF_TRUTH
];
const REQUIRED_KERNEL_TOOLING_MODULES = [
  'tools/rmt-language/kernel-trust-authority.js',
  'tools/rmt-language/kernel-panic-monitor.js',
  'tools/rmt-language/kernel-recovery.js',
  'tools/rmt-language/kernel-escalation.js',
  'tools/rmt-language/kernel-scheduler-failure.js',
  'tools/rmt-language/kernel-policy-parity.js',
  'tools/rmt-language/kernel-security-regression.js'
];
const KERNEL_LAB_MODULE_MANIFEST = 'xtendrmt/rmt-kernel-module-manifest.json';
const KERNEL_LAB_SOURCE_MANIFEST = 'xtendrmt/kernel/rmt-kernel-sources.json';
const KERNEL_LAB_SOURCE_INPUTS = [
  'xtendrmt/rmt-dom-descriptor-renderer.js',
  'xtendrmt/rmt-dom-descriptor-renderer.d.ts'
];
const KERNEL_LAB_CLEAN_ARTIFACTS = [
  'xtendrmt/rmt-core.esm.js',
  'xtendrmt/rmt-runtime.esm.js',
  'xtendrmt/rmt-runtime.browser.js',
  'xtendrmt/rmt-core.d.ts',
  'xtendrmt/rmt.schema.json',
  'xtendrmt/rmt-manifest.json'
];
const KERNEL_LAB_JS_ARTIFACTS = [
  'xtendrmt/rmt-core.esm.js',
  'xtendrmt/rmt-runtime.esm.js',
  'xtendrmt/rmt-runtime.browser.js'
];
const KERNEL_LAB_BUILD_PROVENANCE_PREFIX = 'generated by: xtend kernel-lab build --profile clean';
const DOM_RENDERER_MODULE_PATH = 'modules/rmt-dom-descriptor-renderer.js';
const DOM_RENDERER_FACTORY = 'createRmtDomDescriptorRenderer';
const DOM_RENDERER_SCHEMA = 'xtend.epic18.rmt-dom-descriptor-renderer.v1';
const DOM_COMMIT_RESULT_SCHEMA = 'xtend.rmt.dom-commit-result.v1';
const DOM_COMMIT_OPERATIONS = [
  'create-node',
  'replace-children',
  'reconcile-children',
  'reconcile-element',
  'merge-element'
];
const DEPRECATED_BRAND_PARTS = Object.freeze(['Render', 'Man']);
const DEPRECATED_BRAND_NAME = DEPRECATED_BRAND_PARTS.join('');
const DEPRECATED_BRAND_LOWER = DEPRECATED_BRAND_NAME.toLowerCase();
const DEPRECATED_BRAND_CAMEL = `${DEPRECATED_BRAND_LOWER.slice(0, 6)}${DEPRECATED_BRAND_NAME.slice(6)}`;
const DEPRECATED_BRAND_KEBAB = `${DEPRECATED_BRAND_LOWER.slice(0, 6)}-${DEPRECATED_BRAND_LOWER.slice(6)}`;
const DEPRECATED_FACTORY_PREFIX = `create${DEPRECATED_BRAND_NAME}`;
const REMOVED_DASHBOARD_SYMBOLS = [
  'createRmtDashboardAdapter',
  'createRmtDashboardCompatBootstrap',
  'createRmtDashboardCommandCatalog',
  'createRmtDashboardProductRuntime',
  `${DEPRECATED_FACTORY_PREFIX}DashboardAdapter`,
  `${DEPRECATED_FACTORY_PREFIX}DashboardCompatBootstrap`,
  `${DEPRECATED_FACTORY_PREFIX}DashboardCommandCatalog`,
  `${DEPRECATED_FACTORY_PREFIX}DashboardProductRuntime`,
  'dashboardAdapter',
  'dashboardCompatBootstrap',
  'dashboardCommandCatalog'
];
const REQUIRED_KERNEL_CONTRACT_IDS = [
  KERNEL_ARTIFACT_PARITY_SCHEMA,
  'xtend.rmt.kernel-trust-hardening.v1',
  'xtend.rmt.kernel-trust-authority.v1',
  'xtend.rmt.kernel-trust-verdict.v1',
  'xtend.rmt.kernel-trusted-dom-runtime.v1',
  'xtend.rmt.kernel-binding-security.v1',
  'xtend.rmt.kernel-panic-monitor.v1',
  'xtend.rmt.kernel-panic-state.v1',
  'xtend.rmt.kernel-panic-event.v1',
  'xtend.rmt.kernel-recovery.v1',
  'xtend.rmt.kernel-recovery-outcome.v1',
  'xtend.rmt.kernel-recovery-safe-snapshot.v1',
  'xtend.rmt.kernel-escalation.v1',
  'xtend.rmt.kernel-escalation-envelope.v1',
  'xtend.rmt.kernel-scheduler-failure.v1',
  'xtend.rmt.kernel-scheduler-failure-record.v1',
  'xtend.rmt.kernel-policy-parity.v1',
  'xtend.rmt.kernel-security-regression.v1'
];
const REQUIRED_KERNEL_RUNTIME_HOOKS = [
  'commitTrustedHtml',
  'commitTrustedAttribute',
  'commitTrustedProperty',
  'listTrustVerdicts',
  'getPanicSnapshot',
  'listPanicEvents',
  'recoverFromPanic',
  'listRecoveryOutcomes',
  'recordEscalation',
  'panicBlockScope',
  'createRmtKernelPolicyParity'
];
const REQUIRED_KERNEL_TYPE_SURFACES = [
  'RmtKernelRuntimeTrustVerdict',
  'RmtKernelRuntimePanicEvent',
  'RmtKernelRuntimePanicSnapshot',
  'RmtKernelRuntimeRecoverySafeSnapshot',
  'RmtKernelRuntimeRecoveryOutcome',
  'RmtKernelRuntimeEscalationEnvelope',
  'RmtKernelRuntimeSchedulerFailureRecord',
  'RmtKernelRuntimePolicyParityReport',
  'createRmtKernelPolicyParity'
];
const REQUIRED_KERNEL_GATES = [
  'node scripts/run_xtend_tests.js rmt-kernel-trust-authority --json',
  'node scripts/run_xtend_tests.js rmt-kernel-trusted-dom-runtime --json',
  'node scripts/run_xtend_tests.js rmt-kernel-binding-security --json',
  'node scripts/run_xtend_tests.js rmt-kernel-panic-monitor --json',
  'node scripts/run_xtend_tests.js rmt-kernel-recovery --json',
  'node scripts/run_xtend_tests.js rmt-kernel-escalation --json',
  'node scripts/run_xtend_tests.js rmt-kernel-scheduler-failure --json',
  'node scripts/run_xtend_tests.js rmt-kernel-policy-parity --json',
  'node scripts/run_xtend_tests.js rmt-kernel-security-regression --json',
  'node scripts/verify_xtendrmt_artifact_parity.js --json'
];
const REQUIRED_CONTRACT_IDS = [
  DOM_RENDERER_SCHEMA,
  DOM_COMMIT_RESULT_SCHEMA,
  'xtend.rmt.runtime-registry.v1',
  'xtend.rmt.xrouter-adapter.v1',
  'xtend.rmt.xtend-component-adapter.v1',
  'xtend.rmt.state-scheduler-diagnostics-bridge.v1',
  ARTIFACT_PARITY_SCHEMA,
  ...REQUIRED_KERNEL_CONTRACT_IDS
];
const REQUIRED_FACTORIES = [
  DOM_RENDERER_FACTORY,
  'createRmtFormat',
  'createRmtXRouterAdapter',
  'createRmtXtendComponentAdapter',
  'createRmtSurfaceAdapter',
  'createRmtStateSchedulerDiagnosticsBridge',
  'createRmtKernelPolicyParity'
];
const ESM_TARGETS = [
  { id: 'rmt-core.esm', path: 'xtendrmt/rmt-core.esm.js' },
  { id: 'rmt-runtime.esm', path: 'xtendrmt/rmt-runtime.esm.js' }
];
const BROWSER_TARGET = 'xtendrmt/rmt-runtime.browser.js';

function resolveRootDir(rootDir) {
  return path.resolve(rootDir || path.resolve(__dirname, '..'));
}

function resolvePath(rootDir, relativePath) {
  return path.join(rootDir, relativePath);
}

function readText(rootDir, relativePath) {
  return fs.readFileSync(resolvePath(rootDir, relativePath), 'utf8');
}

function readJson(rootDir, relativePath) {
  return JSON.parse(readText(rootDir, relativePath));
}

function sha256(value) {
  return crypto.createHash('sha256').update(String(value || '')).digest('hex');
}

function addCheck(checks, id, ok, message, details = {}) {
  checks.push({
    id,
    status: ok ? 'passed' : 'failed',
    message,
    ...details
  });
}

function includesAll(values, expected) {
  return Array.isArray(values) && expected.every((entry) => values.includes(entry));
}

function findRemovedDashboardSymbols(source) {
  return REMOVED_DASHBOARD_SYMBOLS.filter((symbol) => String(source || '').includes(symbol));
}

function findDeprecatedKernelBranding(source) {
  const text = String(source || '');
  return [
    DEPRECATED_BRAND_NAME,
    DEPRECATED_BRAND_CAMEL,
    DEPRECATED_BRAND_KEBAB,
    DEPRECATED_BRAND_LOWER
  ].filter((token) => text.includes(token));
}

function extractEsmNamedExports(source) {
  const exportMatch = source.match(/export\s+\{\s*([^}]+?)\s*\};\s*export default/u);
  if (!exportMatch) return [];
  return exportMatch[1]
    .split(',')
    .map((entry) => entry.trim().split(/\s+as\s+/u)[0].trim())
    .filter(Boolean);
}

function stripEsmExports(source) {
  return String(source || '')
    .replace(/^\s*import\s+[\s\S]*?\s+from\s+['"][^'"]+['"];\s*$/gmu, '')
    .replace(/^\s*import\s+['"][^'"]+['"];\s*$/gmu, '')
    .replace(/\nexport\s+\{[\s\S]*?\};\s*\nexport default[\s\S]*?;\s*$/u, '\n');
}

function parseScript(checks, relativePath, source, stripExports = false) {
  try {
    new vm.Script(stripExports ? stripEsmExports(source) : source, { filename: relativePath });
    addCheck(checks, `syntax:${relativePath}`, true, `${relativePath} parses as a JavaScript artifact`);
  } catch (error) {
    addCheck(checks, `syntax:${relativePath}`, false, `${relativePath} parses as a JavaScript artifact`, {
      error: error.message
    });
  }
}

function evaluateAppModules(checks, relativePath, source) {
  const sandbox = {
    console,
    setTimeout,
    clearTimeout,
    performance: { now: () => 0 }
  };
  sandbox.globalThis = sandbox;
  sandbox.window = sandbox;

  try {
    vm.runInNewContext(stripEsmExports(source), sandbox, { filename: relativePath });
    const appModules = sandbox.AppModules;
    addCheck(
      checks,
      `appModules:${relativePath}`,
      Boolean(appModules && typeof appModules.createRmtProductManifest === 'function'),
      `${relativePath} exposes AppModules and createRmtProductManifest`
    );
    return appModules || null;
  } catch (error) {
    addCheck(checks, `appModules:${relativePath}`, false, `${relativePath} exposes AppModules and createRmtProductManifest`, {
      error: error.message
    });
    return null;
  }
}

function getBuildTarget(manifest, id) {
  const targets = manifest && manifest.entryPoints && Array.isArray(manifest.entryPoints.buildTargets)
    ? manifest.entryPoints.buildTargets
    : [];
  return targets.find((target) => target.id === id) || null;
}

function getContractById(contracts, id) {
  return Array.isArray(contracts) ? contracts.find((entry) => entry.id === id) || null : null;
}

function getFactoryValues(manifest) {
  const factories = manifest && manifest.entryPoints && manifest.entryPoints.appModulesFactories
    ? manifest.entryPoints.appModulesFactories
    : {};
  return Object.values(factories);
}

function assertArtifactParityContract(checks, label, contract) {
  addCheck(checks, `${label}:contract`, Boolean(contract), `${label} exposes ${ARTIFACT_PARITY_SCHEMA}`);
  if (!contract) return;

  addCheck(
    checks,
    `${label}:status`,
    contract.status === 'epic-05-wp-13-contract',
    `${label} marks artifact parity as Epic 05 / WP-13 contract`
  );
  addCheck(
    checks,
    `${label}:sourceOfTruth`,
    contract.sourceOfTruth === 'development/WP-E05-13-Build-Pipeline-und-Artefakt-Paritaet-fuer-XTendRMT-absichern.md',
    `${label} points artifact parity to the WP-13 source of truth`
  );
  addCheck(
    checks,
    `${label}:gateCommand`,
    contract.gateCommand === 'node scripts/verify_xtendrmt_artifact_parity.js --json',
    `${label} documents the dedicated artifact parity gate command`
  );
  addCheck(
    checks,
    `${label}:artifactPaths`,
    includesAll(contract.artifactPaths, REQUIRED_ARTIFACTS),
    `${label} lists every synchronized XTendRMT artifact path`
  );
  addCheck(
    checks,
    `${label}:requiredFactories`,
    includesAll(contract.requiredFactories, REQUIRED_FACTORIES),
    `${label} lists the productive RMT adapter and bridge factories`
  );
  addCheck(
    checks,
    `${label}:requiredContracts`,
    includesAll(contract.requiredContractIds, REQUIRED_CONTRACT_IDS),
    `${label} lists the synchronized bridge and parity contract ids`
  );
  addCheck(
    checks,
    `${label}:artifactSurfaces`,
    includesAll(contract.artifactSurfaces, [
      'scripts/verify_xtendrmt_artifact_parity.js',
      'RmtArtifactParityContract',
      'artifactParityContracts',
      DOM_RENDERER_FACTORY,
      'RmtKernelRuntimeTrustVerdict',
      'RmtKernelRuntimePanicSnapshot',
      'RmtKernelRuntimeRecoveryOutcome',
      'createRmtKernelPolicyParity'
    ]),
    `${label} lists the artifact parity gate and type surfaces`
  );
  addCheck(
    checks,
    `${label}:kernelHardeningSourceOfTruth`,
    contract.kernelHardeningSourceOfTruth === KERNEL_HARDENING_SOURCE_OF_TRUTH,
    `${label} points kernel hardening artifact parity to RKSH-WP-10`
  );
  addCheck(
    checks,
    `${label}:kernelHardeningContracts`,
    includesAll(contract.kernelHardeningContracts, REQUIRED_KERNEL_CONTRACT_IDS),
    `${label} lists kernel hardening contract ids`
  );
  addCheck(
    checks,
    `${label}:kernelHardeningRuntimeHooks`,
    includesAll(contract.kernelHardeningRuntimeHooks, REQUIRED_KERNEL_RUNTIME_HOOKS),
    `${label} lists kernel hardening runtime hooks`
  );
  addCheck(
    checks,
    `${label}:kernelHardeningTypeSurfaces`,
    includesAll(contract.kernelHardeningTypeSurfaces, REQUIRED_KERNEL_TYPE_SURFACES),
    `${label} lists kernel hardening type surfaces`
  );
  addCheck(
    checks,
    `${label}:kernelHardeningToolingModules`,
    includesAll(contract.kernelHardeningToolingModules, REQUIRED_KERNEL_TOOLING_MODULES),
    `${label} lists kernel hardening tooling modules`
  );
  addCheck(
    checks,
    `${label}:kernelHardeningGates`,
    includesAll(contract.kernelHardeningGates, REQUIRED_KERNEL_GATES),
    `${label} lists kernel hardening gates`
  );
}

function runXtendRmtArtifactParity(options = {}) {
  const rootDir = resolveRootDir(options.rootDir);
  const checks = [];
  const sources = {};

  REQUIRED_ARTIFACTS.forEach((relativePath) => {
    const exists = fs.existsSync(resolvePath(rootDir, relativePath));
    addCheck(checks, `exists:${relativePath}`, exists, `${relativePath} exists`);
    if (exists) {
      sources[relativePath] = readText(rootDir, relativePath);
    }
  });
  KERNEL_LAB_SOURCE_INPUTS.forEach((relativePath) => {
    const exists = fs.existsSync(resolvePath(rootDir, relativePath));
    addCheck(checks, `exists:${relativePath}`, exists, `${relativePath} exists as a canonical KernelLab input`);
    if (exists) {
      sources[relativePath] = readText(rootDir, relativePath);
    }
  });
  [...REQUIRED_KERNEL_HARDENING_DOCS, ...REQUIRED_KERNEL_TOOLING_MODULES].forEach((relativePath) => {
    addCheck(
      checks,
      `exists:${relativePath}`,
      fs.existsSync(resolvePath(rootDir, relativePath)),
      `${relativePath} exists`
    );
  });

  let schema = null;
  let manifest = null;
  let packageJson = null;
  try {
    schema = readJson(rootDir, 'xtendrmt/rmt.schema.json');
    addCheck(checks, 'json:xtendrmt/rmt.schema.json', true, 'RMT schema parses as JSON');
  } catch (error) {
    addCheck(checks, 'json:xtendrmt/rmt.schema.json', false, 'RMT schema parses as JSON', { error: error.message });
  }
  try {
    manifest = readJson(rootDir, 'xtendrmt/rmt-manifest.json');
    addCheck(checks, 'json:xtendrmt/rmt-manifest.json', true, 'RMT manifest parses as JSON');
  } catch (error) {
    addCheck(checks, 'json:xtendrmt/rmt-manifest.json', false, 'RMT manifest parses as JSON', { error: error.message });
  }
  try {
    packageJson = readJson(rootDir, 'package.json');
    addCheck(checks, 'json:package.json', true, 'package.json parses as JSON');
  } catch (error) {
    addCheck(checks, 'json:package.json', false, 'package.json parses as JSON', { error: error.message });
  }
  let kernelModuleManifest = null;
  try {
    kernelModuleManifest = readJson(rootDir, KERNEL_LAB_MODULE_MANIFEST);
    addCheck(checks, `json:${KERNEL_LAB_MODULE_MANIFEST}`, true, 'KernelLab module manifest parses as JSON');
  } catch (error) {
    addCheck(checks, `json:${KERNEL_LAB_MODULE_MANIFEST}`, false, 'KernelLab module manifest parses as JSON', { error: error.message });
  }
  let kernelSourceManifest = null;
  try {
    kernelSourceManifest = readJson(rootDir, KERNEL_LAB_SOURCE_MANIFEST);
    addCheck(checks, `json:${KERNEL_LAB_SOURCE_MANIFEST}`, true, 'KernelLab canonical source manifest parses as JSON');
  } catch (error) {
    addCheck(checks, `json:${KERNEL_LAB_SOURCE_MANIFEST}`, false, 'KernelLab canonical source manifest parses as JSON', { error: error.message });
  }
  const expectedKernelModuleCount = kernelSourceManifest
    && kernelSourceManifest.bundle
    && Array.isArray(kernelSourceManifest.bundle.moduleOrder)
    ? kernelSourceManifest.bundle.moduleOrder.length
    : 0;

  const schemaXtend = schema && schema['x-xtendrmt'] ? schema['x-xtendrmt'] : {};
  const schemaContract = getContractById(schemaXtend.artifactParityContracts, ARTIFACT_PARITY_SCHEMA);
  const manifestContract = getContractById(manifest && manifest.artifactParityContracts, ARTIFACT_PARITY_SCHEMA);
  const domCommitContract = getContractById(schemaXtend.domCommitContracts, DOM_COMMIT_RESULT_SCHEMA);
  assertArtifactParityContract(checks, 'schema', schemaContract);
  assertArtifactParityContract(checks, 'manifest', manifestContract);
  addCheck(
    checks,
    'schema-dom-commit:contract',
    Boolean(domCommitContract),
    `RMT schema exposes ${DOM_COMMIT_RESULT_SCHEMA}`
  );
  addCheck(
    checks,
    'schema-dom-commit:renderer',
    domCommitContract && domCommitContract.rendererSchema === DOM_RENDERER_SCHEMA,
    `RMT DOM commit contract references ${DOM_RENDERER_SCHEMA}`
  );
  addCheck(
    checks,
    'schema-dom-commit:operations',
    domCommitContract && includesAll(domCommitContract.operations, DOM_COMMIT_OPERATIONS),
    'RMT DOM commit contract lists every public commit operation'
  );

  REQUIRED_CONTRACT_IDS.forEach((contractId) => {
    addCheck(
      checks,
      `schema-contract:${contractId}`,
      sources['xtendrmt/rmt.schema.json'] && sources['xtendrmt/rmt.schema.json'].includes(contractId),
      `RMT schema contains ${contractId}`
    );
  });

  KERNEL_LAB_CLEAN_ARTIFACTS.forEach((relativePath) => {
    const dashboardSymbols = findRemovedDashboardSymbols(sources[relativePath] || '');
    addCheck(
      checks,
      `kernel-lab-dashboard-free:${relativePath}`,
      dashboardSymbols.length === 0,
      `${relativePath} does not contain removed Dashboard kernel symbols`,
      { symbols: dashboardSymbols }
    );
    const deprecatedBranding = findDeprecatedKernelBranding(sources[relativePath] || '');
    addCheck(
      checks,
      `kernel-lab-deprecated-brand-free:${relativePath}`,
      deprecatedBranding.length === 0,
      `${relativePath} does not contain deprecated kernel branding`,
      { matchCount: deprecatedBranding.length }
    );
  });
  const manifestVersion = manifest && typeof manifest.version === 'string' ? manifest.version : null;
  const manifestApiVersion = manifest && typeof manifest.apiVersion === 'string' ? manifest.apiVersion : null;
  addCheck(
    checks,
    'kernel-lab-version:manifest-api',
    Boolean(manifestVersion && manifestApiVersion && manifestVersion === manifestApiVersion),
    'rmt-manifest version and apiVersion are synchronized'
  );
  KERNEL_LAB_JS_ARTIFACTS.forEach((relativePath) => {
    const source = sources[relativePath] || '';
    addCheck(
      checks,
      `kernel-lab-header:no-generated-at:${relativePath}`,
      !source.includes('generated at:'),
      `${relativePath} does not carry a stale generated timestamp`
    );
    addCheck(
      checks,
      `kernel-lab-header:provenance:${relativePath}`,
      source.includes(KERNEL_LAB_BUILD_PROVENANCE_PREFIX) && (!manifestVersion || source.includes(`--version ${manifestVersion}`)),
      `${relativePath} records KernelLab build provenance`
    );
    addCheck(
      checks,
      `kernel-lab-version:header:${relativePath}`,
      Boolean(manifestVersion && source.includes(`XTendRMT ${manifestVersion}`)),
      `${relativePath} header matches rmt-manifest version`
    );
    addCheck(
      checks,
      `kernel-lab-version:runtime:${relativePath}`,
      Boolean(manifestVersion && source.includes(`const PUBLIC_API_VERSION = '${manifestVersion}';`)),
      `${relativePath} PUBLIC_API_VERSION matches rmt-manifest version`
    );
    addCheck(
      checks,
      `kernel-lab-dom-commit:module:${relativePath}`,
      source.includes(`/* ${DOM_RENDERER_MODULE_PATH} */`),
      `${relativePath} includes the canonical DOM descriptor renderer module`
    );
    addCheck(
      checks,
      `kernel-lab-dom-commit:factory:${relativePath}`,
      source.includes(`appModules.${DOM_RENDERER_FACTORY} = rendererApi.${DOM_RENDERER_FACTORY};`),
      `${relativePath} registers ${DOM_RENDERER_FACTORY}`
    );
    addCheck(
      checks,
      `kernel-lab-dom-commit:component-bridge:${relativePath}`,
      source.includes('<kernel-lab:xtend-component-dom-commit-bridge>')
        && source.includes("operation: 'replace-children'"),
      `${relativePath} delegates XTend component writes to the DOM commit bridge`
    );
    addCheck(
      checks,
      `kernel-lab-dom-commit:no-legacy-writer:${relativePath}`,
      !source.includes('function applyXtendComponentAttributes(')
        && !source.includes('function applyXtendComponentProps('),
      `${relativePath} does not contain the legacy XTend component DOM writers`
    );
    addCheck(
      checks,
      `kernel-lab-dom-commit:no-normal-html-sink:${relativePath}`,
      !source.includes('child.innerHTML = markup'),
      `${relativePath} does not contain the legacy normal slot HTML sink`
    );
    addCheck(
      checks,
      `kernel-lab-dom-commit:canonical-trusted-html-sink:${relativePath}`,
      (source.match(/\btemplateElement\.innerHTML\s*=/gu) || []).length === 1
        && source.includes('<kernel-lab:rmt-trusted-dom-sink>')
        && source.includes('<kernel-lab:rmt-template-execution-trusted-dom-delegate>'),
      `${relativePath} contains one canonical Trusted-DOM parser sink and delegates the execution path`
    );
    addCheck(
      checks,
      `kernel-lab-dom-commit:no-direct-element-html-sink:${relativePath}`,
      !/\belement\.innerHTML\s*=(?!=)/u.test(source),
      `${relativePath} does not contain direct element.innerHTML writers`
    );
  });
  addCheck(
    checks,
    'kernel-lab-version:types',
    Boolean(manifestVersion && (sources['xtendrmt/rmt-core.d.ts'] || '').includes(`XTendRMT ${manifestVersion} type definitions`)),
    'rmt-core.d.ts header matches rmt-manifest version'
  );
  addCheck(
    checks,
    'kernel-lab-dom-commit:types',
    (sources['xtendrmt/rmt-core.d.ts'] || '').includes('export type RmtDomCommitRequest')
      && (sources['xtendrmt/rmt-core.d.ts'] || '').includes('export interface RmtDomCommitResult')
      && (sources['xtendrmt/rmt-core.d.ts'] || '').includes(`export function ${DOM_RENDERER_FACTORY}`),
    'rmt-core.d.ts exposes the synchronized DOM commit request, result and renderer factory'
  );

  addCheck(
    checks,
    'kernel-lab-module-manifest:schema',
    kernelModuleManifest && kernelModuleManifest.schema === KERNEL_MODULE_MANIFEST_SCHEMA,
    `KernelLab module manifest uses ${KERNEL_MODULE_MANIFEST_SCHEMA}`
  );
  addCheck(
    checks,
    'kernel-lab-module-manifest:count-reconciliation',
    kernelModuleManifest
      && expectedKernelModuleCount > 0
      && kernelModuleManifest.expectedHistoricalModuleCount === expectedKernelModuleCount
      && kernelModuleManifest.visibleModuleCount === expectedKernelModuleCount
      && kernelModuleManifest.moduleCountMatchesHistory === true,
    `KernelLab module manifest records the complete ${expectedKernelModuleCount}-module canonical topology`
  );
  addCheck(
    checks,
    'kernel-lab-module-manifest:canonical-source-mode',
    kernelModuleManifest
      && kernelModuleManifest.generatedFrom === 'kernel-lab-canonical-module-sources'
      && kernelModuleManifest.sourceOfTruth === 'xtendrmt/kernel/rmt-kernel-sources.json'
      && kernelModuleManifest.legacyBundleModuleCount === 0
      && includesAll(kernelModuleManifest.canonicalSources, KERNEL_LAB_SOURCE_INPUTS),
    'KernelLab module manifest records canonical source-only assembly without legacy bundle inputs'
  );
  const domCommitSource = kernelModuleManifest && kernelModuleManifest.domCommitSource;
  addCheck(
    checks,
    'kernel-lab-module-manifest:dom-source',
    domCommitSource
      && domCommitSource.modulePath === DOM_RENDERER_MODULE_PATH
      && domCommitSource.factory === DOM_RENDERER_FACTORY
      && domCommitSource.rendererSchema === DOM_RENDERER_SCHEMA
      && domCommitSource.commitResultSchema === DOM_COMMIT_RESULT_SCHEMA,
    'KernelLab module manifest records the DOM renderer module, factory and schemas'
  );
  addCheck(
    checks,
    'kernel-lab-module-manifest:dom-source-sha',
    domCommitSource
      && domCommitSource.renderer
      && domCommitSource.types
      && domCommitSource.renderer.sha256 === sha256(sources[KERNEL_LAB_SOURCE_INPUTS[0]])
      && domCommitSource.types.sha256 === sha256(sources[KERNEL_LAB_SOURCE_INPUTS[1]]),
    'KernelLab module manifest hashes match both canonical DOM renderer inputs'
  );
  addCheck(
    checks,
    'kernel-lab-module-manifest:dom-module',
    kernelModuleManifest
      && Array.isArray(kernelModuleManifest.modules)
      && kernelModuleManifest.modules.some((entry) => (
        entry.id === 'rmt-dom-descriptor-renderer'
        && Array.isArray(entry.factories)
        && entry.factories.includes(DOM_RENDERER_FACTORY)
      )),
    'KernelLab module topology includes the canonical DOM renderer module and factory'
  );
  addCheck(
    checks,
    'kernel-lab-module-manifest:artifact-set',
    kernelModuleManifest
      && Array.isArray(kernelModuleManifest.sourceArtifacts)
      && includesAll(
        kernelModuleManifest.sourceArtifacts.map((entry) => entry.path),
        KERNEL_LAB_CLEAN_ARTIFACTS
      )
      && kernelModuleManifest.sourceArtifacts.length === KERNEL_LAB_CLEAN_ARTIFACTS.length,
    'KernelLab module manifest covers all six synchronized artifacts (seven outputs including itself)'
  );
  addCheck(
    checks,
    'kernel-lab-module-manifest:version',
    Boolean(kernelModuleManifest && manifestVersion && kernelModuleManifest.kernelVersion === manifestVersion),
    'KernelLab module manifest records the manifest kernel version'
  );
  const kernelModuleManifestSource = fs.existsSync(resolvePath(rootDir, KERNEL_LAB_MODULE_MANIFEST))
    ? readText(rootDir, KERNEL_LAB_MODULE_MANIFEST)
    : '';
  const kernelModuleManifestDeprecatedBranding = findDeprecatedKernelBranding(kernelModuleManifestSource);
  addCheck(
    checks,
    'kernel-lab-module-manifest:deprecated-brand-free',
    kernelModuleManifestDeprecatedBranding.length === 0,
    'KernelLab module manifest does not contain deprecated kernel branding',
    { matchCount: kernelModuleManifestDeprecatedBranding.length }
  );
  if (kernelModuleManifest && Array.isArray(kernelModuleManifest.sourceArtifacts)) {
    KERNEL_LAB_CLEAN_ARTIFACTS.forEach((relativePath) => {
      const artifact = kernelModuleManifest.sourceArtifacts.find((entry) => entry.path === relativePath);
      addCheck(
        checks,
        `kernel-lab-module-manifest:sha:${relativePath}`,
        Boolean(artifact && sources[relativePath] && artifact.sha256 === sha256(sources[relativePath])),
        `KernelLab module manifest sha matches ${relativePath}`
      );
      addCheck(
        checks,
        `kernel-lab-module-manifest:dashboard-free:${relativePath}`,
        Boolean(artifact && Array.isArray(artifact.dashboardSymbols) && artifact.dashboardSymbols.length === 0),
        `KernelLab module manifest records ${relativePath} as Dashboard-free`
      );
    });
  }

  const manifestFactories = getFactoryValues(manifest);
  addCheck(
    checks,
    'manifest-dom-commit:runtime-contract',
    manifest
      && manifest.runtimeContract
      && manifest.runtimeContract.domDescriptorCommit === true,
    'rmt-manifest enables the canonical DOM descriptor commit contract'
  );
  REQUIRED_FACTORIES.forEach((factoryName) => {
    addCheck(
      checks,
      `manifest-factory:${factoryName}`,
      manifestFactories.includes(factoryName),
      `rmt-manifest appModulesFactories includes ${factoryName}`
    );
  });
  ['rmt-core.esm', 'rmt-runtime.esm', 'rmt-runtime.browser'].forEach((targetId) => {
    const target = getBuildTarget(manifest, targetId);
    addCheck(
      checks,
      `manifest-dom-commit:source-module:${targetId}`,
      target && includesAll(target.sourceModules, [DOM_RENDERER_MODULE_PATH]),
      `${targetId} includes the canonical DOM renderer source module`
    );
    if (targetId.endsWith('.esm')) {
      addCheck(
        checks,
        `manifest-dom-commit:named-export:${targetId}`,
        target && includesAll(target.namedExports, [DOM_RENDERER_FACTORY]),
        `${targetId} declares ${DOM_RENDERER_FACTORY} as a named export`
      );
    }
  });

  const typesSource = sources['xtendrmt/rmt-core.d.ts'] || '';
  REQUIRED_FACTORIES.forEach((factoryName) => {
    addCheck(
      checks,
      `types-factory:${factoryName}`,
      typesSource.includes(`export declare function ${factoryName}`)
        || typesSource.includes(`export function ${factoryName}`),
      `rmt-core.d.ts declares ${factoryName}`
    );
  });
  ['RmtArtifactParityContract', 'artifactParityContracts?: RmtArtifactParityContract[]'].forEach((typeSurface) => {
    addCheck(
      checks,
      `types-surface:${typeSurface}`,
      typesSource.includes(typeSurface),
      `rmt-core.d.ts exposes ${typeSurface}`
    );
  });
  REQUIRED_KERNEL_TYPE_SURFACES.forEach((typeSurface) => {
    addCheck(
      checks,
      `kernel-types-surface:${typeSurface}`,
      typesSource.includes(typeSurface),
      `rmt-core.d.ts exposes ${typeSurface}`
    );
  });

  ESM_TARGETS.forEach((target) => {
    const source = sources[target.path] || '';
    parseScript(checks, target.path, source, true);
    const manifestTarget = getBuildTarget(manifest, target.id);
    const manifestNamedExports = manifestTarget && Array.isArray(manifestTarget.namedExports)
      ? manifestTarget.namedExports
      : [];
    const actualNamedExports = extractEsmNamedExports(source);
    addCheck(
      checks,
      `esm-target:${target.id}`,
      Boolean(manifestTarget),
      `rmt-manifest declares build target ${target.id}`
    );
    addCheck(
      checks,
      `esm-exports:${target.id}`,
      includesAll(actualNamedExports, manifestNamedExports),
      `${target.id} ESM export block covers manifest namedExports`,
      {
        expected: manifestNamedExports.length,
        actual: actualNamedExports.length
      }
    );
    addCheck(
      checks,
      `esm-factory-snapshot:${target.id}`,
      !/\bconst\s+AppModules\s*=\s*__XTENDRMT_GLOBAL__\.AppModules\s*;/u.test(source),
      `${target.id} named exports resolve through a module-local factory snapshot instead of the live AppModules mirror`
    );
    REQUIRED_FACTORIES.forEach((factoryName) => {
      addCheck(
        checks,
        `esm-factory:${target.id}:${factoryName}`,
        source.includes(`const ${factoryName} =`) && source.includes(`AppModules.${factoryName}`),
        `${target.id} exposes ${factoryName} through AppModules wrapper`
      );
    });
    REQUIRED_KERNEL_RUNTIME_HOOKS.forEach((hookName) => {
      addCheck(
        checks,
        `esm-kernel-hook:${target.id}:${hookName}`,
        source.includes(hookName),
        `${target.id} contains kernel hardening hook ${hookName}`
      );
    });

    const appModules = evaluateAppModules(checks, target.path, source);
    if (appModules && typeof appModules.createRmtProductManifest === 'function') {
      const generatedManifest = appModules.createRmtProductManifest();
      REQUIRED_FACTORIES.forEach((factoryName) => {
        addCheck(
          checks,
          `generated-manifest-factory:${target.id}:${factoryName}`,
          getFactoryValues(generatedManifest).includes(factoryName),
          `${target.id} generated product manifest includes ${factoryName}`
        );
      });
      const generatedContract = getContractById(generatedManifest.artifactParityContracts, ARTIFACT_PARITY_SCHEMA);
      assertArtifactParityContract(checks, `generated-manifest:${target.id}`, generatedContract);
    }
  });

  const browserSource = sources[BROWSER_TARGET] || '';
  parseScript(checks, BROWSER_TARGET, browserSource, false);
  REQUIRED_FACTORIES.forEach((factoryName) => {
    addCheck(
      checks,
      `browser-factory:${factoryName}`,
      browserSource.includes(`appModules.${factoryName}`),
      `browser runtime artifact contains ${factoryName}`
    );
  });
  REQUIRED_KERNEL_RUNTIME_HOOKS.forEach((hookName) => {
    addCheck(
      checks,
      `browser-kernel-hook:${hookName}`,
      browserSource.includes(hookName),
      `browser runtime artifact contains kernel hardening hook ${hookName}`
    );
  });
  addCheck(
    checks,
    'browser-artifact-parity-contract',
    browserSource.includes('artifactParityContracts') && browserSource.includes(ARTIFACT_PARITY_SCHEMA),
    'browser runtime generated manifest contains artifact parity contract'
  );

  addCheck(
    checks,
    'package-script:test-rmt-artifact-parity',
    packageJson && packageJson.scripts && packageJson.scripts['test:rmt-artifact-parity'] === 'node scripts/verify_xtendrmt_artifact_parity.js',
    'package.json exposes npm run test:rmt-artifact-parity'
  );
  const kernelArtifactParityMetadata = packageJson && packageJson.xtend && packageJson.xtend.rmtKernelArtifactParity;
  addCheck(
    checks,
    'package-metadata:rmtKernelArtifactParity',
    kernelArtifactParityMetadata && kernelArtifactParityMetadata.schema === KERNEL_ARTIFACT_PARITY_SCHEMA,
    'package.json exposes RKSH-WP-10 kernel artifact parity metadata'
  );
  addCheck(
    checks,
    'package-metadata:rmtKernelArtifactParity-gate',
    kernelArtifactParityMetadata && kernelArtifactParityMetadata.localGate === 'node scripts/verify_xtendrmt_artifact_parity.js --json',
    'package.json exposes RKSH-WP-10 kernel artifact parity gate'
  );

  const demoInventory = verifyRmtDemoInventory();
  addCheck(checks, 'rmt-demo-inventory', demoInventory.ok, `demo inventory and source hashes are current${demoInventory.ok ? '' : `: ${demoInventory.errors.join('; ')}`}`);
  addCheck(
    checks,
    'rmt-demo-package-boundary',
    packageJson && Array.isArray(packageJson.files) && packageJson.files.every((entry) => !String(entry).startsWith('demos/')),
    'root package files exclude demos/ from the publish boundary'
  );

  const failedChecks = checks.filter((check) => check.status === 'failed');
  return {
    schema: 'xtend.rmt.artifact-parity-report.v1',
    contract: ARTIFACT_PARITY_SCHEMA,
    status: failedChecks.length === 0 ? 'passed' : 'failed',
    ok: failedChecks.length === 0,
    rootDir,
    passCount: checks.length - failedChecks.length,
    failureCount: failedChecks.length,
    checks
  };
}

function printTextReport(report) {
  if (report.ok) {
    console.log(`XTendRMT artifact parity passed (${report.passCount} checks).`);
    return;
  }
  console.error(`XTendRMT artifact parity failed (${report.failureCount} failures).`);
  report.checks
    .filter((check) => check.status === 'failed')
    .forEach((check) => {
      console.error(`- ${check.id}: ${check.message}`);
      if (check.error) {
        console.error(`  ${check.error}`);
      }
    });
}

if (require.main === module) {
  const json = process.argv.includes('--json');
  const report = runXtendRmtArtifactParity();
  if (json) {
    console.log(JSON.stringify(report, null, 2));
  } else {
    printTextReport(report);
  }
  if (!report.ok) {
    process.exit(1);
  }
}

module.exports = {
  ARTIFACT_PARITY_SCHEMA,
  KERNEL_ARTIFACT_PARITY_SCHEMA,
  REQUIRED_KERNEL_CONTRACT_IDS,
  REQUIRED_KERNEL_RUNTIME_HOOKS,
  REQUIRED_KERNEL_TYPE_SURFACES,
  REQUIRED_ARTIFACTS,
  REQUIRED_CONTRACT_IDS,
  REQUIRED_FACTORIES,
  runXtendRmtArtifactParity
};
