'use strict';

const fs = require('fs');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');
const checkOnly = process.argv.includes('--check');

function read(relativePath) {
  return fs.readFileSync(path.join(rootDir, relativePath), 'utf8');
}

function replaceOnce(source, pattern, replacement, label) {
  const matches = source.match(pattern);
  if (!matches) throw new Error(`Unable to generate native ESM: ${label} was not found.`);
  return source.replace(pattern, replacement);
}

function esmExport(source, frozen = false) {
  const pattern = frozen
    ? /module\.exports = Object\.freeze\(\{([\s\S]*?)\}\);\s*$/u
    : /module\.exports = \{([\s\S]*?)\};\s*$/u;
  return replaceOnce(source, pattern, (_match, names) => `export {${names}};\n`, 'CommonJS export block');
}

function protocolEsm() {
  let source = read('tools/rmt-language/xscaler-protocol.js');
  source = replaceOnce(source, /^'use strict';\s*/u, '', 'protocol strict-mode header');
  source = source.replace(
    "const XSCALER_PREFLIGHT_REQUEST_SCHEMA = 'xtend.xscaler.preflight-request.v1';",
    "const XSCALER_PUBLIC_PROTOCOL_SCHEMA = 'xtend.xscaler.public-protocol.v1';\nconst XSCALER_PREFLIGHT_REQUEST_SCHEMA = 'xtend.xscaler.preflight-request.v1';"
  );
  source = esmExport(source, false);
  source = source.replace('export {\n', 'export {\n  XSCALER_PUBLIC_PROTOCOL_SCHEMA,\n');
  return `// Generated by xscaler/generate-esm.js from the canonical tooling protocol.\n${source}`;
}

function loaderEsm() {
  let source = read('xscaler/remote-adapter-loader.js');
  source = replaceOnce(source, /^'use strict';\s*/u, '', 'loader strict-mode header');
  source = replaceOnce(
    source,
    /const \{([\s\S]*?)\n\} = require\('\.\/protocol'\);/u,
    (_match, names) => `import {${names}\n} from './protocol.mjs';`,
    'loader protocol import'
  );
  source = esmExport(source, true);
  return `// Generated by xscaler/generate-esm.js from remote-adapter-loader.js.\n${source}`;
}

function appServiceTransportEsm() {
  let source = read('xscaler/app-service-transport.js');
  source = replaceOnce(source, /^'use strict';\s*/u, '', 'AppService transport strict-mode header');
  source = replaceOnce(
    source,
    /const \{([\s\S]*?)\n\} = require\('\.\/remote-adapter-loader'\);/u,
    (_match, names) => `import {${names}\n} from './remote-adapter-loader.mjs';`,
    'AppService loader import'
  );
  source = esmExport(source, true);
  return `// Generated by xscaler/generate-esm.js from app-service-transport.js.\n${source}`;
}

function indexEsm() {
  return `// Generated by xscaler/generate-esm.js.\nexport const XSCALER_PUBLIC_API_SCHEMA = 'xtend.xscaler.public-api.v1';\nexport * from './protocol.mjs';\nexport * from './remote-adapter-loader.mjs';\nexport * from './app-service-transport.mjs';\n`;
}

const outputs = new Map([
  ['xscaler/protocol.mjs', protocolEsm()],
  ['xscaler/remote-adapter-loader.mjs', loaderEsm()],
  ['xscaler/app-service-transport.mjs', appServiceTransportEsm()],
  ['xscaler/index.mjs', indexEsm()]
]);

let drift = false;
for (const [relativePath, expected] of outputs) {
  const absolutePath = path.join(rootDir, relativePath);
  if (checkOnly) {
    const actual = fs.existsSync(absolutePath) ? fs.readFileSync(absolutePath, 'utf8') : '';
    if (actual !== expected) {
      drift = true;
      process.stderr.write(`Native XScaler ESM drift: ${relativePath}\n`);
    }
  } else {
    fs.writeFileSync(absolutePath, expected);
  }
}

if (drift) process.exitCode = 1;
else process.stdout.write(checkOnly ? 'Native XScaler ESM outputs are synchronized.\n' : 'Native XScaler ESM outputs generated.\n');
