// Generated by xscaler/generate-esm.js.
export const XSCALER_PUBLIC_API_SCHEMA = 'xtend.xscaler.public-api.v1';
export * from './protocol.mjs';
export * from './remote-adapter-loader.mjs';
export * from './app-service-transport.mjs';
