export const xTextareaFixture = {
  schema: 'xtend.component.fixture-data.v1',
  componentRef: 'x-textarea',
  attributes: {
    id: 'component-textarea',
    name: 'notes',
    value: 'Initial note',
    placeholder: 'Write a note',
    maxlength: 240,
    minlength: 1,
    rows: 5,
    required: true,
    disabled: false,
    readonly: false,
    busy: false,
    invalid: false,
    density: 'comfortable',
    fill: true,
    'submit-on-enter': true,
    'submit-command': 'save-note',
    'syntax-highlight': true,
    highlight: true,
    'line-numbering': true,
    lang: 'text',
    language: 'plaintext'
  },
  expectedSlots: ['label', 'hint', 'error'],
  expectedEvents: ['textarea-changed', 'textarea-invalid', 'textarea-submit', 'xtend-command'],
  expectedMethods: ['checkValidity', 'reportValidity', 'validate', 'reset', 'focus', 'snapshot'],
  expectedA11y: ['role=textbox', 'aria-describedby', 'role=status', 'role=alert'],
  expectedTelemetry: ['mount', 'hydrate', 'event']
} as const;
