export const XCOMMAND_KERNEL_CONTRACT: 'xtend.xcommand.kernel-contract.v1';
export const XKEYMAP_SURFACE_CONTRACT: 'xtend.xkeymap.surface-contract.v1';
export const RMT_XCOMMAND_SCHEMA: 'xtend.rmt.xcommand.v1';
export const DEFAULT_CHORD_TIMEOUT_MS: 1200;
export type XCommandLane = 'input' | 'interaction' | 'background' | 'user-blocking' | 'visible' | 'a11y' | 'diagnostics';
export type XCommandRegistration = {
  id: string;
  scope?: string;
  when?: string;
  sequence?: string[];
  keys?: string;
  label?: { i18nKey: string; fallback: string } | string;
  icon?: string;
  actionRef?: string;
  action?: string;
  eventRef?: string;
  event?: string;
  effectRef?: string;
  effect?: string;
  lane?: XCommandLane;
  keymap?: { group?: string; visible?: boolean; order?: number };
};
export type XCommandKeyStroke = { token: string; key?: string; scope?: string; repeat?: boolean; timestamp?: number };
export type XCommandDispatchResult = { schema: typeof XCOMMAND_KERNEL_CONTRACT; status: 'invoked' | 'pending-chord' | 'ignored'; commandId?: string; sequence: string[]; lane?: XCommandLane; actionRef?: string; eventRef?: string; effectRef?: string };
export type XKeymapEntry = { schema: typeof XKEYMAP_SURFACE_CONTRACT; id: string; scope: string; group: string; order: number; sequence: string[]; label: { i18nKey: string; fallback: string }; icon?: string; lane: XCommandLane };
export function parseKeySequence(input: string | string[]): string[];
export function normalizeRegistration(record: XCommandRegistration): { record: Required<XCommandRegistration> & { schema: typeof XCOMMAND_KERNEL_CONTRACT; sequenceKey: string }; diagnostics: Array<Record<string, unknown>> };
export function normalizeKeyboardEvent(event: KeyboardEvent, options?: Record<string, unknown>): XCommandKeyStroke;
export function createXCommandKernel(options?: Record<string, unknown>): { schema: typeof XCOMMAND_KERNEL_CONTRACT; register(record: XCommandRegistration): () => void; dispatch(stroke: XCommandKeyStroke | string): XCommandDispatchResult; resetChord(reason?: string): void; getKeymap(scope?: string): XKeymapEntry[]; getDiagnostics(): Array<Record<string, unknown>>; getRegistrations(): XCommandRegistration[] };
export function createXKeymapModel(entries: XKeymapEntry[], options?: { locale?: string; platform?: string }): Record<string, unknown>;
export function parseRmtXCommands(sourceText: string): { schema: typeof RMT_XCOMMAND_SCHEMA; records: XCommandRegistration[]; diagnostics: Array<Record<string, unknown>> };
