'use strict';
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const root = path.resolve(__dirname, '..');
test('XTend Material Workbench product contract', () => {
  const config = JSON.parse(fs.readFileSync(path.join(root, 'maraca.config.json'), 'utf8'));
  const evidence = JSON.parse(fs.readFileSync(path.join(root, 'src/data/evidence.json'), 'utf8'));
  const lessons = JSON.parse(fs.readFileSync(path.join(root, 'src/data/lessons.json'), 'utf8'));
  const rmt = fs.readFileSync(path.join(root, 'src/app.rmt'), 'utf8');
  const devApi = fs.readFileSync(path.join(root, 'src/workbench-dev-api.mjs'), 'utf8');
  const visualGate = fs.readFileSync(path.join(root, 'src/workbench-visual-gate.mjs'), 'utf8');
  const runtimeHost = fs.readFileSync(path.join(root, 'src/workbench-runtime-host.mjs'), 'utf8');
  const navigation = fs.readFileSync(path.join(root, 'src/workbench-navigation.mjs'), 'utf8');
  const runtimeSite = fs.readFileSync(path.join(root, 'site/runtime.html'), 'utf8');
  const site = fs.readFileSync(path.join(root, 'site/index.html'), 'utf8');
  const theme = fs.readFileSync(path.join(root, 'site/workbench-theme.css'), 'utf8');
  const workbenchCss = fs.readFileSync(path.join(root, 'site/workbench.css'), 'utf8');
  assert.equal(config.options.cssProvider, 'tailwind');
  assert.equal(config.options.cssPreflight, 'disabled');
  assert.equal(evidence.browserEvidence.matrixCells, 384);
  assert.equal(evidence.performanceEvidence.tailwindRuntimeBytes, 0);
  assert.equal(lessons.undecidedLessonCount, 0);
  assert.match(rmt, /class "xtm-dashboard"/);
  assert.match(rmt, /action workbench\.confirmReview/);
  assert.match(rmt, /validation workbench\.lessonFilter/);
  assert.match(rmt, /transition workbench\.reviewEvidence/);
  assert.doesNotMatch(rmt, /class "(?:grid|flex|p-\d)/);
  assert.doesNotMatch(site, /workbench-dev-api\.mjs/);
  assert.match(devApi, /xtend\.devsurface\.dev-api\.v1/);
  ['getPerformanceSnapshot', 'getFabricTelemetrySnapshot', 'getKernelSnapshot', 'getHydrationSnapshot'].forEach((method) => assert.match(devApi, new RegExp(`${method}\\(`)));
  assert.match(devApi, /installWorkbenchDevApi/);
  assert.doesNotMatch(devApi, /(?:innerHTML|shadowRoot|attachShadow)/);
  assert.match(site, /\/design-tokens\/tailwind\/xtend-material-theme\.css/);
  assert.doesNotMatch(site, /\/xtend-material\/tokens\.css/);
  assert.match(site, /workbench-theme\.css/);
  assert.match(site, /workbench-visual-gate\.mjs/);
  assert.doesNotMatch(site, /<dialog\b[^>]*\bopen\b/u);
  assert.match(site, /commandfor="review-dialog" command="show-modal"/);
  assert.match(theme, /--xtend-surface-page: #f4f7fb/);
  assert.match(theme, /--xtend-text-primary: #172033/);
  assert.match(visualGate, /xtend\.material\.workbench-visual-gate\.v1/);
  assert.match(visualGate, /backgroundColor === 'rgb\(244, 247, 251\)'/);
  assert.match(visualGate, /primaryWidth >= Math\.min\(320, viewportWidth \* 0\.7\)/);
  assert.match(visualGate, /horizontalOverflow === 0/);
  assert.match(visualGate, /devApiAbsent/);
  assert.doesNotMatch(visualGate, /(?:innerHTML|shadowRoot|attachShadow)/);
  assert.match(site, /site\/runtime\.html/);
  assert.match(site, /site\/runtime\.html" target="_blank" rel="noopener"/);
  assert.match(site, /workbench-navigation\.mjs/);
  assert.match(navigation, /xtend\.material\.workbench-navigation\.v1/);
  assert.match(navigation, /addEventListener\('hashchange'/);
  assert.match(navigation, /root\.dataset\.xtmRoute = route/);
  assert.match(navigation, /root\.dataset\.xtmNavigationVisible = String\(visible\)/);
  assert.match(navigation, /navigationRect\.top >= headerRect\.bottom - 1/);
  assert.match(workbenchCss, /height: calc\(100dvh - 4rem\)/);
  assert.match(workbenchCss, /overscroll-behavior: contain/);
  assert.match(runtimeSite, /data-maraca-root/);
  assert.match(runtimeSite, /id="xtm-runtime-mount"[^>]*aria-hidden="true" inert/);
  assert.match(runtimeSite, /id="xtm-runtime-surface-count"/);
  assert.equal((runtimeSite.match(/data-route="(?:evidence|lessons|settings)"/gu) || []).length, 3);
  assert.match(runtimeSite, /data-route="runtime" aria-current="page"/);
  assert.match(runtimeHost, /bootXtendMaraca\(\{ root, lazyStrategy: 'eager' \}\)/);
  assert.match(runtimeHost, /installWorkbenchDevApi/);
  assert.match(runtimeHost, /snapshotsSerializable/);
  assert.match(runtimeHost, /presentationReady/);
  assert.match(runtimeHost, /mountRect\.width <= 1/);
  assert.match(workbenchCss, /\.xtm-runtime-mount \{/);
  assert.match(workbenchCss, /clip-path: inset\(50%\)/);
  assert.match(runtimeHost, /surfaceCount >= 15/);
  assert.doesNotMatch(runtimeHost, /(?:innerHTML|shadowRoot|attachShadow)/);
});
